In [2]:
%load_ext autoreload
%autoreload 2

import sys 
sys.path.append("..")

In [6]:
import importlib 
# from Getnet.src import data_wrangling_mailingHist, utils, data_wrangling_pagamentos, data_wrangling_acordos, data_wrangling_acionamentos#, data_loader
from Estacio.process_digital_channels.utils import queries
from utils import data_loader, queries

# importlib.reload(data_loader)
# importlib.reload(queries)
# importlib.reload(data_wrangling_mailingHist)
importlib.reload(queries)
# importlib.reload(utils)
# importlib.reload(data_wrangling_pagamentos)
# importlib.reload(data_wrangling_acordos)
#importlib.reload(data_processing)
#importlib.reload(metricas_acumuladas)
#importlib.reload(utils)
importlib.reload(data_loader)

In [3]:
import pandas as pd
from utils.db_connection import get_db_connections
from Estacio.process_digital_channels.utils.queries import get_query_mailing_hist

# 1️⃣ Gera a query
query = get_query_mailing_hist(
    dt_ini='2026-01-01',
    dt_fim='2026-01-31',
    where_clause="WHERE M.COD_CLI = 252"
)

# 2️⃣ Abre conexão e executa
with get_db_connections() as (conn_trc, conn_bd2, conn_src):
    df_mailing_hist = pd.read_sql(query, conn_src)

df_mailing_hist

🔌 Conectando aos bancos de dados...
✅ Conexões estabelecidas

C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_4156\2680809198.py:14: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_mailing_hist = pd.read_sql(query, conn_src)

🔌 Conexão TRC fechada
🔌 Conexão BD2 fechada
🔌 Conexão SRC fechada

,DATA,CONTRATO,CPF,ATRASO,COD_CLI,REGIONAL,GRUPO,GRUPO_SEGMENTADO,PRODUTO_SEGMENTADO,SPD,BU,MODALIDE,STDEBITO,STALUNO,CURSO,APROACAD,PRODUTO,ULTRENOV,COD_PRODUT,FX_ATRASO
0,2026-01-12,41686088ID,10437001709,2848,252,SUDESTE,ESTACIO,ESTACIO INATIVO,BASE LIQUIDA,CALOURO 1R,PRESENCIAL,PRES,INATIVO,INATIVO,LOGÍSTICA,8 - BLIQ,RENOVACAO,2018.1,1,N - Maior 1800
1,2026-01-15,41686088ID,10437001709,2851,252,SUDESTE,ESTACIO,ESTACIO INATIVO,BASE LIQUIDA,CALOURO 1R,PRESENCIAL,PRES,INATIVO,INATIVO,LOGÍSTICA,8 - BLIQ,RENOVACAO,2018.1,1,N - Maior 1800
2,2026-01-14,41686088ID,10437001709,2850,252,SUDESTE,ESTACIO,ESTACIO INATIVO,BASE LIQUIDA,CALOURO 1R,PRESENCIAL,PRES,INATIVO,INATIVO,LOGÍSTICA,8 - BLIQ,RENOVACAO,2018.1,1,N - Maior 1800
3,2026-01-07,41686088ID,10437001709,2843,252,SUDESTE,ESTACIO,ESTACIO INATIVO,BASE LIQUIDA,CALOURO 1R,PRESENCIAL,PRES,INATIVO,INATIVO,LOGÍSTICA,8 - BLIQ,RENOVACAO,2018.1,1,N - Maior 1800
4,2026-01-11,41686088ID,10437001709,2846,252,SUDESTE,ESTACIO,ESTACIO INATIVO,BASE LIQUIDA,CALOURO 1R,PRESENCIAL,PRES,INATIVO,INATIVO,LOGÍSTICA,8 - BLIQ,RENOVACAO,2018.1,1,N - Maior 1800
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7992841,2026-01-31,55854906ID,60899178340,-9,252,None,None,OUTROS,RENOVAÇÃO,None,None,None,None,None,None,None,MENSALIDADE,None,2,0 - Menor 8
7992842,2026-01-31,55854907ID,4560090351,123,252,NORDESTE,ESTACIO,ESTACIO ATIVO,BASE LIQUIDA,None,None,PRES,ATIVO,ATIVO,PEDAGOGIA,None,RENOVACAO,2025.2,1,F - 91 - 180
7992843,2026-01-31,55854908ID,4560090351,1,252,None,None,OUTROS,RENOVAÇÃO,None,None,None,None,None,None,None,MENSALIDADE,None,2,A - 01 - 07
7992844,2026-01-31,55854909ID,7709671322,118,252,NORDESTE,ESTACIO,ESTACIO ATIVO,BASE LIQUIDA,None,None,PRES,ATIVO,ATIVO,ENFERMAGEM,None,RENOVACAO,2025.2,1,F - 91 - 180
7992845,2026-01-31,55854910ID,7709671322,1,252,None,None,OUTROS,RENOVAÇÃO,None,None,None,None,None,None,None,MENSALIDADE,None,2,A - 01 - 07

In [4]:
# sobe para Projects 
from Estacio.process_digital_channels.src.data_loader import load_data_estacio

dados = load_data_estacio('2026-01-01', '2026-01-31')

(
# df_discagens_expert, 
# df_mailing_hist, 
# df_tab_acionamentos, 
# df_tabulacao_aciona,
# df_dw_calendario, 
# df_pagamentos, 
# df_acordos, 
df_sms,
df_rcs,
df_email,
df_whatsapp
# df_telefones,
# df_blacklist_expert
) = dados.values()

🔌 Conectando aos bancos de dados...
✅ Conexões estabelecidas

📊 Carregando dados de 2026-01-01 até 2026-01-31...

C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\utils\data_loader.py:484: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conexao)

[1/4] ✓ SMS: 241.890 registros (2s)
[2/4] ✓ RCS: 452.070 registros (4s)
[3/4] ✓ Email: 3.204.874 registros (27s)
[4/4] ✓ WhatsApp: 0 registros (0s)

✅ Carregamento concluído em 34s
🔌 Conexão TRC fechada
🔌 Conexão BD2 fechada
🔌 Conexão SRC fechada

In [19]:

df_sms
#df_rcs
# Filtrar apenas receptivo = 1
# df_filtrado = df_sms[df_sms['RECEPTIVO'] == 1]
# df_filtrado
#df_whatsapp

,DATA_DISPARO,TELEFONE,CPF,CUSTO,RECEPTIVO,PGTO,PGTO_VLR,RECEITA,PROMESSA_VCTO
0,2026-01-05,21981529413,12145054731,0.04,None,None,None,None,None
1,2026-01-05,21995368836,11446592723,0.04,None,None,None,None,None
2,2026-01-05,11979508985,42328184804,0.04,None,None,None,None,None
3,2026-01-05,62994615280,70173965105,0.04,None,None,None,None,None
4,2026-01-05,98984431621,5738379373,0.04,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...
241885,2026-01-06,74999580884,5564631536,0.04,None,None,None,None,None
241886,2026-01-06,88996169833,6434279370,0.04,None,None,None,None,None
241887,2026-01-06,41995654797,9030870907,0.04,None,None,None,None,None
241888,2026-01-06,19993484173,99024900182,0.04,None,None,None,None,None
241889,2026-01-06,31983101128,79750133153,0.04,None,None,None,None,None

In [ ]:
canais = {
    'SMS': df_sms,
    'RCS': df_rcs,
    'WHATS': df_whatsapp,  # remove se não houver dados
    'EMAIL': df_email
}

import pandas as pd
import time

def preparar_canal(df: pd.DataFrame, canal: str) -> pd.DataFrame:
    df = df.copy()
    df['CPF'] = df['CPF'].str.strip()

    if canal in ['SMS', 'RCS', 'WHATS']:
        df = df[['DATA_DISPARO', 'CPF', 'CUSTO', 'TELEFONE']].rename(columns={'TELEFONE': 'CONTATO'})

    elif canal == 'EMAIL':
        df = df[['DATA', 'CPF', 'CUSTO', 'EMAIL']].rename(columns={
            'DATA': 'DATA_DISPARO',
            'EMAIL': 'CONTATO'
        })

    df['CANAL'] = canal
    return df


def cruzar_mailing_canal(df_mailing: pd.DataFrame, df_canal: pd.DataFrame, nome_canal: str) -> tuple[pd.DataFrame, pd.DataFrame]:
    
    inicio = time.time()
    print(f"\n[{nome_canal}] Iniciando cruzamento...")

    # 1. Prepara o canal
    df_canal_prep = preparar_canal(df_canal, nome_canal)

    # 2. Remove espaços do mailing
    df_mailing['CPF'] = df_mailing['CPF'].str.strip()

    # 3. Filtra mailing pelos CPFs do canal
    cpfs_canal = df_canal_prep['CPF'].unique()
    df_mailing_filtrado = df_mailing[df_mailing['CPF'].isin(cpfs_canal)]
    print(f"[{nome_canal}] Mailing filtrado: {df_mailing_filtrado.shape[0]} linhas")

    # 4. Deduplica o mailing
    df_mailing_dedup = (
        df_mailing_filtrado
        .assign(prioridade_grupo=df_mailing_filtrado['GRUPO'].apply(lambda x: 1 if x == 'ESTACIO' else 2))
        .sort_values(['CPF', 'DATA', 'prioridade_grupo', 'ATRASO', 'CONTRATO'],
                     ascending=[True, True, True, False, True])
        .drop_duplicates(subset=['CPF', 'DATA'], keep='first')
        .drop(columns='prioridade_grupo')
    )
    print(f"[{nome_canal}] Mailing deduplicado: {df_mailing_dedup.shape[0]} linhas")

    # 5. Merge com indicador para identificar o que ficou de fora
    df_merge = df_canal_prep.merge(
        df_mailing_dedup,
        left_on=['CPF', 'DATA_DISPARO'],
        right_on=['CPF', 'DATA'],
        how='left',
        indicator=True
    )

    # 6. Separa os dois dfs
    df_com_relacionamento = df_merge[df_merge['_merge'] == 'both'].drop(columns='_merge')
    df_sem_relacionamento = df_merge[df_merge['_merge'] == 'left_only'][['DATA_DISPARO', 'CPF', 'CUSTO', 'CONTATO', 'CANAL']]

    tempo = time.time() - inicio
    print(f"[{nome_canal}] Concluído em {tempo:.1f}s")
    print(f"[{nome_canal}] Com relacionamento: {df_com_relacionamento.shape[0]} linhas")
    print(f"[{nome_canal}] Sem relacionamento: {df_sem_relacionamento.shape[0]} linhas — custo fora: R$ {df_sem_relacionamento['CUSTO'].sum():,.2f}")

    return df_com_relacionamento, df_sem_relacionamento


def cruzar_todos_canais(df_mailing: pd.DataFrame, canais: dict) -> tuple[pd.DataFrame, pd.DataFrame]:
    resultados_com = []
    resultados_sem = []
    inicio_total = time.time()

    for nome_canal, df_canal in canais.items():
        df_com, df_sem = cruzar_mailing_canal(df_mailing, df_canal, nome_canal)
        resultados_com.append(df_com)
        resultados_sem.append(df_sem)

    df_consolidado_com = pd.concat(resultados_com, ignore_index=True)
    df_consolidado_sem = pd.concat(resultados_sem, ignore_index=True)

    tempo_total = time.time() - inicio_total
    print(f"\nTotal com relacionamento: {df_consolidado_com.shape[0]} linhas")
    print(f"Total sem relacionamento: {df_consolidado_sem.shape[0]} linhas — custo total fora: R$ {df_consolidado_sem['CUSTO'].sum():,.2f}")
    print(f"Tempo total: {tempo_total:.1f}s")

    return df_consolidado_com, df_consolidado_sem

#df_consolidado = cruzar_todos_canais(df_mailing_hist, canais)
df_com_relacionamento, df_sem_relacionamento = cruzar_todos_canais(df_mailing_hist, canais)

[SMS] Iniciando cruzamento...
[SMS] Mailing filtrado: 2919317 linhas
[SMS] Mailing deduplicado: 2144874 linhas
[SMS] Concluído em 104.9s
[SMS] Com relacionamento: 230001 linhas
[SMS] Sem relacionamento: 11889 linhas — custo fora: R$ 475.56

[RCS] Iniciando cruzamento...
[RCS] Mailing filtrado: 2652784 linhas
[RCS] Mailing deduplicado: 1884456 linhas
[RCS] Concluído em 43.7s
[RCS] Com relacionamento: 408339 linhas
[RCS] Sem relacionamento: 43731 linhas — custo fora: R$ 2,011.63

[WHATS] Iniciando cruzamento...
[WHATS] Mailing filtrado: 0 linhas
[WHATS] Mailing deduplicado: 0 linhas
[WHATS] Concluído em 1.7s
[WHATS] Com relacionamento: 0 linhas
[WHATS] Sem relacionamento: 0 linhas — custo fora: R$ 0.00

[EMAIL] Iniciando cruzamento...
[EMAIL] Mailing filtrado: 6674271 linhas
[EMAIL] Mailing deduplicado: 5221432 linhas
[EMAIL] Concluído em 346.5s
[EMAIL] Com relacionamento: 3173433 linhas
[EMAIL] Sem relacionamento: 31441 linhas — custo fora: R$ 314.41

Total com relacionamento: 3811773 linhas
Total sem relacionamento: 87061 linhas — custo total fora: R$ 2,801.60
Tempo total: 533.2s

In [33]:
import os
from pathlib import Path

BASE_PATH = Path(r"C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs")

def salvar_analiticos(df_com: pd.DataFrame, df_sem: pd.DataFrame, canal: str) -> None:
    """
    Salva os analíticos de cada canal separados por relacionamento com mailing,
    ano, mês e dia.
    
    Parâmetros:
        df_com: df com relacionamento com mailing
        df_sem: df sem relacionamento com mailing
        canal: nome do canal (SMS, RCS, WHATS, EMAIL)
    """
    canal_lower = canal.lower()
    pasta_canal = BASE_PATH / f"analytical_{canal_lower}"

    dfs = {
        'com_relacion_mailing': df_com,
        'sem_relacion_mailing': df_sem
    }

    for tipo, df in dfs.items():
        if df.empty:
            print(f"[{canal}] {tipo} — df vazio, pulando...")
            continue

        # Garante que DATA_DISPARO é datetime
        df = df.copy()
        df['DATA_DISPARO'] = pd.to_datetime(df['DATA_DISPARO'])

        # Itera por data única
        for data, df_dia in df.groupby(df['DATA_DISPARO'].dt.date):
            ano = str(data.year)
            mes = f"{data.month:02d}"
            dia = f"{data.month:02d}{data.day:02d}"  # ex: 0501

            # Cria estrutura de pastas se não existir
            pasta_destino = pasta_canal / tipo / ano / mes
            pasta_destino.mkdir(parents=True, exist_ok=True)

            # Nome do arquivo ex: analitico_email_0501.csv
            nome_arquivo = f"analitico_{canal_lower}_{dia}.csv"
            caminho_arquivo = pasta_destino / nome_arquivo

            df_dia.to_csv(caminho_arquivo, index=False, sep=';', encoding='utf-8-sig')
            print(f"[{canal}] {tipo} — salvo: {caminho_arquivo}")


def salvar_todos_analiticos(df_com: pd.DataFrame, df_sem: pd.DataFrame) -> None:
    """
    Salva os analíticos de todos os canais presentes nos dfs consolidados.
    """
    inicio = time.time()

    for canal in df_com['CANAL'].unique():
        salvar_analiticos(
            df_com=df_com[df_com['CANAL'] == canal],
            df_sem=df_sem[df_sem['CANAL'] == canal],
            canal=canal
        )

    tempo = time.time() - inicio
    print(f"\nTodos os analíticos salvos em {tempo:.1f}s")

salvar_todos_analiticos(df_com_relacionamento, df_sem_relacionamento)

[SMS] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_sms\com_relacion_mailing\2026\01\analitico_sms_0105.csv
[SMS] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_sms\com_relacion_mailing\2026\01\analitico_sms_0106.csv
[SMS] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_sms\com_relacion_mailing\2026\01\analitico_sms_0107.csv
[SMS] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_sms\com_relacion_mailing\2026\01\analitico_sms_0109.csv
[SMS] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_sms\com_relacion_mailing\2026\01\analitico_sms_0112.csv
[SMS] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_sms\com_relacion_mailing\2026\01\analitico_sms_0116.csv
[SMS] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_sms\sem_relacion_mailing\2026\01\analitico_sms_0105.csv
[SMS] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_sms\sem_relacion_mailing\2026\01\analitico_sms_0106.csv
[SMS] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_sms\sem_relacion_mailing\2026\01\analitico_sms_0107.csv
[SMS] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_sms\sem_relacion_mailing\2026\01\analitico_sms_0109.csv
[SMS] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_sms\sem_relacion_mailing\2026\01\analitico_sms_0112.csv
[SMS] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_sms\sem_relacion_mailing\2026\01\analitico_sms_0116.csv
[RCS] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_rcs\com_relacion_mailing\2026\01\analitico_rcs_0105.csv
[RCS] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_rcs\com_relacion_mailing\2026\01\analitico_rcs_0106.csv
[RCS] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_rcs\com_relacion_mailing\2026\01\analitico_rcs_0107.csv
[RCS] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_rcs\com_relacion_mailing\2026\01\analitico_rcs_0108.csv
[RCS] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_rcs\com_relacion_mailing\2026\01\analitico_rcs_0112.csv
[RCS] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_rcs\com_relacion_mailing\2026\01\analitico_rcs_0113.csv
[RCS] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_rcs\com_relacion_mailing\2026\01\analitico_rcs_0114.csv
[RCS] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_rcs\com_relacion_mailing\2026\01\analitico_rcs_0115.csv
[RCS] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_rcs\com_relacion_mailing\2026\01\analitico_rcs_0120.csv
[RCS] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_rcs\com_relacion_mailing\2026\01\analitico_rcs_0121.csv
[RCS] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_rcs\com_relacion_mailing\2026\01\analitico_rcs_0122.csv
[RCS] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_rcs\com_relacion_mailing\2026\01\analitico_rcs_0127.csv
[RCS] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_rcs\com_relacion_mailing\2026\01\analitico_rcs_0129.csv
[RCS] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_rcs\sem_relacion_mailing\2026\01\analitico_rcs_0105.csv
[RCS] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_rcs\sem_relacion_mailing\2026\01\analitico_rcs_0106.csv
[RCS] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_rcs\sem_relacion_mailing\2026\01\analitico_rcs_0107.csv
[RCS] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_rcs\sem_relacion_mailing\2026\01\analitico_rcs_0108.csv
[RCS] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_rcs\sem_relacion_mailing\2026\01\analitico_rcs_0112.csv
[RCS] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_rcs\sem_relacion_mailing\2026\01\analitico_rcs_0113.csv
[RCS] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_rcs\sem_relacion_mailing\2026\01\analitico_rcs_0114.csv
[RCS] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_rcs\sem_relacion_mailing\2026\01\analitico_rcs_0115.csv
[RCS] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_rcs\sem_relacion_mailing\2026\01\analitico_rcs_0120.csv
[RCS] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_rcs\sem_relacion_mailing\2026\01\analitico_rcs_0121.csv
[RCS] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_rcs\sem_relacion_mailing\2026\01\analitico_rcs_0122.csv
[RCS] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_rcs\sem_relacion_mailing\2026\01\analitico_rcs_0127.csv
[RCS] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_rcs\sem_relacion_mailing\2026\01\analitico_rcs_0129.csv
[EMAIL] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\com_relacion_mailing\2026\01\analitico_email_0105.csv
[EMAIL] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\com_relacion_mailing\2026\01\analitico_email_0106.csv
[EMAIL] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\com_relacion_mailing\2026\01\analitico_email_0107.csv
[EMAIL] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\com_relacion_mailing\2026\01\analitico_email_0108.csv
[EMAIL] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\com_relacion_mailing\2026\01\analitico_email_0112.csv
[EMAIL] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\com_relacion_mailing\2026\01\analitico_email_0113.csv
[EMAIL] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\com_relacion_mailing\2026\01\analitico_email_0114.csv
[EMAIL] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\com_relacion_mailing\2026\01\analitico_email_0115.csv
[EMAIL] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\com_relacion_mailing\2026\01\analitico_email_0116.csv
[EMAIL] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\com_relacion_mailing\2026\01\analitico_email_0119.csv
[EMAIL] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\com_relacion_mailing\2026\01\analitico_email_0120.csv
[EMAIL] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\com_relacion_mailing\2026\01\analitico_email_0121.csv
[EMAIL] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\com_relacion_mailing\2026\01\analitico_email_0122.csv
[EMAIL] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\com_relacion_mailing\2026\01\analitico_email_0123.csv
[EMAIL] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\com_relacion_mailing\2026\01\analitico_email_0126.csv
[EMAIL] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\com_relacion_mailing\2026\01\analitico_email_0127.csv
[EMAIL] com_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\com_relacion_mailing\2026\01\analitico_email_0129.csv
[EMAIL] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\sem_relacion_mailing\2026\01\analitico_email_0105.csv
[EMAIL] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\sem_relacion_mailing\2026\01\analitico_email_0106.csv
[EMAIL] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\sem_relacion_mailing\2026\01\analitico_email_0107.csv
[EMAIL] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\sem_relacion_mailing\2026\01\analitico_email_0108.csv
[EMAIL] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\sem_relacion_mailing\2026\01\analitico_email_0112.csv
[EMAIL] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\sem_relacion_mailing\2026\01\analitico_email_0113.csv
[EMAIL] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\sem_relacion_mailing\2026\01\analitico_email_0114.csv
[EMAIL] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\sem_relacion_mailing\2026\01\analitico_email_0115.csv
[EMAIL] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\sem_relacion_mailing\2026\01\analitico_email_0116.csv
[EMAIL] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\sem_relacion_mailing\2026\01\analitico_email_0119.csv
[EMAIL] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\sem_relacion_mailing\2026\01\analitico_email_0121.csv
[EMAIL] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\sem_relacion_mailing\2026\01\analitico_email_0122.csv
[EMAIL] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\sem_relacion_mailing\2026\01\analitico_email_0123.csv
[EMAIL] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\sem_relacion_mailing\2026\01\analitico_email_0126.csv
[EMAIL] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\sem_relacion_mailing\2026\01\analitico_email_0127.csv
[EMAIL] sem_relacion_mailing — salvo: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\data_analytcs\analytical_email\sem_relacion_mailing\2026\01\analitico_email_0129.csv

Todos os analíticos salvos em 273.7s

In [34]:
def resumo_canais(df: pd.DataFrame) -> pd.DataFrame:
    
    resultado = (
        df.groupby(['DATA', 'CANAL', 'GRUPO_SEGMENTADO', 'PRODUTO_SEGMENTADO'])
        .agg(
            qte_cpf_unique=('CPF', 'nunique'),
            qte_envio=('CPF', 'count'),
            custo=('CUSTO', 'sum'),
        )
        .reset_index()
    )

    # Salva o resumo
    caminho = Path(r"C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data")
    caminho.mkdir(parents=True, exist_ok=True)
    
    caminho_arquivo = caminho / "digital_channels.xlsx"
    resultado.to_excel(caminho_arquivo, index=False, engine='openpyxl')
    print(f"Resumo salvo em: {caminho_arquivo}")

    return resultado

df_massivos_over = resumo_canais(df_com_relacionamento)
df_massivos_over

Resumo salvo em: C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Estacio\process_digital_channels\Data\digital_channels.xlsx

,DATA,CANAL,GRUPO_SEGMENTADO,PRODUTO_SEGMENTADO,qte_cpf_unique,qte_envio,custo
0,2026-01-05,EMAIL,ESTACIO ATIVO,BASE LIQUIDA,34101,34108,341.080
1,2026-01-05,EMAIL,ESTACIO ATIVO,RENOVAÇÃO,5,5,0.050
2,2026-01-05,EMAIL,ESTACIO INATIVO,BASE LIQUIDA,129211,132355,1323.550
3,2026-01-05,EMAIL,ESTACIO INATIVO,RENOVAÇÃO,136,144,1.440
4,2026-01-05,EMAIL,OUTROS,BASE LIQUIDA,57,57,0.570
...,...,...,...,...,...,...,...
314,2026-01-29,RCS,ESTACIO INATIVO,RENOVAÇÃO,13,13,0.598
315,2026-01-29,RCS,OUTROS,BASE LIQUIDA,8,8,0.368
316,2026-01-29,RCS,OUTROS,RENOVAÇÃO,10,10,0.460
317,2026-01-29,RCS,WYDEN ATIVO,BASE LIQUIDA,1,1,0.046
318,2026-01-29,RCS,WYDEN INATIVO,BASE LIQUIDA,88,94,4.324