In [ ]:
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> GERAR DADOS

# import importlib
# importlib.reload(queries)
from src.data_wrangling_mailingHist import tratar_base_mailing_hist
from src.db_connection import get_connection
from Projects.Ouze.src.queries import get_query_discagens, get_query_cad_devf, get_query_mailing_hist, get_query_discagens_trestto, get_query_tabulacao_aciona, get_query_base_acionamentos, get_query_dw_calendario, get_query_pagamentos, get_query_acordos
import pandas as pd

# DADOS SRC

def data_loader(conn_trc, conn_bd2, conn_src):

    df_discagens_expert = pd.read_sql(
        get_query_discagens('2025-09-01', '2025-09-30'), 
        conn_src
    )
    df_cad_devf = pd.read_sql(
        get_query_cad_devf(), 
        conn_src
    )
    df_tab_acionamentos = pd.read_sql(
        get_query_base_acionamentos('2025-09-01', '2025-09-30'), 
        conn_src
    )

    # DADOS BD2/PLANEJAMENTO
    df_maling_hist = pd.read_sql(
        get_query_mailing_hist('2025-09-01', '2025-09-30'), 
        conn_bd2
    )
    df_maling_hist = tratar_base_mailing_hist(df_maling_hist, df_cad_devf)

    df_dw_calendario = pd.read_sql(
        get_query_dw_calendario(), 
        conn_bd2
    )
    df_tabulacao_aciona = pd.read_sql(
        get_query_tabulacao_aciona(), 
        conn_bd2
    )
    df_pagamentos = pd.read_sql(
        get_query_pagamentos('2025-09-01', '2025-09-30'), 
        conn_src
    )
    df_acordos = pd.read_sql(
        get_query_acordos('2025-09-01', '2025-09-30'), 
        conn_src
    )

    # DADOS BD2/TRC
    
    df_discagens_trestto = pd.read_sql(
        get_query_discagens_trestto('2025-09-01', '2025-09-30'), 
        conn_trc
    )
    
    return df_discagens_expert, df_cad_devf, df_tab_acionamentos, df_maling_hist, df_dw_calendario, df_tabulacao_aciona, df_pagamentos, df_acordos, df_discagens_trestto

def get_connection():
    conn_trc = get_connection("SERVER_BD2", "DATABASE_TRC")
    conn_bd2 = get_connection("SERVER_BD2", "DATABASE_BD2")
    conn_src = get_connection("SERVER_SRC", "DATABASE_SRC")

    df_discagens_expert, df_cad_devf, df_tab_acionamentos, df_maling_hist, df_dw_calendario, df_tabulacao_aciona, df_pagamentos, df_acordos, df_discagens_trestto = data_loader(conn_trc, conn_bd2, conn_src)

    return df_discagens_expert, df_cad_devf, df_tab_acionamentos, df_maling_hist, df_dw_calendario, df_tabulacao_aciona, df_pagamentos, df_acordos, df_discagens_trestto

In [ ]:
import importlib
from src import(queries, data_wrangling_discagens_trestto, data_wrangling_mailingHist, data_wrangling_acionamentos, data_wrangling_discagens_expert, data_wrangling_pagamentos, utils, pipeline_funil, data_loader, csv_cleaning)
importlib.reload(utils)
importlib.reload(data_loader)
importlib.reload(pipeline_funil)
importlib.reload(data_wrangling_discagens_trestto)
importlib.reload(data_wrangling_mailingHist)
importlib.reload(data_wrangling_acionamentos)
importlib.reload(data_wrangling_discagens_expert)
importlib.reload(data_wrangling_pagamentos)
importlib.reload(queries)
importlib.reload(csv_cleaning)

# 1. Carregar e ativar autoreload
# %load_ext autoreload
# %autoreload 2

# # 2. Fazer suas importações normalmente
# from src import (
#     queries,
#     data_wrangling_discagens_trestto,
#     data_wrangling_mailingHist,
#     data_wrangling_acionamentos,
#     data_wrangling_discagens_expert,
#     data_wrangling_pagamentos,
#     utils,
#     pipeline_funil,
#     data_loader,
#     csv_cleaning
# )

In [46]:
# from src.data_wrangling_mailingHist import tratar_base_mailing_hist
# from src.data_wrangling_discagens_expert import acionamentos_expert
from src.db_connection import get_connection
from src.queries import get_query_discagens, get_query_cad_devf, get_query_mailing_hist, get_query_discagens_trestto, get_query_tabulacao_aciona, get_query_base_acionamentos, get_query_dw_calendario, get_query_pagamentos, get_query_acordos
import pandas as pd
conn_trc = get_connection("SERVER_BD2", "DATABASE_TRC")
conn_bd2 = get_connection("SERVER_BD2", "DATABASE_BD2")
conn_src = get_connection("SERVER_SRC", "DATABASE_SRC")
# df_discagens_expert = pd.read_sql(
#     get_query_discagens('2025-11-01', '2025-11-17'), 
#     conn_src
# )
# df_cad_devf = pd.read_sql(
#     get_query_cad_devf(), 
#     conn_src
# )
# df_maling_hist = pd.read_sql(
#     get_query_mailing_hist('2025-11-01', '2025-11-17'), 
#     conn_bd2
# )
# df_maling_hist = tratar_base_mailing_hist(df_maling_hist, df_cad_devf)
df_dw_calendario = pd.read_sql(
    get_query_dw_calendario('2025-11-01', '2025-11-30'), 
    conn_bd2
)
df_dw_calendario
#df_acionamentos_expert, df_analitico_expert, df_enriquecido_discagens_expert_semFaixa, df_humano_tabulados_como_robo, df_dicagens_operacaoOutros = acionamentos_expert(df_discagens_expert, df_dw_calendario, df_maling_hist)
#df_acionamentos_expert

C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_38420\2890686504.py:22: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_dw_calendario = pd.read_sql(

,dt_data,dt_ano,dt_mes,dt_dia,nr_dia_semana,nr_dia_ano,fl_dia_util,nr_dia_util,quartil,mes_abreviado
0,2025-11-03,2025,11,3,2,307,1,1,Q4,Nov
1,2025-11-04,2025,11,4,3,308,1,2,Q4,Nov
2,2025-11-05,2025,11,5,4,309,1,3,Q4,Nov
3,2025-11-06,2025,11,6,5,310,1,4,Q4,Nov
4,2025-11-07,2025,11,7,6,311,1,5,Q4,Nov
5,2025-11-10,2025,11,10,2,314,1,6,Q4,Nov
6,2025-11-11,2025,11,11,3,315,1,7,Q4,Nov
7,2025-11-12,2025,11,12,4,316,1,8,Q4,Nov
8,2025-11-13,2025,11,13,5,317,1,9,Q4,Nov
9,2025-11-14,2025,11,14,6,318,1,10,Q4,Nov
10,2025-11-17,2025,11,17,2,321,1,11,Q4,Nov
11,2025-11-18,2025,11,18,3,322,1,12,Q4,Nov
12,2025-11-19,2025,11,19,4,323,1,13,Q4,Nov
13,2025-11-21,2025,11,21,6,325,1,14,Q4,Nov
14,2025-11-24,2025,11,24,2,328,1,15,Q4,Nov
15,2025-11-25,2025,11,25,3,329,1,16,Q4,Nov
16,2025-11-26,2025,11,26,4,330,1,17,Q4,Nov
17,2025-11-27,2025,11,27,5,331,1,18,Q4,Nov
18,2025-11-28,2025,11,28,6,332,1,19,Q4,Nov

In [6]:
#from src.data_wrangling_mailingHist import tratar_base_mailing_hist, gerar_acumulado_mailing_hist
#from src.data_wrangling_discagens_expert import acionamentos_expert
from src.db_connection import get_connection
from src.queries import get_query_discagens, get_query_cad_devf, get_query_mailing_hist, get_query_discagens_trestto, get_query_tabulacao_aciona, get_query_base_acionamentos, get_query_dw_calendario, get_query_pagamentos, get_query_acordos
import pandas as pd
conn_trc = get_connection("SERVER_BD2", "DATABASE_TRC")
conn_bd2 = get_connection("SERVER_BD2", "DATABASE_BD2")
conn_src = get_connection("SERVER_SRC", "DATABASE_SRC")

# df_cad_devf = pd.read_sql(
#     get_query_cad_devf(), 
#     conn_src
# )
# df_maling_hist = pd.read_sql(
#     get_query_mailing_hist('2025-11-01', '2025-11-17'), 
#     conn_bd2
# )
# df_maling_hist = tratar_base_mailing_hist(df_maling_hist, df_cad_devf)
df_dw_calendario = pd.read_sql(
    get_query_dw_calendario('2025-11-01', '2025-11-17'), 
    conn_bd2
)
# df_maling_acumulado = gerar_acumulado_mailing_hist(df_maling_hist, df_dw_calendario)
# df_maling_acumulado
df_dw_calendario

C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_38420\1509880068.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_dw_calendario = pd.read_sql(

,dt_data,dt_ano,dt_mes,dt_dia,nr_dia_semana,nr_dia_ano,fl_dia_util,nr_dia_util,quartil,mes_abreviado
0,2025-11-03,2025,11,3,2,307,1,1,Q4,Nov
1,2025-11-04,2025,11,4,3,308,1,2,Q4,Nov
2,2025-11-05,2025,11,5,4,309,1,3,Q4,Nov
3,2025-11-06,2025,11,6,5,310,1,4,Q4,Nov
4,2025-11-07,2025,11,7,6,311,1,5,Q4,Nov
5,2025-11-10,2025,11,10,2,314,1,6,Q4,Nov
6,2025-11-11,2025,11,11,3,315,1,7,Q4,Nov
7,2025-11-12,2025,11,12,4,316,1,8,Q4,Nov
8,2025-11-13,2025,11,13,5,317,1,9,Q4,Nov
9,2025-11-14,2025,11,14,6,318,1,10,Q4,Nov
10,2025-11-17,2025,11,17,2,321,1,11,Q4,Nov

In [ ]:
from src.db_connection import get_connection
from src.queries import get_query_discagens, get_query_cad_devf, get_query_mailing_hist, get_query_discagens_trestto, get_query_tabulacao_aciona, get_query_base_acionamentos, get_query_dw_calendario, get_query_pagamentos, get_query_acordos
#from src.data_wrangling_discagens_trestto import enriquecer_discagens_trestto, acionamentos_fxAtraso_origem_trestto
from src.data_wrangling_acionamentos import tratar_acionamentos_tabulacao, confere_tabulacao_acionamentos, enriquecer_acionamentos, acionamentos_fxAtraso_origem_humano
from src.data_wrangling_discagens_trestto import acionamentos_trestto
from src.data_wrangling_mailingHist import tratar_base_mailing_hist
from src.utils import transformar_funil_formato_long
import pandas as pd
# conn_trc = get_connection("SERVER_BD2", "DATABASE_TRC")
# conn_src = get_connection("SERVER_SRC", "DATABASE_SRC")
# conn_bd2 = get_connection("SERVER_BD2", "DATABASE_BD2")
# df_discagens_trestto = pd.read_sql(
#     get_query_discagens_trestto('2025-11-01', '2025-11-20'), 
#     conn_trc
# )
# df_cad_devf = pd.read_sql(
#     get_query_cad_devf(), 
#     conn_src
# )
# df_maling_hist = pd.read_sql(
#     get_query_mailing_hist('2025-11-01', '2025-11-25'), 
#     conn_bd2
# )
# df_maling_hist = tratar_base_mailing_hist(df_maling_hist, df_cad_devf)
# df_tabulacao_aciona = pd.read_sql(
#     get_query_tabulacao_aciona(), 
#     conn_bd2
# )
# df_tab_acionamentos = pd.read_sql(
#     get_query_base_acionamentos('2025-11-01', '2025-11-25'), 
#     conn_src
# )
# df_dw_calendario = pd.read_sql(
#     get_query_dw_calendario('2025-11-01', '2025-11-25'), 
#     conn_bd2
# )
df_acionamentos_trestto, df_analitico_trestto, df_enriquecido_discagens_trestto_semFaixa = acionamentos_trestto(df_discagens_trestto, df_maling_hist, df_dw_calendario)
df_acionamentos_trestto

In [130]:
import os
# #df_conflitos_score
#df_acionamentos_enriquecido_limpo, df_acion_semFaixa, df_acion_semDescricao, df_acion_semOrigem 
df_final.to_csv('df_final.csv', sep=';', index=False, decimal=',', encoding='utf-8-sig')
os.startfile('df_final.csv')  # abre com o programa padrão

In [ ]:
from src.data_loader import get_date_range_from_csv

var = get_date_range_from_csv()
var

In [ ]:
# INTERSEÇÃO DE CPFS DISCADOS COM E SEM FAIXA DE ATRASO

from src.data_wrangling_discagens_trestto import tratar_discagens_trestto, enriquecer_discagens_trestto, acionamentos_esforco_trestto, interseção_cpfs_discados_trestto

mesagem_resultado = interseção_cpfs_discados_trestto(df_enriquecido_discagens_trestto_limpo, df_enriquecido_discagens_trestto_semFaixa)
mesagem_resultado

In [57]:

caminho_csv = r"\\trc-dc-ad\Planejamento\MIS\CARTEIRAS\WILLBANK\Automations\base_tempos.csv"
def obter_ultima_data_arquivo(caminho_csv):
    """
    Lê o arquivo CSV e retorna a última data de atendimento.
    """
    try:
        # Ler CSV
        df = pd.read_csv(caminho_csv, encoding='utf-8-sig', sep=';')
        
        # Normalizar nomes de colunas (remover espaços)
        df.columns = df.columns.str.strip()
        
        if 'data_insert' not in df.columns:
            raise ValueError("Coluna 'data_insert' não encontrada no arquivo")
        
        # Remover espaços e caracteres estranhos da coluna
        df['data_insert'] = df['data_insert'].astype(str).str.strip()
        
        # Converter para datetime
        df['data_insert'] = pd.to_datetime(
            df['data_insert'].str.strip(),
            format='%d/%m/%Y',   # força o formato brasileiro
            errors='coerce'
        )

        print(df['data_insert'].sort_values().tail(10))
        
        # Verificar se alguma data foi convertida
        if df['data_insert'].isna().all():
            raise ValueError("Nenhuma data válida encontrada. Verifique o formato no CSV.")
        
        # Obter a última data válida
        ultima_data = df['data_insert'].max()
        
        print(f"Última data encontrada no arquivo: {ultima_data.strftime('%d/%m/%Y')}")
        return ultima_data
    
    except Exception as e:
        print(f"Erro ao ler arquivo: {str(e)}")
        import traceback
        traceback.print_exc()
        raise

data = obter_ultima_data_arquivo(caminho_csv)
data

795   NaT
796   NaT
797   NaT
798   NaT
799   NaT
800   NaT
801   NaT
802   NaT
803   NaT
804   NaT
Name: data_insert, dtype: datetime64[ns]
Última data encontrada no arquivo: 03/12/2025

Timestamp('2025-12-03 00:00:00')

In [58]:
caminho_csv = r"\\trc-dc-ad\Planejamento\MIS\CARTEIRAS\WILLBANK\Automations\base_tempos.csv"
df = pd.read_csv(caminho_csv, encoding='utf-8-sig', sep=';')
        
# Normalizar nomes de colunas (remover espaços)
df.columns = df.columns.str.strip()

if 'data_insert' not in df.columns: 
    raise ValueError("Coluna 'data_insert' não encontrada no arquivo")

# Remover espaços e caracteres estranhos da coluna
df['data_insert'] = df['data_insert'].astype(str).str.strip()

# Converter para datetime
df['data_insert'] = pd.to_datetime(
    df['data_insert'].str.strip(),
    format='%d/%m/%Y',   # força o formato brasileiro
    errors='coerce'
)

print(df['data_insert'].sort_values().tail(10))
print(df['data_insert'].unique())
print(df.loc[620:630, 'data_insert'])

795   NaT
796   NaT
797   NaT
798   NaT
799   NaT
800   NaT
801   NaT
802   NaT
803   NaT
804   NaT
Name: data_insert, dtype: datetime64[ns]
<DatetimeArray>
['2025-11-01 00:00:00', '2025-11-03 00:00:00', '2025-11-04 00:00:00',
 '2025-11-05 00:00:00', '2025-11-06 00:00:00', '2025-11-07 00:00:00',
 '2025-11-08 00:00:00', '2025-11-10 00:00:00', '2025-11-11 00:00:00',
 '2025-11-12 00:00:00', '2025-11-13 00:00:00', '2025-11-14 00:00:00',
 '2025-11-17 00:00:00', '2025-11-18 00:00:00', '2025-11-19 00:00:00',
 '2025-11-21 00:00:00', '2025-11-22 00:00:00', '2025-11-24 00:00:00',
 '2025-11-25 00:00:00', '2025-11-26 00:00:00', '2025-11-27 00:00:00',
 '2025-11-28 00:00:00', '2025-11-29 00:00:00', '2025-12-01 00:00:00',
 '2025-12-02 00:00:00', '2025-12-03 00:00:00',                 'NaT']
Length: 27, dtype: datetime64[ns]
620   2025-11-27
621   2025-11-27
622   2025-11-27
623   2025-11-27
624   2025-11-27
625   2025-11-27
626   2025-11-27
627   2025-11-27
628   2025-11-27
629   2025-11-27
630   2025-11-27
Name: data_insert, dtype: datetime64[ns]

In [27]:
# ...existing code...
caminho_csv = r"\\trc-dc-ad\Planejamento\MIS\CARTEIRAS\WILLBANK\Automations\base_tempos.csv"
def obter_ultima_data_arquivo(caminho_csv):
    """
    Lê o CSV e retorna a MAIOR data encontrada na coluna de data.
    Detecta 'data_insert' ou 'data_atendimento' ou usa a primeira coluna.
    Remove linhas de header acidental e valores inválidos antes de calcular o max.
    """
    try:
        # Ler tudo como string para evitar inferências estranhas
        df = pd.read_csv(caminho_csv, encoding='utf-8-sig', sep=';', dtype=str, keep_default_na=False)
        df.columns = df.columns.str.strip()
        if df.shape[0] == 0:
            raise ValueError("Arquivo vazio")

        # escolher coluna de data: preferir data_insert, depois data_atendimento, senão primeira coluna
        if 'data_insert' in df.columns:
            date_col = 'data_insert'
        elif 'data_atendimento' in df.columns:
            date_col = 'data_atendimento'
        else:
            date_col = df.columns[0]

        s = df[date_col].astype(str).str.strip()

        # remover linhas que sejam exatamente o nome da coluna (header inserido) ou vazias
        mask_header_like = s.str.lower() == date_col.lower()
        mask_empty = s == '' 
        s_clean = s[~(mask_header_like | mask_empty)].copy()

        # converter com heurística (dayfirst True para formatos DD/MM/YYYY) e inferência
        s_dt = pd.to_datetime(s_clean, dayfirst=True, infer_datetime_format=True, errors='coerce')

        # relatório mínimo (útil para debug)
        n_total = len(s)
        n_valid = s_dt.notna().sum()
        n_invalid = n_total - n_valid
        print(f"Coluna detectada: '{date_col}' — total:{n_total} válidas:{n_valid} inválidas:{n_invalid}")

        if s_dt.notna().sum() == 0:
            raise ValueError("Nenhuma data válida encontrada após limpeza. Verifique formatos ou linhas de header no CSV.")

        ultima_data = s_dt.max()
        print(f"Última data encontrada no arquivo: {ultima_data.strftime('%d/%m/%Y')}")
        return ultima_data

    except FileNotFoundError:
        print(f"Arquivo não encontrado: {caminho_csv}")
        raise
    except Exception as e:
        print(f"Erro ao obter última data: {e}")
        import traceback
        traceback.print_exc()
        raise

# ...existing code...

def obter_ultima_data_arquivo(caminho_csv):
    """
    Lê o CSV e retorna a MAIOR data encontrada na coluna de data.
    - detecta 'data_insert' ou 'data_atendimento' ou usa a primeira coluna
    - lê tudo como string, limpa ruídos (quotes, prefixes tipo b'...', headers inseridos),
      tenta parse em vários formatos e retorna o max válido.
    """
    import re

    try:
        # Ler como string para evitar coerções estranhas
        df = pd.read_csv(caminho_csv, encoding='utf-8-sig', sep=';', dtype=str, keep_default_na=False)
        df.columns = df.columns.str.strip()

        if df.shape[0] == 0:
            raise ValueError("Arquivo vazio")

        # escolher coluna de data
        if 'data_insert' in df.columns:
            col = 'data_insert'
        elif 'data_atendimento' in df.columns:
            col = 'data_atendimento'
        else:
            col = df.columns[0]

        s = df[col].astype(str).str.strip()

        # remover linhas que são header inserido ou claramente vazias
        mask_header = s.str.lower() == col.lower()
        mask_empty = s == '' 
        s = s[~(mask_header | mask_empty)].copy()

        if s.empty:
            raise ValueError("Nenhum valor não-vazio encontrado na coluna de datas")

        # limpeza básica: remover quotes, prefixes b'...', controle de caracteres estranhos
        s = s.str.replace(r"^b['\"]", "", regex=True).str.replace(r"['\"]$", "", regex=True)
        s = s.str.replace(r"[^\d\-/:\s]", "", regex=True).str.strip()

        # Tentar converter diretamente (vários formatos suportados)
        dt = pd.to_datetime(s, dayfirst=True, infer_datetime_format=True, errors='coerce')

        # Se muitos NaT, tentar extrair padrões comuns (YYYY-MM-DD HH:MM:SS ou DD/MM/YYYY)
        if dt.isna().sum() > 0:
            def extract_best(x):
                if pd.isna(x):
                    return x
                txt = str(x)
                # padrões possíveis
                m = re.search(r"(\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2})", txt)
                if m:
                    return m.group(1)
                m = re.search(r"(\d{4}-\d{2}-\d{2})", txt)
                if m:
                    return m.group(1)
                m = re.search(r"(\d{2}/\d{2}/\d{4})", txt)
                if m:
                    return m.group(1)
                return txt

            s2 = s.map(extract_best)
            dt2 = pd.to_datetime(s2, dayfirst=True, infer_datetime_format=True, errors='coerce')
            # combinar: preferir dt2 quando dt for NaT
            dt = dt.fillna(dt2)

        n_total = len(s)
        n_valid = dt.notna().sum()
        n_invalid = n_total - n_valid
        print(f"Coluna detectada: '{col}' — total:{n_total} válidas:{n_valid} inválidas:{n_invalid}")

        if n_valid == 0:
            raise ValueError("Nenhuma data válida encontrada após limpeza. Verifique o conteúdo do CSV.")

        ultima = dt.max()
        print(f"Última data encontrada no arquivo: {ultima.strftime('%d/%m/%Y')}")
        return ultima

    except FileNotFoundError:
        print(f"Arquivo não encontrado: {caminho_csv}")
        raise
    except Exception as e:
        print(f"Erro ao obter última data: {e}")
        import traceback
        traceback.print_exc()
        raise

# ...existing code...

def obter_ultima_data_arquivo(caminho_csv):
    """
    Lê o arquivo CSV e retorna a última data de atendimento.
    
    Parâmetros:
    -----------
    caminho_csv : str
        Caminho do arquivo CSV
    
    Retorna:
    --------
    datetime : Última data encontrada no arquivo
    """
    try:
        # Ler CSV com delimitador ponto e vírgula
        df = pd.read_csv(caminho_csv, encoding='utf-8-sig', sep=';')
        
        # Verificar se a coluna existe
        print(f"Colunas encontradas no arquivo ({len(df.columns)} colunas):")
        print(list(df.columns)[:10])  # Mostrar apenas as 10 primeiras
        
        if 'data_atendimento' not in df.columns:
            raise ValueError("Coluna 'data_atendimento' não encontrada no arquivo")
        
        # Mostrar exemplo de como a data está no arquivo
        print(f"Exemplo de data no arquivo: {df['data_atendimento'].iloc[0]}")
        
        # Tentar converter para datetime com dayfirst=True (formato brasileiro)
        df['data_atendimento'] = pd.to_datetime(df['data_atendimento'], dayfirst=True, errors='coerce')
        
        # Verificar se conseguiu converter
        if df['data_atendimento'].isna().all():
            raise ValueError("Não foi possível converter nenhuma data. Verifique o formato das datas no arquivo.")
        
        # Obter a última data
        ultima_data = df['data_atendimento'].max()
        
        # Verificar se a última data é válida
        if pd.isna(ultima_data):
            raise ValueError("Última data é inválida (NaT)")
        
        print(f"Última data encontrada no arquivo: {ultima_data.strftime('%d/%m/%Y')}")
        
        return ultima_data
        
    except Exception as e:
        print(f"Erro ao ler arquivo: {str(e)}")
        import traceback
        traceback.print_exc()
        raise

ultima_data = obter_ultima_data_arquivo(caminho_csv)
ultima_data
# ...existing code...

Colunas encontradas no arquivo (34 colunas):
['data_insert', 'hora_insert', 'id_agente', 'nome_agente', 'cpf_agente', 'nome_supervisor', 'coluna_fixa', 'data_atendimento', 'tempo_logado', 'hora_login']
Exemplo de data no arquivo: 01/11/2025
Última data encontrada no arquivo: 26/11/2025

Timestamp('2025-11-26 00:00:00')

In [128]:
import pandas as pd
from dotenv import load_dotenv
from src.db_connection import get_connection

conn_bd2 = get_connection("SERVER_BD2", "DATABASE_BD2")
sql_file = r"\\trc-dc-ad\Planejamento\MIS\CARTEIRAS\PayJoy\Daily_PayJoy.sql"

def df_consulta(conn_bd2, sql_file):
    # Lê o conteúdo da query
    with open(sql_file, "r", encoding="utf-8") as f:
        query = f.read()

    cursor = conn_bd2.cursor()
    
    try:
        # Executa a query completa
        cursor.execute(query)
        
        # Percorre todos os resultados até encontrar um com dados
        columns = None
        data = None
        
        # Tenta buscar o primeiro resultado
        if cursor.description:
            columns = [column[0] for column in cursor.description]
            data = cursor.fetchall()
        
        # Avança pelos resultados até encontrar o último com dados
        while cursor.nextset():
            if cursor.description:
                columns = [column[0] for column in cursor.description]
                data = cursor.fetchall()
        
        # Verifica se encontrou dados
        if columns is None or data is None:
            raise ValueError("Nenhum resultado encontrado na query")
        
        # Cria o DataFrame
        df = pd.DataFrame.from_records(data, columns=columns)
        
        return df
        
    except Exception as e:
        print(f"Erro ao executar query: {e}")
        raise
    finally:
        cursor.close()

# Executa a consulta
df_consulta_df = df_consulta(conn_bd2, sql_file)

# Verifica quantas datas únicas existem
datas_unicas = df_consulta_df['DATA'].unique()
print(f"Datas encontradas: {datas_unicas}")
print(f"Total de datas: {len(datas_unicas)}")

# Define automaticamente as colunas de indicadores
# Todas as colunas EXCETO 'DATA' e 'FAIXA'
colunas_todas = df_consulta_df.columns.tolist()
colunas_id = ['DATA', 'FAIXA']  # Colunas identificadoras
value_columns = [col for col in colunas_todas if col not in colunas_id]

print(f"\nColunas identificadoras: {colunas_id}")
print(f"Total de indicadores encontrados: {len(value_columns)}")

# Faz o unpivot (melt) mantendo DATA e FAIXA como identificadores
df_transposto = df_consulta_df.melt(
    id_vars=['DATA', 'FAIXA'],
    value_vars=value_columns,
    var_name='Indicador',
    value_name='Valor'
)

print(f"\nDataFrame após melt:")
print(df_transposto.head(10))

# Pivota para colocar as datas como colunas
df_final = df_transposto.pivot_table(
    index=['FAIXA', 'Indicador'],
    columns='DATA',
    values='Valor',
    aggfunc='first'  # Usa o primeiro valor caso haja duplicatas
).reset_index()

# Remove o nome do índice das colunas (fica mais limpo)
df_final.columns.name = None

# Ordena por FAIXA e Indicador
df_final = df_final.sort_values(['FAIXA', 'Indicador']).reset_index(drop=True)

# Visualiza o resultado
print(f"\n{'='*60}")
print(f"Estrutura final:")
print(f"Total de linhas: {len(df_final)}")
print(f"Faixas únicas: {df_final['FAIXA'].unique()}")
print(f"Colunas: {df_final.columns.tolist()}")
print(f"{'='*60}")
print("\nPrimeiras 30 linhas:")
print(df_final.head(30))

df_final

Datas encontradas: [datetime.date(2025, 12, 4)]
Total de datas: 1

Colunas identificadoras: ['DATA', 'FAIXA']
Total de indicadores encontrados: 23

DataFrame após melt:
         DATA       FAIXA            Indicador  Valor
0  2025-12-04   DPD 16-30   Assigned_Portfolio   1614
1  2025-12-04   DPD 31-60   Assigned_Portfolio   2680
2  2025-12-04   DPD 61-90   Assigned_Portfolio   2084
3  2025-12-04  DPD 91-120   Assigned_Portfolio   1869
4  2025-12-04   DPD 16-30  Reachable_Portfolio      0
5  2025-12-04   DPD 31-60  Reachable_Portfolio      0
6  2025-12-04   DPD 61-90  Reachable_Portfolio      0
7  2025-12-04  DPD 91-120  Reachable_Portfolio      0
8  2025-12-04   DPD 16-30  Contacted_Portfolio   1423
9  2025-12-04   DPD 31-60  Contacted_Portfolio   2369

============================================================
Estrutura final:
Total de linhas: 92
Faixas únicas: ['DPD 16-30' 'DPD 31-60' 'DPD 61-90' 'DPD 91-120']
Colunas: ['FAIXA', 'Indicador', datetime.date(2025, 12, 4)]
============================================================

Primeiras 30 linhas:
        FAIXA                                  Indicador  2025-12-04
0   DPD 16-30                  AHT_Excluding_Short_Calls        2110
1   DPD 16-30                              Active_Agents           4
2   DPD 16-30                         Assigned_Portfolio        1614
3   DPD 16-30                        Contacted_Portfolio        1423
4   DPD 16-30                        Debt_Not_Recognized           0
5   DPD 16-30                     Device_Reported_Stolen           0
6   DPD 16-30                Device_Warranty_Acess_issue           0
7   DPD 16-30                     Dont_Know_on_the_Phone           0
8   DPD 16-30                       Number_Of_Email_sent           0
9   DPD 16-30                         Number_Of_SMS_Sent        1251
10  DPD 16-30                          Number_Of_WA_Sent           0
11  DPD 16-30                       Payment_Already_Made           0
12  DPD 16-30                        Promises_to_Pay_PTP           0
13  DPD 16-30           Promises_to_Pay_per_Active_Agent           0
14  DPD 16-30                        Reachable_Portfolio           0
15  DPD 16-30                                  Total_AHT        2220
16  DPD 16-30                       Total_Answered_Calls         228
17  DPD 16-30      Total_Answered_Calls_Excl_Short_Calls         170
18  DPD 16-30                        Total_Call_Attempts        2810
19  DPD 16-30            Total_RPCs_Right_Party_Contacts           0
20  DPD 16-30                   Unique_Customers_Reached          58
21  DPD 16-30  Unique_Customers_Reached_Excl_Short_Calls          43
22  DPD 16-30                                Unique_RPCs           0
23  DPD 31-60                  AHT_Excluding_Short_Calls        3155
24  DPD 31-60                              Active_Agents           4
25  DPD 31-60                         Assigned_Portfolio        2680
26  DPD 31-60                        Contacted_Portfolio        2369
27  DPD 31-60                        Debt_Not_Recognized           0
28  DPD 31-60                     Device_Reported_Stolen           0
29  DPD 31-60                Device_Warranty_Acess_issue           0

         FAIXA                                  Indicador  2025-12-04
0    DPD 16-30                  AHT_Excluding_Short_Calls        2110
1    DPD 16-30                              Active_Agents           4
2    DPD 16-30                         Assigned_Portfolio        1614
3    DPD 16-30                        Contacted_Portfolio        1423
4    DPD 16-30                        Debt_Not_Recognized           0
..         ...                                        ...         ...
87  DPD 91-120                        Total_Call_Attempts        3293
88  DPD 91-120            Total_RPCs_Right_Party_Contacts           0
89  DPD 91-120                   Unique_Customers_Reached          68
90  DPD 91-120  Unique_Customers_Reached_Excl_Short_Calls          47
91  DPD 91-120                                Unique_RPCs           0

[92 rows x 3 columns]

In [76]:
import pandas as pd
from src.db_connection import get_connection

def df_contratos_payjoy():
    """
    Busca os contratos PayJoy com suas respectivas faixas (DPD_BUCKET)
    
    Returns:
        DataFrame com colunas: Assigned_Portfolio, FAIXA
    """
    # Cria a conexão
    conn_bd2 = get_connection("SERVER_BD2", "DATABASE_BD2")
    
    # Query SQL
    query = """
    SELECT
        Assigned_Portfolio
    ,   DPD_BUCKET as FAIXA
    FROM OPENQUERY([TRC-DC-BDM\BD],
    '
        SELECT 
            ltrim(rtrim(contrato_fin)) Assigned_Portfolio
        ,   DPD_BUCKET
        ,   cast(CALENDAR_DATE as date) dt_base 
        FROM AUX_PAYJOY_REMESSA 
        WHERE CALENDAR_DATE = (SELECT MAX(CALENDAR_DATE) FROM AUX_PAYJOY_REMESSA)
    '
    )
    """
    
    try:
        # Executa a query e retorna o DataFrame
        df = pd.read_sql(query, conn_bd2)
        
        print(f"Total de contratos: {len(df)}")
        print(f"Faixas disponíveis: {df['FAIXA'].unique()}")
        
        return df
        
    except Exception as e:
        print(f"Erro ao executar query: {e}")
        raise
    finally:
        conn_bd2.close()

# Executa a função
df_contratos = df_contratos_payjoy()
df_contratos

<>:15: SyntaxWarning: invalid escape sequence '\B'
<>:15: SyntaxWarning: invalid escape sequence '\B'
C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_38420\3698485219.py:15: SyntaxWarning: invalid escape sequence '\B'
  query = """
C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_38420\3698485219.py:33: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn_bd2)

Total de contratos: 8247
Faixas disponíveis: ['DPD 61-90' 'DPD 91-120' 'DPD 16-30' 'DPD 31-60']

     Assigned_Portfolio       FAIXA
0            54988427ID   DPD 61-90
1            54988428ID  DPD 91-120
2            54988429ID  DPD 91-120
3            54988430ID   DPD 16-30
4            54988431ID  DPD 91-120
...                 ...         ...
8242         54996669ID   DPD 31-60
8243         54996670ID   DPD 16-30
8244         54996671ID   DPD 31-60
8245         54996672ID   DPD 31-60
8246         54996673ID   DPD 16-30

[8247 rows x 2 columns]

In [78]:
import pandas as pd
import os
from glob import glob

def consolidar_mailings_payjoy(caminho_pasta=r"\\trc-dc-ad\Planejamento\00 - USUÁRIOS\0003_Daniel Kodama\PAYJOY\mailings payjoy"):
    """
    Consolida todos os arquivos CSV de mailings PayJoy em um único DataFrame
    
    Args:
        caminho_pasta: Caminho da pasta com os arquivos CSV
        
    Returns:
        DataFrame com colunas: CHAVE_POPUP, DATA
    """
    
    # Lista todos os arquivos CSV na pasta
    arquivos = glob(os.path.join(caminho_pasta, "*.csv"))
    
    if not arquivos:
        print(f"Nenhum arquivo CSV encontrado em: {caminho_pasta}")
        return pd.DataFrame()
    
    print(f"Encontrados {len(arquivos)} arquivos CSV")
    
    # Lista para armazenar os DataFrames
    lista_dfs = []
    
    for arquivo in arquivos:
        try:
            # Extrai o nome do arquivo sem o caminho
            nome_arquivo = os.path.basename(arquivo)
            
            # Remove a extensão .csv
            nome_sem_extensao = nome_arquivo.replace('.csv', '')
            
            # Pega os últimos 4 caracteres (ex: "03.12" ou "8/12")
            ultimos_4_chars = nome_sem_extensao[-4:]
            
            # Substitui ponto por barra para padronizar (ex: "03.12" -> "03/12")
            data_str = ultimos_4_chars.replace('.', '/')
            
            # Tenta ler com ponto e vírgula primeiro, se falhar tenta com vírgula
            try:
                df_temp = pd.read_csv(arquivo, usecols=['CHAVE_POPUP'], encoding='latin-1', sep=';')
            except:
                try:
                    df_temp = pd.read_csv(arquivo, usecols=['CHAVE_POPUP'], encoding='latin-1', sep=',')
                except:
                    df_temp = pd.read_csv(arquivo, usecols=['CHAVE_POPUP'], encoding='utf-8', sep=';')
            
            # Adiciona a coluna de data
            df_temp['DATA'] = data_str
            
            # Adiciona à lista
            lista_dfs.append(df_temp)
            
            print(f"✓ Processado: {nome_arquivo} - {len(df_temp)} registros - Data: {data_str}")
            
        except Exception as e:
            print(f"✗ Erro ao processar {nome_arquivo}: {e}")
            continue
    
    # Concatena todos os DataFrames
    if lista_dfs:
        df_consolidado = pd.concat(lista_dfs, ignore_index=True)
        
        print(f"\n{'='*60}")
        print(f"Total de registros consolidados: {len(df_consolidado)}")
        print(f"Datas únicas: {sorted(df_consolidado['DATA'].unique())}")
        print(f"Total de contratos únicos: {df_consolidado['CHAVE_POPUP'].nunique()}")
        print(f"{'='*60}")
        
        return df_consolidado
    else:
        print("Nenhum dado foi consolidado.")
        return pd.DataFrame()

# Executa a função
df_mailings = consolidar_mailings_payjoy()
df_mailings

Encontrados 15 arquivos CSV
✓ Processado: PAYJOY-ATIVO.01.12.csv - 6889 registros - Data: 1/12
✓ Processado: PAYJOY-ATIVO.02.12.csv - 6873 registros - Data: 2/12
✓ Processado: PAYJOY-ATIVO.03.12.csv - 6873 registros - Data: 3/12
✓ Processado: PAYJOY-ATIVO.18.11.csv - 7260 registros - Data: 8/11
✓ Processado: PAYJOY-ATIVO.19.11.csv - 7260 registros - Data: 9/11
✓ Processado: PAYJOY-ATIVO.21.11.csv - 7260 registros - Data: 1/11
✓ Processado: PAYJOY-ATIVO.24.11.csv - 7265 registros - Data: 4/11
✓ Processado: PAYJOY-ATIVO.25.11.csv - 7265 registros - Data: 5/11
✓ Processado: PAYJOY-ATIVO.26.11.csv - 6898 registros - Data: 6/11
✓ Processado: PAYJOY-ATIVO.27.11.csv - 6889 registros - Data: 7/11
✓ Processado: PAYJOY-ATIVO.28.11.csv - 6889 registros - Data: 8/11
✓ Processado: PAYJOY-ATIVO_03.12.csv - 8243 registros - Data: 3/12
✓ Processado: PAYJOY-ATIVO_04.12.csv - 8243 registros - Data: 4/12
✓ Processado: PAYJOY-ATIVO_05.12.csv - 8243 registros - Data: 5/12
✓ Processado: PAYJOY-ATIVO_08.12.csv - 8210 registros - Data: 8/12

============================================================
Total de registros consolidados: 110560
Datas únicas: ['1/11', '1/12', '2/12', '3/12', '4/11', '4/12', '5/11', '5/12', '6/11', '7/11', '8/11', '8/12', '9/11']
Total de contratos únicos: 15849
============================================================

       CHAVE_POPUP  DATA
0         DBBBMRNZ  1/12
1          DBBDKFD  1/12
2          DBBGSDM  1/12
3          DBBHDKF  1/12
4          DBBHNDN  1/12
...            ...   ...
110555  54996669ID  8/12
110556  54996670ID  8/12
110557  54996671ID  8/12
110558  54996672ID  8/12
110559  54996673ID  8/12

[110560 rows x 2 columns]

In [125]:
def consolidar_mailings_por_faixa(df_mailings, df_contratos, ordenar_datas=True, contratos_unicos=True):
    """
    Cruza os mailings com os contratos para obter faixas e gera tabela pivotada
    """
    
    # Cruzamento
    df_mailings_com_faixa = df_mailings.merge(
        df_contratos,
        left_on='CHAVE_POPUP',
        right_on='Assigned_Portfolio',
        how='left'
    )
    
    # Contagem
    if contratos_unicos:
        df_contagem = df_mailings_com_faixa.groupby(['FAIXA', 'DATA'])['CHAVE_POPUP'].nunique().reset_index()
    else:
        df_contagem = df_mailings_com_faixa.groupby(['FAIXA', 'DATA'])['CHAVE_POPUP'].count().reset_index()
    
    df_contagem.columns = ['FAIXA', 'DATA', 'CONTAGEM']
    
    # Pivota
    df_pivot = df_contagem.pivot(
        index='FAIXA',
        columns='DATA',
        values='CONTAGEM'
    ).fillna(0).astype(int)
    
    # Ordena datas se solicitado
    if ordenar_datas:
        colunas_ordenadas = sorted(
            df_pivot.columns, 
            key=lambda x: pd.to_datetime(x, format='%d/%m', errors='coerce')
        )
        df_pivot = df_pivot[colunas_ordenadas]
    
    # Reset index
    df_pivot = df_pivot.reset_index()
    
    return df_pivot

# Uso:
df_pivot = consolidar_mailings_por_faixa(df_mailings, df_contratos)
df_pivot

DATA       FAIXA  3/12  4/12  5/12  8/12
0      DPD 16-30  1613  1613  1613  1602
1      DPD 31-60  2678  2678  2678  2665
2      DPD 61-90  2083  2083  2083  2077
3     DPD 91-120  1869  1869  1869  1866

In [167]:
import pandas as pd

def substituir_zeros_com_pivot(df_transposto, df_pivot):
    """
    Substitui valores 0 do df_transposto pelos valores do df_pivot,
    respeitando FAIXA + data.
    
    Args:
        df_transposto: DataFrame com estrutura [FAIXA, Indicador, 2025-12-04, 2025-12-05, ...]
        df_pivot: DataFrame com estrutura [FAIXA, 3/12, 4/12, 5/12, ...]
    
    Returns:
        DataFrame atualizado
    """
    
    df_resultado = df_transposto.copy()
    
    # Pegar as colunas de data do df_transposto
    colunas_data = [col for col in df_transposto.columns if col not in ['FAIXA', 'Indicador']]
    
    # Para cada linha do df_pivot
    for _, row_pivot in df_pivot.iterrows():
        faixa = row_pivot["FAIXA"]
        
        # Para cada coluna de data no df_transposto
        for col_transposto in colunas_data:
            # Converter coluna do df_transposto para formato do df_pivot
            if isinstance(col_transposto, str) and '-' in col_transposto:
                partes = col_transposto.split('-')
                dia = partes[2].lstrip('0') or '0'
                mes = partes[1].lstrip('0') or '0'
                col_pivot_format = f"{dia}/{mes}"
            elif hasattr(col_transposto, 'day') and hasattr(col_transposto, 'month'):
                dia = str(col_transposto.day)
                mes = str(col_transposto.month)
                col_pivot_format = f"{dia}/{mes}"
            else:
                continue
            
            # Se essa coluna existe no df_pivot
            if col_pivot_format in df_pivot.columns:
                valor_pivot = row_pivot[col_pivot_format]
                
                # Substituir os zeros APENAS para o indicador Reachable_Portfolio
                mask = (
                    (df_resultado["FAIXA"] == faixa) & 
                    (df_resultado["Indicador"] == "Reachable_Portfolio") &
                    (df_resultado[col_transposto] == 0)
                )
                df_resultado.loc[mask, col_transposto] = valor_pivot
    
    return df_resultado


df_PAYJOY = substituir_zeros_com_pivot(df_final, df_pivot)
print("DataFrame atualizado:")
print(df_PAYJOY)

DataFrame atualizado:
         FAIXA                                  Indicador  2025-12-04
0    DPD 16-30                  AHT_Excluding_Short_Calls        2110
1    DPD 16-30                              Active_Agents           4
2    DPD 16-30                         Assigned_Portfolio        1614
3    DPD 16-30                        Contacted_Portfolio        1423
4    DPD 16-30                        Debt_Not_Recognized           0
..         ...                                        ...         ...
87  DPD 91-120                        Total_Call_Attempts        3293
88  DPD 91-120            Total_RPCs_Right_Party_Contacts           0
89  DPD 91-120                   Unique_Customers_Reached          68
90  DPD 91-120  Unique_Customers_Reached_Excl_Short_Calls          47
91  DPD 91-120                                Unique_RPCs           0

[92 rows x 3 columns]

In [168]:
import pandas as pd

# Exemplo: supondo que a coluna que guarda o nome do indicador se chama "Indicador"
df_filtrado = df_PAYJOY[df_PAYJOY["Indicador"] == "Reachable_Portfolio"]

print(df_filtrado.head())

         FAIXA            Indicador  2025-12-04
14   DPD 16-30  Reachable_Portfolio        1613
37   DPD 31-60  Reachable_Portfolio        2678
60   DPD 61-90  Reachable_Portfolio        2083
83  DPD 91-120  Reachable_Portfolio        1869