In [ ]:
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> GERAR DADOS

# import importlib
# importlib.reload(queries)
from src.data_wrangling_mailingHist import tratar_base_mailing_hist
from src.db_connection import get_connection
from Projects.Getnet.src.queries import get_query_discagens, get_query_cad_devf, get_query_mailing_hist, get_query_discagens_trestto, get_query_tabulacao_aciona, get_query_base_acionamentos, get_query_dw_calendario, get_query_pagamentos, get_query_acordos
import pandas as pd

# DADOS SRC

def data_loader(conn_trc, conn_bd2, conn_src):

    df_discagens_expert = pd.read_sql(
        get_query_discagens('2025-12-01', '2025-12-17'), 
        conn_src
    )
    df_cad_devf = pd.read_sql(
        get_query_cad_devf(), 
        conn_src
    )
    df_tab_acionamentos = pd.read_sql(
        get_query_base_acionamentos('2025-12-01', '2025-12-17'), 
        conn_src
    )

    # DADOS BD2/PLANEJAMENTO
    df_maling_hist = pd.read_sql(
        get_query_mailing_hist('2025-12-01', '2025-12-17'), 
        conn_bd2
    )
    df_maling_hist = tratar_base_mailing_hist(df_maling_hist, df_cad_devf)

    df_dw_calendario = pd.read_sql(
        get_query_dw_calendario(), 
        conn_bd2
    )
    df_tabulacao_aciona = pd.read_sql(
        get_query_tabulacao_aciona(), 
        conn_bd2
    )
    df_pagamentos = pd.read_sql(
        get_query_pagamentos('2025-12-01', '2025-12-17'), 
        conn_src
    )
    df_acordos = pd.read_sql(
        get_query_acordos('2025-12-01', '2025-12-17'), 
        conn_src
    )

    # DADOS BD2/TRC
    
    df_discagens_trestto = pd.read_sql(
        get_query_discagens_trestto('2025-12-01', '2025-12-17'), 
        conn_trc
    )
    
    return df_discagens_expert, df_cad_devf, df_tab_acionamentos, df_maling_hist, df_dw_calendario, df_tabulacao_aciona, df_pagamentos, df_acordos, df_discagens_trestto

def get_connection():
    conn_trc = get_connection("SERVER_BD2", "DATABASE_TRC")
    conn_bd2 = get_connection("SERVER_BD2", "DATABASE_BD2")
    conn_src = get_connection("SERVER_SRC", "DATABASE_SRC")

    df_discagens_expert, df_cad_devf, df_tab_acionamentos, df_maling_hist, df_dw_calendario, df_tabulacao_aciona, df_pagamentos, df_acordos, df_discagens_trestto = data_loader(conn_trc, conn_bd2, conn_src)

    return df_discagens_expert, df_cad_devf, df_tab_acionamentos, df_maling_hist, df_dw_calendario, df_tabulacao_aciona, df_pagamentos, df_acordos, df_discagens_trestto

In [ ]:
import importlib
from src import(queries, data_wrangling_discagens_trestto, data_wrangling_mailingHist, data_wrangling_acionamentos, data_wrangling_discagens_expert, data_wrangling_pagamentos, utils, pipeline_funil, data_loader, csv_cleaning)
importlib.reload(utils)
importlib.reload(data_loader)
importlib.reload(pipeline_funil)
importlib.reload(data_wrangling_discagens_trestto)
importlib.reload(data_wrangling_mailingHist)
importlib.reload(data_wrangling_acionamentos)
importlib.reload(data_wrangling_discagens_expert)
importlib.reload(data_wrangling_pagamentos)
importlib.reload(queries)
importlib.reload(csv_cleaning)

# 1. Carregar e ativar autoreload
# %load_ext autoreload
# %autoreload 2

# # 2. Fazer suas importações normalmente
# from src import (
#     queries,
#     data_wrangling_discagens_trestto,
#     data_wrangling_mailingHist,
#     data_wrangling_acionamentos,
#     data_wrangling_discagens_expert,
#     data_wrangling_pagamentos,
#     utils,
#     pipeline_funil,
#     data_loader,
#     csv_cleaning
# )

In [46]:
# from src.data_wrangling_mailingHist import tratar_base_mailing_hist
# from src.data_wrangling_discagens_expert import acionamentos_expert
from src.db_connection import get_connection
from src.queries import get_query_discagens, get_query_cad_devf, get_query_mailing_hist, get_query_discagens_trestto, get_query_tabulacao_aciona, get_query_base_acionamentos, get_query_dw_calendario, get_query_pagamentos, get_query_acordos
import pandas as pd
conn_trc = get_connection("SERVER_BD2", "DATABASE_TRC")
conn_bd2 = get_connection("SERVER_BD2", "DATABASE_BD2")
conn_src = get_connection("SERVER_SRC", "DATABASE_SRC")
# df_discagens_expert = pd.read_sql(
#     get_query_discagens('2025-11-01', '2025-11-17'), 
#     conn_src
# )
# df_cad_devf = pd.read_sql(
#     get_query_cad_devf(), 
#     conn_src
# )
# df_maling_hist = pd.read_sql(
#     get_query_mailing_hist('2025-11-01', '2025-11-17'), 
#     conn_bd2
# )
# df_maling_hist = tratar_base_mailing_hist(df_maling_hist, df_cad_devf)
df_dw_calendario = pd.read_sql(
    get_query_dw_calendario('2025-11-01', '2025-11-30'), 
    conn_bd2
)
df_dw_calendario
#df_acionamentos_expert, df_analitico_expert, df_enriquecido_discagens_expert_semFaixa, df_humano_tabulados_como_robo, df_dicagens_operacaoOutros = acionamentos_expert(df_discagens_expert, df_dw_calendario, df_maling_hist)
#df_acionamentos_expert

C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_38420\2890686504.py:22: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_dw_calendario = pd.read_sql(

,dt_data,dt_ano,dt_mes,dt_dia,nr_dia_semana,nr_dia_ano,fl_dia_util,nr_dia_util,quartil,mes_abreviado
0,2025-11-03,2025,11,3,2,307,1,1,Q4,Nov
1,2025-11-04,2025,11,4,3,308,1,2,Q4,Nov
2,2025-11-05,2025,11,5,4,309,1,3,Q4,Nov
3,2025-11-06,2025,11,6,5,310,1,4,Q4,Nov
4,2025-11-07,2025,11,7,6,311,1,5,Q4,Nov
5,2025-11-10,2025,11,10,2,314,1,6,Q4,Nov
6,2025-11-11,2025,11,11,3,315,1,7,Q4,Nov
7,2025-11-12,2025,11,12,4,316,1,8,Q4,Nov
8,2025-11-13,2025,11,13,5,317,1,9,Q4,Nov
9,2025-11-14,2025,11,14,6,318,1,10,Q4,Nov
10,2025-11-17,2025,11,17,2,321,1,11,Q4,Nov
11,2025-11-18,2025,11,18,3,322,1,12,Q4,Nov
12,2025-11-19,2025,11,19,4,323,1,13,Q4,Nov
13,2025-11-21,2025,11,21,6,325,1,14,Q4,Nov
14,2025-11-24,2025,11,24,2,328,1,15,Q4,Nov
15,2025-11-25,2025,11,25,3,329,1,16,Q4,Nov
16,2025-11-26,2025,11,26,4,330,1,17,Q4,Nov
17,2025-11-27,2025,11,27,5,331,1,18,Q4,Nov
18,2025-11-28,2025,11,28,6,332,1,19,Q4,Nov

In [6]:
#from src.data_wrangling_mailingHist import tratar_base_mailing_hist, gerar_acumulado_mailing_hist
#from src.data_wrangling_discagens_expert import acionamentos_expert
from src.db_connection import get_connection
from src.queries import get_query_discagens, get_query_cad_devf, get_query_mailing_hist, get_query_discagens_trestto, get_query_tabulacao_aciona, get_query_base_acionamentos, get_query_dw_calendario, get_query_pagamentos, get_query_acordos
import pandas as pd
conn_trc = get_connection("SERVER_BD2", "DATABASE_TRC")
conn_bd2 = get_connection("SERVER_BD2", "DATABASE_BD2")
conn_src = get_connection("SERVER_SRC", "DATABASE_SRC")

# df_cad_devf = pd.read_sql(
#     get_query_cad_devf(), 
#     conn_src
# )
# df_maling_hist = pd.read_sql(
#     get_query_mailing_hist('2025-11-01', '2025-11-17'), 
#     conn_bd2
# )
# df_maling_hist = tratar_base_mailing_hist(df_maling_hist, df_cad_devf)
df_dw_calendario = pd.read_sql(
    get_query_dw_calendario('2025-11-01', '2025-11-17'), 
    conn_bd2
)
# df_maling_acumulado = gerar_acumulado_mailing_hist(df_maling_hist, df_dw_calendario)
# df_maling_acumulado
df_dw_calendario

C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_38420\1509880068.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_dw_calendario = pd.read_sql(

,dt_data,dt_ano,dt_mes,dt_dia,nr_dia_semana,nr_dia_ano,fl_dia_util,nr_dia_util,quartil,mes_abreviado
0,2025-11-03,2025,11,3,2,307,1,1,Q4,Nov
1,2025-11-04,2025,11,4,3,308,1,2,Q4,Nov
2,2025-11-05,2025,11,5,4,309,1,3,Q4,Nov
3,2025-11-06,2025,11,6,5,310,1,4,Q4,Nov
4,2025-11-07,2025,11,7,6,311,1,5,Q4,Nov
5,2025-11-10,2025,11,10,2,314,1,6,Q4,Nov
6,2025-11-11,2025,11,11,3,315,1,7,Q4,Nov
7,2025-11-12,2025,11,12,4,316,1,8,Q4,Nov
8,2025-11-13,2025,11,13,5,317,1,9,Q4,Nov
9,2025-11-14,2025,11,14,6,318,1,10,Q4,Nov
10,2025-11-17,2025,11,17,2,321,1,11,Q4,Nov

In [ ]:
from src.db_connection import get_connection
from src.queries import get_query_discagens, get_query_cad_devf, get_query_mailing_hist, get_query_discagens_trestto, get_query_tabulacao_aciona, get_query_base_acionamentos, get_query_dw_calendario, get_query_pagamentos, get_query_acordos
#from src.data_wrangling_discagens_trestto import enriquecer_discagens_trestto, acionamentos_fxAtraso_origem_trestto
from src.data_wrangling_acionamentos import tratar_acionamentos_tabulacao, confere_tabulacao_acionamentos, enriquecer_acionamentos, acionamentos_fxAtraso_origem_humano
from src.data_wrangling_discagens_trestto import acionamentos_trestto
from src.data_wrangling_mailingHist import tratar_base_mailing_hist
from src.utils import transformar_funil_formato_long
import pandas as pd
# conn_trc = get_connection("SERVER_BD2", "DATABASE_TRC")
# conn_src = get_connection("SERVER_SRC", "DATABASE_SRC")
# conn_bd2 = get_connection("SERVER_BD2", "DATABASE_BD2")
# df_discagens_trestto = pd.read_sql(
#     get_query_discagens_trestto('2025-11-01', '2025-11-20'), 
#     conn_trc
# )
# df_cad_devf = pd.read_sql(
#     get_query_cad_devf(), 
#     conn_src
# )
# df_maling_hist = pd.read_sql(
#     get_query_mailing_hist('2025-11-01', '2025-11-25'), 
#     conn_bd2
# )
# df_maling_hist = tratar_base_mailing_hist(df_maling_hist, df_cad_devf)
# df_tabulacao_aciona = pd.read_sql(
#     get_query_tabulacao_aciona(), 
#     conn_bd2
# )
# df_tab_acionamentos = pd.read_sql(
#     get_query_base_acionamentos('2025-11-01', '2025-11-25'), 
#     conn_src
# )
# df_dw_calendario = pd.read_sql(
#     get_query_dw_calendario('2025-11-01', '2025-11-25'), 
#     conn_bd2
# )
df_acionamentos_trestto, df_analitico_trestto, df_enriquecido_discagens_trestto_semFaixa = acionamentos_trestto(df_discagens_trestto, df_maling_hist, df_dw_calendario)
df_acionamentos_trestto

In [56]:
import os
# #df_conflitos_score
#df_acionamentos_enriquecido_limpo, df_acion_semFaixa, df_acion_semDescricao, df_acion_semOrigem 
df_PAYJOY.to_csv('df_PAYJOY.csv', sep=';', index=False, decimal=',', encoding='utf-8-sig')
os.startfile('df_PAYJOY.csv')  # abre com o programa padrão

In [ ]:
from src.data_loader import get_date_range_from_csv

var = get_date_range_from_csv()
var

In [ ]:
# INTERSEÇÃO DE CPFS DISCADOS COM E SEM FAIXA DE ATRASO

from src.data_wrangling_discagens_trestto import tratar_discagens_trestto, enriquecer_discagens_trestto, acionamentos_esforco_trestto, interseção_cpfs_discados_trestto

mesagem_resultado = interseção_cpfs_discados_trestto(df_enriquecido_discagens_trestto_limpo, df_enriquecido_discagens_trestto_semFaixa)
mesagem_resultado

In [57]:

caminho_csv = r"\\trc-dc-ad\Planejamento\MIS\CARTEIRAS\WILLBANK\Automations\base_tempos.csv"
def obter_ultima_data_arquivo(caminho_csv):
    """
    Lê o arquivo CSV e retorna a última data de atendimento.
    """
    try:
        # Ler CSV
        df = pd.read_csv(caminho_csv, encoding='utf-8-sig', sep=';')
        
        # Normalizar nomes de colunas (remover espaços)
        df.columns = df.columns.str.strip()
        
        if 'data_insert' not in df.columns:
            raise ValueError("Coluna 'data_insert' não encontrada no arquivo")
        
        # Remover espaços e caracteres estranhos da coluna
        df['data_insert'] = df['data_insert'].astype(str).str.strip()
        
        # Converter para datetime
        df['data_insert'] = pd.to_datetime(
            df['data_insert'].str.strip(),
            format='%d/%m/%Y',   # força o formato brasileiro
            errors='coerce'
        )

        print(df['data_insert'].sort_values().tail(10))
        
        # Verificar se alguma data foi convertida
        if df['data_insert'].isna().all():
            raise ValueError("Nenhuma data válida encontrada. Verifique o formato no CSV.")
        
        # Obter a última data válida
        ultima_data = df['data_insert'].max()
        
        print(f"Última data encontrada no arquivo: {ultima_data.strftime('%d/%m/%Y')}")
        return ultima_data
    
    except Exception as e:
        print(f"Erro ao ler arquivo: {str(e)}")
        import traceback
        traceback.print_exc()
        raise

data = obter_ultima_data_arquivo(caminho_csv)
data

795   NaT
796   NaT
797   NaT
798   NaT
799   NaT
800   NaT
801   NaT
802   NaT
803   NaT
804   NaT
Name: data_insert, dtype: datetime64[ns]
Última data encontrada no arquivo: 03/12/2025

Timestamp('2025-12-03 00:00:00')

In [58]:
caminho_csv = r"\\trc-dc-ad\Planejamento\MIS\CARTEIRAS\WILLBANK\Automations\base_tempos.csv"
df = pd.read_csv(caminho_csv, encoding='utf-8-sig', sep=';')
        
# Normalizar nomes de colunas (remover espaços)
df.columns = df.columns.str.strip()

if 'data_insert' not in df.columns: 
    raise ValueError("Coluna 'data_insert' não encontrada no arquivo")

# Remover espaços e caracteres estranhos da coluna
df['data_insert'] = df['data_insert'].astype(str).str.strip()

# Converter para datetime
df['data_insert'] = pd.to_datetime(
    df['data_insert'].str.strip(),
    format='%d/%m/%Y',   # força o formato brasileiro
    errors='coerce'
)

print(df['data_insert'].sort_values().tail(10))
print(df['data_insert'].unique())
print(df.loc[620:630, 'data_insert'])

795   NaT
796   NaT
797   NaT
798   NaT
799   NaT
800   NaT
801   NaT
802   NaT
803   NaT
804   NaT
Name: data_insert, dtype: datetime64[ns]
<DatetimeArray>
['2025-11-01 00:00:00', '2025-11-03 00:00:00', '2025-11-04 00:00:00',
 '2025-11-05 00:00:00', '2025-11-06 00:00:00', '2025-11-07 00:00:00',
 '2025-11-08 00:00:00', '2025-11-10 00:00:00', '2025-11-11 00:00:00',
 '2025-11-12 00:00:00', '2025-11-13 00:00:00', '2025-11-14 00:00:00',
 '2025-11-17 00:00:00', '2025-11-18 00:00:00', '2025-11-19 00:00:00',
 '2025-11-21 00:00:00', '2025-11-22 00:00:00', '2025-11-24 00:00:00',
 '2025-11-25 00:00:00', '2025-11-26 00:00:00', '2025-11-27 00:00:00',
 '2025-11-28 00:00:00', '2025-11-29 00:00:00', '2025-12-01 00:00:00',
 '2025-12-02 00:00:00', '2025-12-03 00:00:00',                 'NaT']
Length: 27, dtype: datetime64[ns]
620   2025-11-27
621   2025-11-27
622   2025-11-27
623   2025-11-27
624   2025-11-27
625   2025-11-27
626   2025-11-27
627   2025-11-27
628   2025-11-27
629   2025-11-27
630   2025-11-27
Name: data_insert, dtype: datetime64[ns]

In [27]:
# ...existing code...
caminho_csv = r"\\trc-dc-ad\Planejamento\MIS\CARTEIRAS\WILLBANK\Automations\base_tempos.csv"
def obter_ultima_data_arquivo(caminho_csv):
    """
    Lê o CSV e retorna a MAIOR data encontrada na coluna de data.
    Detecta 'data_insert' ou 'data_atendimento' ou usa a primeira coluna.
    Remove linhas de header acidental e valores inválidos antes de calcular o max.
    """
    try:
        # Ler tudo como string para evitar inferências estranhas
        df = pd.read_csv(caminho_csv, encoding='utf-8-sig', sep=';', dtype=str, keep_default_na=False)
        df.columns = df.columns.str.strip()
        if df.shape[0] == 0:
            raise ValueError("Arquivo vazio")

        # escolher coluna de data: preferir data_insert, depois data_atendimento, senão primeira coluna
        if 'data_insert' in df.columns:
            date_col = 'data_insert'
        elif 'data_atendimento' in df.columns:
            date_col = 'data_atendimento'
        else:
            date_col = df.columns[0]

        s = df[date_col].astype(str).str.strip()

        # remover linhas que sejam exatamente o nome da coluna (header inserido) ou vazias
        mask_header_like = s.str.lower() == date_col.lower()
        mask_empty = s == '' 
        s_clean = s[~(mask_header_like | mask_empty)].copy()

        # converter com heurística (dayfirst True para formatos DD/MM/YYYY) e inferência
        s_dt = pd.to_datetime(s_clean, dayfirst=True, infer_datetime_format=True, errors='coerce')

        # relatório mínimo (útil para debug)
        n_total = len(s)
        n_valid = s_dt.notna().sum()
        n_invalid = n_total - n_valid
        print(f"Coluna detectada: '{date_col}' — total:{n_total} válidas:{n_valid} inválidas:{n_invalid}")

        if s_dt.notna().sum() == 0:
            raise ValueError("Nenhuma data válida encontrada após limpeza. Verifique formatos ou linhas de header no CSV.")

        ultima_data = s_dt.max()
        print(f"Última data encontrada no arquivo: {ultima_data.strftime('%d/%m/%Y')}")
        return ultima_data

    except FileNotFoundError:
        print(f"Arquivo não encontrado: {caminho_csv}")
        raise
    except Exception as e:
        print(f"Erro ao obter última data: {e}")
        import traceback
        traceback.print_exc()
        raise

# ...existing code...

def obter_ultima_data_arquivo(caminho_csv):
    """
    Lê o CSV e retorna a MAIOR data encontrada na coluna de data.
    - detecta 'data_insert' ou 'data_atendimento' ou usa a primeira coluna
    - lê tudo como string, limpa ruídos (quotes, prefixes tipo b'...', headers inseridos),
      tenta parse em vários formatos e retorna o max válido.
    """
    import re

    try:
        # Ler como string para evitar coerções estranhas
        df = pd.read_csv(caminho_csv, encoding='utf-8-sig', sep=';', dtype=str, keep_default_na=False)
        df.columns = df.columns.str.strip()

        if df.shape[0] == 0:
            raise ValueError("Arquivo vazio")

        # escolher coluna de data
        if 'data_insert' in df.columns:
            col = 'data_insert'
        elif 'data_atendimento' in df.columns:
            col = 'data_atendimento'
        else:
            col = df.columns[0]

        s = df[col].astype(str).str.strip()

        # remover linhas que são header inserido ou claramente vazias
        mask_header = s.str.lower() == col.lower()
        mask_empty = s == '' 
        s = s[~(mask_header | mask_empty)].copy()

        if s.empty:
            raise ValueError("Nenhum valor não-vazio encontrado na coluna de datas")

        # limpeza básica: remover quotes, prefixes b'...', controle de caracteres estranhos
        s = s.str.replace(r"^b['\"]", "", regex=True).str.replace(r"['\"]$", "", regex=True)
        s = s.str.replace(r"[^\d\-/:\s]", "", regex=True).str.strip()

        # Tentar converter diretamente (vários formatos suportados)
        dt = pd.to_datetime(s, dayfirst=True, infer_datetime_format=True, errors='coerce')

        # Se muitos NaT, tentar extrair padrões comuns (YYYY-MM-DD HH:MM:SS ou DD/MM/YYYY)
        if dt.isna().sum() > 0:
            def extract_best(x):
                if pd.isna(x):
                    return x
                txt = str(x)
                # padrões possíveis
                m = re.search(r"(\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2})", txt)
                if m:
                    return m.group(1)
                m = re.search(r"(\d{4}-\d{2}-\d{2})", txt)
                if m:
                    return m.group(1)
                m = re.search(r"(\d{2}/\d{2}/\d{4})", txt)
                if m:
                    return m.group(1)
                return txt

            s2 = s.map(extract_best)
            dt2 = pd.to_datetime(s2, dayfirst=True, infer_datetime_format=True, errors='coerce')
            # combinar: preferir dt2 quando dt for NaT
            dt = dt.fillna(dt2)

        n_total = len(s)
        n_valid = dt.notna().sum()
        n_invalid = n_total - n_valid
        print(f"Coluna detectada: '{col}' — total:{n_total} válidas:{n_valid} inválidas:{n_invalid}")

        if n_valid == 0:
            raise ValueError("Nenhuma data válida encontrada após limpeza. Verifique o conteúdo do CSV.")

        ultima = dt.max()
        print(f"Última data encontrada no arquivo: {ultima.strftime('%d/%m/%Y')}")
        return ultima

    except FileNotFoundError:
        print(f"Arquivo não encontrado: {caminho_csv}")
        raise
    except Exception as e:
        print(f"Erro ao obter última data: {e}")
        import traceback
        traceback.print_exc()
        raise

# ...existing code...

def obter_ultima_data_arquivo(caminho_csv):
    """
    Lê o arquivo CSV e retorna a última data de atendimento.
    
    Parâmetros:
    -----------
    caminho_csv : str
        Caminho do arquivo CSV
    
    Retorna:
    --------
    datetime : Última data encontrada no arquivo
    """
    try:
        # Ler CSV com delimitador ponto e vírgula
        df = pd.read_csv(caminho_csv, encoding='utf-8-sig', sep=';')
        
        # Verificar se a coluna existe
        print(f"Colunas encontradas no arquivo ({len(df.columns)} colunas):")
        print(list(df.columns)[:10])  # Mostrar apenas as 10 primeiras
        
        if 'data_atendimento' not in df.columns:
            raise ValueError("Coluna 'data_atendimento' não encontrada no arquivo")
        
        # Mostrar exemplo de como a data está no arquivo
        print(f"Exemplo de data no arquivo: {df['data_atendimento'].iloc[0]}")
        
        # Tentar converter para datetime com dayfirst=True (formato brasileiro)
        df['data_atendimento'] = pd.to_datetime(df['data_atendimento'], dayfirst=True, errors='coerce')
        
        # Verificar se conseguiu converter
        if df['data_atendimento'].isna().all():
            raise ValueError("Não foi possível converter nenhuma data. Verifique o formato das datas no arquivo.")
        
        # Obter a última data
        ultima_data = df['data_atendimento'].max()
        
        # Verificar se a última data é válida
        if pd.isna(ultima_data):
            raise ValueError("Última data é inválida (NaT)")
        
        print(f"Última data encontrada no arquivo: {ultima_data.strftime('%d/%m/%Y')}")
        
        return ultima_data
        
    except Exception as e:
        print(f"Erro ao ler arquivo: {str(e)}")
        import traceback
        traceback.print_exc()
        raise

ultima_data = obter_ultima_data_arquivo(caminho_csv)
ultima_data
# ...existing code...

Colunas encontradas no arquivo (34 colunas):
['data_insert', 'hora_insert', 'id_agente', 'nome_agente', 'cpf_agente', 'nome_supervisor', 'coluna_fixa', 'data_atendimento', 'tempo_logado', 'hora_login']
Exemplo de data no arquivo: 01/11/2025
Última data encontrada no arquivo: 26/11/2025

Timestamp('2025-11-26 00:00:00')

In [128]:
import pandas as pd
from dotenv import load_dotenv
from src.db_connection import get_connection

conn_bd2 = get_connection("SERVER_BD2", "DATABASE_BD2")
sql_file = r"\\trc-dc-ad\Planejamento\MIS\CARTEIRAS\PayJoy\Daily_PayJoy.sql"

def df_consulta(conn_bd2, sql_file):
    # Lê o conteúdo da query
    with open(sql_file, "r", encoding="utf-8") as f:
        query = f.read()

    cursor = conn_bd2.cursor()
    
    try:
        # Executa a query completa
        cursor.execute(query)
        
        # Percorre todos os resultados até encontrar um com dados
        columns = None
        data = None
        
        # Tenta buscar o primeiro resultado
        if cursor.description:
            columns = [column[0] for column in cursor.description]
            data = cursor.fetchall()
        
        # Avança pelos resultados até encontrar o último com dados
        while cursor.nextset():
            if cursor.description:
                columns = [column[0] for column in cursor.description]
                data = cursor.fetchall()
        
        # Verifica se encontrou dados
        if columns is None or data is None:
            raise ValueError("Nenhum resultado encontrado na query")
        
        # Cria o DataFrame
        df = pd.DataFrame.from_records(data, columns=columns)
        
        return df
        
    except Exception as e:
        print(f"Erro ao executar query: {e}")
        raise
    finally:
        cursor.close()

# Executa a consulta
df_consulta_df = df_consulta(conn_bd2, sql_file)

# Verifica quantas datas únicas existem
datas_unicas = df_consulta_df['DATA'].unique()
print(f"Datas encontradas: {datas_unicas}")
print(f"Total de datas: {len(datas_unicas)}")

# Define automaticamente as colunas de indicadores
# Todas as colunas EXCETO 'DATA' e 'FAIXA'
colunas_todas = df_consulta_df.columns.tolist()
colunas_id = ['DATA', 'FAIXA']  # Colunas identificadoras
value_columns = [col for col in colunas_todas if col not in colunas_id]

print(f"\nColunas identificadoras: {colunas_id}")
print(f"Total de indicadores encontrados: {len(value_columns)}")

# Faz o unpivot (melt) mantendo DATA e FAIXA como identificadores
df_transposto = df_consulta_df.melt(
    id_vars=['DATA', 'FAIXA'],
    value_vars=value_columns,
    var_name='Indicador',
    value_name='Valor'
)

print(f"\nDataFrame após melt:")
print(df_transposto.head(10))

# Pivota para colocar as datas como colunas
df_final = df_transposto.pivot_table(
    index=['FAIXA', 'Indicador'],
    columns='DATA',
    values='Valor',
    aggfunc='first'  # Usa o primeiro valor caso haja duplicatas
).reset_index()

# Remove o nome do índice das colunas (fica mais limpo)
df_final.columns.name = None

# Ordena por FAIXA e Indicador
df_final = df_final.sort_values(['FAIXA', 'Indicador']).reset_index(drop=True)

# Visualiza o resultado
print(f"\n{'='*60}")
print(f"Estrutura final:")
print(f"Total de linhas: {len(df_final)}")
print(f"Faixas únicas: {df_final['FAIXA'].unique()}")
print(f"Colunas: {df_final.columns.tolist()}")
print(f"{'='*60}")
print("\nPrimeiras 30 linhas:")
print(df_final.head(30))

df_final

Datas encontradas: [datetime.date(2025, 12, 4)]
Total de datas: 1

Colunas identificadoras: ['DATA', 'FAIXA']
Total de indicadores encontrados: 23

DataFrame após melt:
         DATA       FAIXA            Indicador  Valor
0  2025-12-04   DPD 16-30   Assigned_Portfolio   1614
1  2025-12-04   DPD 31-60   Assigned_Portfolio   2680
2  2025-12-04   DPD 61-90   Assigned_Portfolio   2084
3  2025-12-04  DPD 91-120   Assigned_Portfolio   1869
4  2025-12-04   DPD 16-30  Reachable_Portfolio      0
5  2025-12-04   DPD 31-60  Reachable_Portfolio      0
6  2025-12-04   DPD 61-90  Reachable_Portfolio      0
7  2025-12-04  DPD 91-120  Reachable_Portfolio      0
8  2025-12-04   DPD 16-30  Contacted_Portfolio   1423
9  2025-12-04   DPD 31-60  Contacted_Portfolio   2369

============================================================
Estrutura final:
Total de linhas: 92
Faixas únicas: ['DPD 16-30' 'DPD 31-60' 'DPD 61-90' 'DPD 91-120']
Colunas: ['FAIXA', 'Indicador', datetime.date(2025, 12, 4)]
============================================================

Primeiras 30 linhas:
        FAIXA                                  Indicador  2025-12-04
0   DPD 16-30                  AHT_Excluding_Short_Calls        2110
1   DPD 16-30                              Active_Agents           4
2   DPD 16-30                         Assigned_Portfolio        1614
3   DPD 16-30                        Contacted_Portfolio        1423
4   DPD 16-30                        Debt_Not_Recognized           0
5   DPD 16-30                     Device_Reported_Stolen           0
6   DPD 16-30                Device_Warranty_Acess_issue           0
7   DPD 16-30                     Dont_Know_on_the_Phone           0
8   DPD 16-30                       Number_Of_Email_sent           0
9   DPD 16-30                         Number_Of_SMS_Sent        1251
10  DPD 16-30                          Number_Of_WA_Sent           0
11  DPD 16-30                       Payment_Already_Made           0
12  DPD 16-30                        Promises_to_Pay_PTP           0
13  DPD 16-30           Promises_to_Pay_per_Active_Agent           0
14  DPD 16-30                        Reachable_Portfolio           0
15  DPD 16-30                                  Total_AHT        2220
16  DPD 16-30                       Total_Answered_Calls         228
17  DPD 16-30      Total_Answered_Calls_Excl_Short_Calls         170
18  DPD 16-30                        Total_Call_Attempts        2810
19  DPD 16-30            Total_RPCs_Right_Party_Contacts           0
20  DPD 16-30                   Unique_Customers_Reached          58
21  DPD 16-30  Unique_Customers_Reached_Excl_Short_Calls          43
22  DPD 16-30                                Unique_RPCs           0
23  DPD 31-60                  AHT_Excluding_Short_Calls        3155
24  DPD 31-60                              Active_Agents           4
25  DPD 31-60                         Assigned_Portfolio        2680
26  DPD 31-60                        Contacted_Portfolio        2369
27  DPD 31-60                        Debt_Not_Recognized           0
28  DPD 31-60                     Device_Reported_Stolen           0
29  DPD 31-60                Device_Warranty_Acess_issue           0

         FAIXA                                  Indicador  2025-12-04
0    DPD 16-30                  AHT_Excluding_Short_Calls        2110
1    DPD 16-30                              Active_Agents           4
2    DPD 16-30                         Assigned_Portfolio        1614
3    DPD 16-30                        Contacted_Portfolio        1423
4    DPD 16-30                        Debt_Not_Recognized           0
..         ...                                        ...         ...
87  DPD 91-120                        Total_Call_Attempts        3293
88  DPD 91-120            Total_RPCs_Right_Party_Contacts           0
89  DPD 91-120                   Unique_Customers_Reached          68
90  DPD 91-120  Unique_Customers_Reached_Excl_Short_Calls          47
91  DPD 91-120                                Unique_RPCs           0

[92 rows x 3 columns]

In [47]:
import pandas as pd
from dotenv import load_dotenv
from src.db_connection import get_connection
from datetime import datetime, timedelta
import os
import sys
import re

conn_bd2 = get_connection("SERVER_BD2", "DATABASE_BD2")
sql_file = r"\\trc-dc-ad\Planejamento\MIS\CARTEIRAS\PayJoy\Daily_PayJoy_prod.sql"
xlsx_file = r"\\trc-dc-ad\Planejamento\MIS\CARTEIRAS\PayJoy\base_PAYJOY.xlsx"

def identificar_maior_data_xlsx(xlsx_path):
    """
    Identifica a maior data presente nas colunas do arquivo Excel.
    Encerra a execução se o arquivo não existir.
    """
    if not os.path.exists(xlsx_path):
        print(f"\n{'='*80}")
        print(f"ERRO CRÍTICO: Arquivo não encontrado!")
        print(f"Caminho: {xlsx_path}")
        print(f"{'='*80}")
        print("\nEncerrando execução...")
        sys.exit(1)
    
    try:
        df_temp = pd.read_excel(xlsx_path, nrows=5)
        print(f"Arquivo Excel lido com sucesso!")
        
        colunas = df_temp.columns.tolist()
        print(f"\nColunas encontradas no arquivo: {colunas}")
        
        ultima_data = None
        
        for col in reversed(colunas):
            if col in ['FAIXA', 'Indicador']:
                continue
            
            try:
                if isinstance(col, (pd.Timestamp, datetime)):
                    if isinstance(col, pd.Timestamp):
                        ultima_data = col.to_pydatetime()
                    else:
                        ultima_data = col
                    print(f"\nMaior data encontrada: {ultima_data.strftime('%Y-%m-%d')} (coluna já era datetime)")
                    return ultima_data
                
                col_limpo = str(col).strip()
                
                for formato in ['%Y-%m-%d', '%d/%m/%Y', '%Y/%m/%d', '%d-%m-%Y']:
                    try:
                        data = datetime.strptime(col_limpo, formato)
                        ultima_data = data
                        print(f"\nMaior data encontrada: {ultima_data.strftime('%Y-%m-%d')} (coluna: '{col}')")
                        return ultima_data
                    except:
                        continue
            except Exception as e:
                continue
        
        if ultima_data is None:
            print("\n" + "="*80)
            print("ERRO: Nenhuma data válida encontrada nas colunas do arquivo!")
            print("Colunas analisadas:", [col for col in colunas if col not in ['FAIXA', 'Indicador']])
            print("="*80)
            print("\nEncerrando execução...")
            sys.exit(1)
        
        return ultima_data
            
    except Exception as e:
        print(f"\n{'='*80}")
        print(f"ERRO ao ler arquivo Excel: {e}")
        print(f"{'='*80}")
        import traceback
        traceback.print_exc()
        print("\nEncerrando execução...")
        sys.exit(1)

def calcular_data_inicio(maior_data_xlsx):
    """
    Calcula a data de início para a consulta (dia seguinte à última data do arquivo).
    """
    if maior_data_xlsx is None:
        print(f"\n{'='*80}")
        print("ERRO: Não foi possível identificar a data inicial!")
        print(f"{'='*80}")
        sys.exit(1)
    
    data_inicio = maior_data_xlsx.date() + timedelta(days=1)
    print(f"\nData início para consulta: {data_inicio.strftime('%Y-%m-%d')}")
    return data_inicio

def df_consulta(conn_bd2, sql_file, data_inicio):
    """
    Executa a consulta substituindo a variável @dataIni no arquivo SQL.
    
    Parâmetros:
    -----------
    conn_bd2 : pyodbc.Connection
        Conexão com o banco de dados
    sql_file : str
        Caminho do arquivo SQL
    data_inicio : datetime.date
        Data a ser substituída na variável @dataIni
    
    Retorna:
    --------
    pd.DataFrame
        DataFrame com os resultados da consulta
    """
    # Lê o conteúdo da query
    with open(sql_file, "r", encoding="utf-8") as f:
        query_original = f.read()
    
    # Formata a data no formato YYYY-MM-DD
    data_str = data_inicio.strftime('%Y-%m-%d')
    
    print(f"\n[SUBSTITUIÇÃO] Buscando padrão '@dataIni' no SQL...")
    print(f"[SUBSTITUIÇÃO] Formatando data: {data_str}")
    
    # Usa regex para encontrar e substituir de forma robusta
    # Padrão: declare @dataIni as date = 'YYYY-MM-DD' (com variações de espaço)
    padrao = r"declare\s+@dataIni\s+as\s+date\s*=\s*'[^']*'"
    
    # Verificar se encontrou o padrão
    if re.search(padrao, query_original, re.IGNORECASE):
        print(f"[✓] Padrão encontrado no SQL")
        substituicao = f"declare @dataIni as date = '{data_str}'"
        query_modificada = re.sub(padrao, substituicao, query_original, flags=re.IGNORECASE)
        
        # Log das mudanças
        linhas_original = query_original.split('\n')
        linhas_modificada = query_modificada.split('\n')
        
        for i, (orig, mod) in enumerate(zip(linhas_original[:50], linhas_modificada[:50])):
            if orig != mod:
                print(f"\n[LINHA {i+1}] Original:")
                print(f"  {orig.strip()}")
                print(f"[LINHA {i+1}] Modificada:")
                print(f"  {mod.strip()}")
    else:
        print(f"[✗] AVISO: Padrão '@dataIni' NÃO encontrado no SQL!")
        print(f"[✗] A consulta será executada sem modificação da data")
        query_modificada = query_original
    
    cursor = conn_bd2.cursor()
    
    try:
        print(f"\n[EXECUÇÃO] Executando consulta com @dataIni = '{data_str}'...")
        cursor.execute(query_modificada)
        
        # Navega pelos resultados até encontrar o último SELECT
        columns = None
        data = None
        
        if cursor.description:
            columns = [column[0] for column in cursor.description]
            data = cursor.fetchall()
            print(f"[✓] Primeiro result set encontrado: {len(data)} linhas")
        
        result_set_count = 1
        while cursor.nextset():
            if cursor.description:
                result_set_count += 1
                columns = [column[0] for column in cursor.description]
                data = cursor.fetchall()
                print(f"[✓] Result set #{result_set_count} encontrado: {len(data)} linhas")
        
        if columns is None or data is None:
            raise ValueError("Nenhum resultado encontrado na query")
        
        df = pd.DataFrame.from_records(data, columns=columns)
        print(f"\n[✓] Query retornou {len(df)} linhas com {len(columns)} colunas")
        
        return df
        
    except Exception as e:
        print(f"\n[✗] Erro ao executar query: {e}")
        import traceback
        traceback.print_exc()
        raise
    finally:
        cursor.close()

# ============================================================================
# EXECUÇÃO PRINCIPAL
# ============================================================================

print("="*80)
print("INICIANDO PROCESSAMENTO PayJoy")
print("="*80)

# 1. Identifica a maior data no arquivo Excel
maior_data_xlsx = identificar_maior_data_xlsx(xlsx_file)

# 2. Calcula data de início (dia seguinte à última data do arquivo)
data_inicio = calcular_data_inicio(maior_data_xlsx)

# 3. Verifica se há dados para processar
ontem = datetime.now().date() - timedelta(days=1)

if data_inicio > ontem:
    print(f"\n{'='*80}")
    print("Relatório já está atualizado! Nenhuma data para processar.")
    print(f"{'='*80}")
    df_resultado = pd.DataFrame()
else:
    print(f"\nPeríodo a processar: de {data_inicio.strftime('%Y-%m-%d')} até {ontem.strftime('%Y-%m-%d')}")
    
    # 4. Executa a consulta
    df_resultado = df_consulta(conn_bd2, sql_file, data_inicio)
    
    print(f"\n{'='*80}")
    print("CONSULTA EXECUTADA COM SUCESSO!")
    print(f"{'='*80}")
    print(f"Total de linhas retornadas: {len(df_resultado)}")
    print(f"Colunas: {df_resultado.columns.tolist()}")
    print(f"{'='*80}")
    
    if len(df_resultado) > 0:
        print("\nPrimeiras 10 linhas do resultado:")
        print(df_resultado.head(10))
        
        print("\nDatas únicas no resultado:")
        if 'DATA' in df_resultado.columns:
            datas_unicas = sorted(df_resultado['DATA'].unique())
            print(datas_unicas)

conn_bd2.close()
print("\nConexão fechada.")
print(f"\nDataFrame 'df_resultado' disponível com {len(df_resultado)} linhas")

================================================================================
INICIANDO PROCESSAMENTO PayJoy
================================================================================
Arquivo Excel lido com sucesso!

Colunas encontradas no arquivo: ['FAIXA', 'Indicador', datetime.datetime(2025, 12, 4, 0, 0), datetime.datetime(2025, 12, 6, 0, 0), datetime.datetime(2025, 12, 8, 0, 0), datetime.datetime(2025, 12, 10, 0, 0), datetime.datetime(2025, 12, 11, 0, 0), datetime.datetime(2025, 12, 12, 0, 0), datetime.datetime(2025, 12, 13, 0, 0), datetime.datetime(2025, 12, 15, 0, 0)]

Maior data encontrada: 2025-12-15 (coluna já era datetime)

Data início para consulta: 2025-12-16

Período a processar: de 2025-12-16 até 2025-12-18

[SUBSTITUIÇÃO] Buscando padrão '@dataIni' no SQL...
[SUBSTITUIÇÃO] Formatando data: 2025-12-16
[✓] Padrão encontrado no SQL

[LINHA 9] Original:
  declare @dataIni as date = '2025-12-05';
[LINHA 9] Modificada:
  declare @dataIni as date = '2025-12-16';

[EXECUÇÃO] Executando consulta com @dataIni = '2025-12-16'...
[✓] Result set #2 encontrado: 12 linhas

[✓] Query retornou 12 linhas com 25 colunas

================================================================================
CONSULTA EXECUTADA COM SUCESSO!
================================================================================
Total de linhas retornadas: 12
Colunas: ['DATA', 'FAIXA', 'Assigned_Portfolio', 'Reachable_Portfolio', 'Contacted_Portfolio', 'Active_Agents', 'Total_Call_Attempts', 'Total_Answered_Calls', 'Dont_Know_on_the_Phone', 'Total_Answered_Calls_Excl_Short_Calls', 'Unique_Customers_Reached', 'Unique_Customers_Reached_Excl_Short_Calls', 'Total_RPCs_Right_Party_Contacts', 'Unique_RPCs', 'Promises_to_Pay_PTP', 'Debt_Not_Recognized', 'Payment_Already_Made', 'Device_Reported_Stolen', 'Device_Warranty_Acess_issue', 'Promises_to_Pay_per_Active_Agent', 'Total_AHT', 'AHT_Excluding_Short_Calls', 'Number_Of_SMS_Sent', 'Number_Of_WA_Sent', 'Number_Of_Email_sent']
================================================================================

Primeiras 10 linhas do resultado:
         DATA       FAIXA  Assigned_Portfolio  Reachable_Portfolio  \
0  2025-12-16   DPD 31-60                2558                    0
1  2025-12-16   DPD 61-90                2035                    0
2  2025-12-16   DPD 16-30                2399                    0
3  2025-12-16  DPD 91-120                1408                    0
4  2025-12-17   DPD 16-30                2399                    0
5  2025-12-17   DPD 61-90                2035                    0
6  2025-12-17   DPD 31-60                2558                    0
7  2025-12-17  DPD 91-120                1408                    0
8  2025-12-18   DPD 31-60                2558                    0
9  2025-12-18  DPD 91-120                1408                    0

   Contacted_Portfolio  Active_Agents  Total_Call_Attempts  \
0                 2332              4                 3882
1                 1805              4                 3035
2                 1234              4                 1849
3                  886              4                 1477
4                 2139              4                 2944
5                 1830              4                 2680
6                 2363              4                 3436
7                  956              4                 1150
8                 2317              4                 3150
9                 1282              4                 1662

   Total_Answered_Calls  Dont_Know_on_the_Phone  \
0                   411                      20
1                   252                      12
2                   214                      11
3                   145                       7
4                   346                      15
5                   267                       8
6                   282                       9
7                    92                       2
8                   309                      18
9                   173                      16

   Total_Answered_Calls_Excl_Short_Calls  ...  Debt_Not_Recognized  \
0                                    306  ...                    0
1                                    157  ...                    0
2                                    162  ...                    2
3                                    110  ...                    0
4                                    202  ...                    0
5                                    160  ...                    2
6                                    189  ...                    0
7                                     66  ...                    0
8                                    196  ...                    0
9                                     96  ...                    1

   Payment_Already_Made  Device_Reported_Stolen  Device_Warranty_Acess_issue  \
0                     1                       0                            0
1                     1                       0                            0
2                     0                       0                            0
3                     0                       0                            0
4                     1                       0                            0
5                     0                       0                            0
6                     1                       0                            0
7                     0                       0                            0
8                     3                       0                            0
9                     0                       0                            0

   Promises_to_Pay_per_Active_Agent  Total_AHT  AHT_Excluding_Short_Calls  \
0                                 1       3796                       3638
1                                 0       1743                       1592
2                                 1       2473                       2385
3                                 0       1306                       1230
4                                 1       2178                       1979
5                                 1       1982                       1846
6                                 1       2163                       2036
7                                 0        516                        460
8                                 1       2038                       1840
9                                 0        678                        561

   Number_Of_SMS_Sent  Number_Of_WA_Sent  Number_Of_Email_sent
0                1440                  0                     0
1                1150                  0                     0
2                1914                  0                     0
3                 761                  0                     0
4                1854                  0                     0
5                2201                  0                     0
6                2720                  0                     0
7                1590                  0                     0
8                   0                  0                     0
9                   0                  0                     0

[10 rows x 25 columns]

Datas únicas no resultado:
[datetime.date(2025, 12, 16), datetime.date(2025, 12, 17), datetime.date(2025, 12, 18)]

Conexão fechada.

DataFrame 'df_resultado' disponível com 12 linhas

In [48]:

# Verifica quantas datas únicas existem
datas_unicas = df_resultado['DATA'].unique()
print(f"Datas encontradas: {datas_unicas}")
print(f"Total de datas: {len(datas_unicas)}")

# Define automaticamente as colunas de indicadores
# Todas as colunas EXCETO 'DATA' e 'FAIXA'
colunas_todas = df_resultado.columns.tolist()
colunas_id = ['DATA', 'FAIXA']  # Colunas identificadoras
value_columns = [col for col in colunas_todas if col not in colunas_id]

print(f"\nColunas identificadoras: {colunas_id}")
print(f"Total de indicadores encontrados: {len(value_columns)}")

# Faz o unpivot (melt) mantendo DATA e FAIXA como identificadores
df_transposto = df_resultado.melt(
    id_vars=['DATA', 'FAIXA'],
    value_vars=value_columns,
    var_name='Indicador',
    value_name='Valor'
)

print(f"\nDataFrame após melt:")
print(df_transposto.head(10))

# Pivota para colocar as datas como colunas
df_final = df_transposto.pivot_table(
    index=['FAIXA', 'Indicador'],
    columns='DATA',
    values='Valor',
    aggfunc='first'  # Usa o primeiro valor caso haja duplicatas
).reset_index()

# Remove o nome do índice das colunas (fica mais limpo)
df_final.columns.name = None

# Ordena por FAIXA e Indicador
df_final = df_final.sort_values(['FAIXA', 'Indicador']).reset_index(drop=True)

# Visualiza o resultado
print(f"\n{'='*60}")
print(f"Estrutura final:")
print(f"Total de linhas: {len(df_final)}")
print(f"Faixas únicas: {df_final['FAIXA'].unique()}")
print(f"Colunas: {df_final.columns.tolist()}")
print(f"{'='*60}")
print("\nPrimeiras 30 linhas:")
print(df_final.head(30))

df_final

Datas encontradas: [datetime.date(2025, 12, 16) datetime.date(2025, 12, 17)
 datetime.date(2025, 12, 18)]
Total de datas: 3

Colunas identificadoras: ['DATA', 'FAIXA']
Total de indicadores encontrados: 23

DataFrame após melt:
         DATA       FAIXA           Indicador  Valor
0  2025-12-16   DPD 31-60  Assigned_Portfolio   2558
1  2025-12-16   DPD 61-90  Assigned_Portfolio   2035
2  2025-12-16   DPD 16-30  Assigned_Portfolio   2399
3  2025-12-16  DPD 91-120  Assigned_Portfolio   1408
4  2025-12-17   DPD 16-30  Assigned_Portfolio   2399
5  2025-12-17   DPD 61-90  Assigned_Portfolio   2035
6  2025-12-17   DPD 31-60  Assigned_Portfolio   2558
7  2025-12-17  DPD 91-120  Assigned_Portfolio   1408
8  2025-12-18   DPD 31-60  Assigned_Portfolio   2558
9  2025-12-18  DPD 91-120  Assigned_Portfolio   1408

============================================================
Estrutura final:
Total de linhas: 92
Faixas únicas: ['DPD 16-30' 'DPD 31-60' 'DPD 61-90' 'DPD 91-120']
Colunas: ['FAIXA', 'Indicador', datetime.date(2025, 12, 16), datetime.date(2025, 12, 17), datetime.date(2025, 12, 18)]
============================================================

Primeiras 30 linhas:
        FAIXA                                  Indicador  2025-12-16  \
0   DPD 16-30                  AHT_Excluding_Short_Calls        2385
1   DPD 16-30                              Active_Agents           4
2   DPD 16-30                         Assigned_Portfolio        2399
3   DPD 16-30                        Contacted_Portfolio        1234
4   DPD 16-30                        Debt_Not_Recognized           2
5   DPD 16-30                     Device_Reported_Stolen           0
6   DPD 16-30                Device_Warranty_Acess_issue           0
7   DPD 16-30                     Dont_Know_on_the_Phone          11
8   DPD 16-30                       Number_Of_Email_sent           0
9   DPD 16-30                         Number_Of_SMS_Sent        1914
10  DPD 16-30                          Number_Of_WA_Sent           0
11  DPD 16-30                       Payment_Already_Made           0
12  DPD 16-30                        Promises_to_Pay_PTP           7
13  DPD 16-30           Promises_to_Pay_per_Active_Agent           1
14  DPD 16-30                        Reachable_Portfolio           0
15  DPD 16-30                                  Total_AHT        2473
16  DPD 16-30                       Total_Answered_Calls         214
17  DPD 16-30      Total_Answered_Calls_Excl_Short_Calls         162
18  DPD 16-30                        Total_Call_Attempts        1849
19  DPD 16-30            Total_RPCs_Right_Party_Contacts          16
20  DPD 16-30                   Unique_Customers_Reached          43
21  DPD 16-30  Unique_Customers_Reached_Excl_Short_Calls          32
22  DPD 16-30                                Unique_RPCs          16
23  DPD 31-60                  AHT_Excluding_Short_Calls        3638
24  DPD 31-60                              Active_Agents           4
25  DPD 31-60                         Assigned_Portfolio        2558
26  DPD 31-60                        Contacted_Portfolio        2332
27  DPD 31-60                        Debt_Not_Recognized           0
28  DPD 31-60                     Device_Reported_Stolen           0
29  DPD 31-60                Device_Warranty_Acess_issue           0

    2025-12-17  2025-12-18
0         1979        2479
1            4           4
2         2399        2399
3         2139        2166
4            0           0
5            0           0
6            0           0
7           15          24
8            0           0
9         1854           0
10           0           0
11           1           2
12           4          11
13           1           2
14           0           0
15        2178        2718
16         346         445
17         202         282
18        2944        3567
19          10          18
20          69          90
21          37          56
22          10          18
23        2036        1840
24           4           4
25        2558        2558
26        2363        2317
27           0           0
28           0           0
29           0           0

,FAIXA,Indicador,2025-12-16,2025-12-17,2025-12-18
0,DPD 16-30,AHT_Excluding_Short_Calls,2385,1979,2479
1,DPD 16-30,Active_Agents,4,4,4
2,DPD 16-30,Assigned_Portfolio,2399,2399,2399
3,DPD 16-30,Contacted_Portfolio,1234,2139,2166
4,DPD 16-30,Debt_Not_Recognized,2,0,0
...,...,...,...,...,...
87,DPD 91-120,Total_Call_Attempts,1477,1150,1662
88,DPD 91-120,Total_RPCs_Right_Party_Contacts,7,1,5
89,DPD 91-120,Unique_Customers_Reached,28,18,32
90,DPD 91-120,Unique_Customers_Reached_Excl_Short_Calls,21,12,19
91,DPD 91-120,Unique_RPCs,7,1,5

In [49]:
df_resultado

,DATA,FAIXA,Assigned_Portfolio,Reachable_Portfolio,Contacted_Portfolio,Active_Agents,Total_Call_Attempts,Total_Answered_Calls,Dont_Know_on_the_Phone,Total_Answered_Calls_Excl_Short_Calls,...,Debt_Not_Recognized,Payment_Already_Made,Device_Reported_Stolen,Device_Warranty_Acess_issue,Promises_to_Pay_per_Active_Agent,Total_AHT,AHT_Excluding_Short_Calls,Number_Of_SMS_Sent,Number_Of_WA_Sent,Number_Of_Email_sent
0,2025-12-16,DPD 31-60,2558,0,2332,4,3882,411,20,306,...,0,1,0,0,1,3796,3638,1440,0,0
1,2025-12-16,DPD 61-90,2035,0,1805,4,3035,252,12,157,...,0,1,0,0,0,1743,1592,1150,0,0
2,2025-12-16,DPD 16-30,2399,0,1234,4,1849,214,11,162,...,2,0,0,0,1,2473,2385,1914,0,0
3,2025-12-16,DPD 91-120,1408,0,886,4,1477,145,7,110,...,0,0,0,0,0,1306,1230,761,0,0
4,2025-12-17,DPD 16-30,2399,0,2139,4,2944,346,15,202,...,0,1,0,0,1,2178,1979,1854,0,0
5,2025-12-17,DPD 61-90,2035,0,1830,4,2680,267,8,160,...,2,0,0,0,1,1982,1846,2201,0,0
6,2025-12-17,DPD 31-60,2558,0,2363,4,3436,282,9,189,...,0,1,0,0,1,2163,2036,2720,0,0
7,2025-12-17,DPD 91-120,1408,0,956,4,1150,92,2,66,...,0,0,0,0,0,516,460,1590,0,0
8,2025-12-18,DPD 31-60,2558,0,2317,4,3150,309,18,196,...,0,3,0,0,1,2038,1840,0,0,0
9,2025-12-18,DPD 91-120,1408,0,1282,4,1662,173,16,96,...,1,0,0,0,0,678,561,0,0,0
10,2025-12-18,DPD 16-30,2399,0,2166,4,3567,445,24,282,...,0,2,0,0,2,2718,2479,0,0,0
11,2025-12-18,DPD 61-90,2035,0,1799,4,2390,203,13,126,...,0,0,0,0,2,1486,1348,0,0,0

In [50]:
import pandas as pd
from src.db_connection import get_connection

def df_contratos_payjoy():
    """
    Busca os contratos PayJoy com suas respectivas faixas (DPD_BUCKET)
    
    Returns:
        DataFrame com colunas: Assigned_Portfolio, FAIXA
    """
    # Cria a conexão
    conn_bd2 = get_connection("SERVER_BD2", "DATABASE_BD2")
    
    # Query SQL
    query = """
    SELECT
        Assigned_Portfolio
    ,   DPD_BUCKET as FAIXA
    FROM OPENQUERY([TRC_BD_LINKED],
    '
        SELECT 
            ltrim(rtrim(contrato_fin)) Assigned_Portfolio
        ,   DPD_BUCKET
        ,   cast(CALENDAR_DATE as date) dt_base 
        FROM SRC..AUX_PAYJOY_REMESSA 
        WHERE CALENDAR_DATE = (SELECT MAX(CALENDAR_DATE) FROM SRC..AUX_PAYJOY_REMESSA)
    '
    )
    """
    
    try:
        # Executa a query e retorna o DataFrame
        df = pd.read_sql(query, conn_bd2)
        
        print(f"Total de contratos: {len(df)}")
        print(f"Faixas disponíveis: {df['FAIXA'].unique()}")
        
        return df
        
    except Exception as e:
        print(f"Erro ao executar query: {e}")
        raise
    finally:
        conn_bd2.close()

# Executa a função
df_contratos = df_contratos_payjoy()
df_contratos

Total de contratos: 8400
Faixas disponíveis: ['DPD 61-90' 'DPD 91-120' 'DPD 16-30' 'DPD 31-60']

C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_5156\4052977116.py:33: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn_bd2)

     Assigned_Portfolio       FAIXA
0            54988427ID   DPD 61-90
1            54988428ID  DPD 91-120
2            54988429ID  DPD 91-120
3            54988430ID   DPD 16-30
4            54988431ID  DPD 91-120
...                 ...         ...
8395         55154585ID   DPD 16-30
8396         55154586ID   DPD 16-30
8397         55154587ID   DPD 16-30
8398         55154588ID   DPD 16-30
8399         55154589ID   DPD 16-30

[8400 rows x 2 columns]

In [51]:
import pandas as pd
import os
from glob import glob
import re

def consolidar_mailings_payjoy(caminho_pasta=r"\\trc-dc-ad\Planejamento\00 - USUÁRIOS\0003_Daniel Kodama\PAYJOY\mailings payjoy"):
    """
    Consolida todos os arquivos CSV de mailings PayJoy em um único DataFrame
    """
    
    arquivos = glob(os.path.join(caminho_pasta, "*.csv"))
    
    if not arquivos:
        print(f"Nenhum arquivo CSV encontrado em: {caminho_pasta}")
        return pd.DataFrame()
    
    print(f"Encontrados {len(arquivos)} arquivos CSV\n")
    
    lista_dfs = []
    arquivos_com_erro = []
    
    for arquivo in arquivos:
        try:
            nome_arquivo = os.path.basename(arquivo)
            nome_sem_extensao = nome_arquivo.replace('.csv', '')
            
            # Busca padrão de data no nome: DD.MM ou DD/MM
            match = re.search(r'(\d{1,2})[./](\d{2})', nome_sem_extensao)
            
            if match:
                dia = match.group(1).zfill(2)  # Adiciona zero à esquerda se necessário
                mes = match.group(2)
                data_str = f"{dia}/{mes}"
            else:
                # Se não encontrar data, usa os últimos 4 caracteres (método antigo)
                ultimos_4_chars = nome_sem_extensao[-4:]
                data_str = ultimos_4_chars.replace('.', '/')
            
            # Tenta diferentes combinações de encoding e separador
            df_temp = None
            for sep in [';', ',', '\t']:
                for enc in ['latin-1', 'utf-8', 'cp1252']:
                    try:
                        df_temp = pd.read_csv(arquivo, usecols=['CHAVE_POPUP'], encoding=enc, sep=sep)
                        if not df_temp.empty and 'CHAVE_POPUP' in df_temp.columns:
                            break
                    except:
                        continue
                if df_temp is not None and not df_temp.empty:
                    break
            
            if df_temp is None or df_temp.empty:
                raise Exception("Não foi possível ler o arquivo com nenhuma combinação")
            
            df_temp['DATA'] = data_str
            lista_dfs.append(df_temp)
            
            print(f"✓ {nome_arquivo} - {len(df_temp)} registros - Data: {data_str}")
            
        except Exception as e:
            print(f"✗ ERRO em {nome_arquivo}: {e}")
            arquivos_com_erro.append((nome_arquivo, str(e)))
            continue
    
    if arquivos_com_erro:
        print(f"\n{'='*60}")
        print("ARQUIVOS COM ERRO:")
        for nome, erro in arquivos_com_erro:
            print(f"  - {nome}: {erro}")
        print(f"{'='*60}\n")
    
    if lista_dfs:
        df_consolidado = pd.concat(lista_dfs, ignore_index=True)
        
        print(f"\n{'='*60}")
        print(f"Total de registros consolidados: {len(df_consolidado)}")
        print(f"Datas únicas: {sorted(df_consolidado['DATA'].unique())}")
        print(f"Total de contratos únicos: {df_consolidado['CHAVE_POPUP'].nunique()}")
        print(f"{'='*60}")
        
        return df_consolidado
    else:
        print("Nenhum dado foi consolidado.")
        return pd.DataFrame()

df_mailings = consolidar_mailings_payjoy()
df_mailings

Encontrados 23 arquivos CSV

✓ PAYJOY-ATIVO.01.12.csv - 6889 registros - Data: 01/12
✓ PAYJOY-ATIVO.02.12.csv - 6873 registros - Data: 02/12
✓ PAYJOY-ATIVO.03.12.csv - 6873 registros - Data: 03/12
✓ PAYJOY-ATIVO.18.11.csv - 7260 registros - Data: 18/11
✓ PAYJOY-ATIVO.19.11.csv - 7260 registros - Data: 19/11
✓ PAYJOY-ATIVO.21.11.csv - 7260 registros - Data: 21/11
✓ PAYJOY-ATIVO.24.11.csv - 7265 registros - Data: 24/11
✓ PAYJOY-ATIVO.25.11.csv - 7265 registros - Data: 25/11
✓ PAYJOY-ATIVO.26.11.csv - 6898 registros - Data: 26/11
✓ PAYJOY-ATIVO.27.11.csv - 6889 registros - Data: 27/11
✓ PAYJOY-ATIVO.28.11.csv - 6889 registros - Data: 28/11
✓ PAYJOY-ATIVO_03.12.csv - 8243 registros - Data: 03/12
✓ PAYJOY-ATIVO_04.12.csv - 8243 registros - Data: 04/12
✓ PAYJOY-ATIVO_05.12.csv - 8243 registros - Data: 05/12
✓ PAYJOY-ATIVO_08.12.csv - 8210 registros - Data: 08/12
✓ PAYJOY-ATIVO_09.12.csv - 8204 registros - Data: 09/12
✓ PAYJOY-ATIVO_10.12.csv - 8204 registros - Data: 10/12
✓ PAYJOY-ATIVO_11.12.csv - 7373 registros - Data: 11/12
✓ PAYJOY-ATIVO_12.12.csv - 8336 registros - Data: 12/12
✓ PAYJOY-ATIVO_16.12.csv - 8399 registros - Data: 16/12
✓ PAYJOY-ATIVO_17.12.csv - 8399 registros - Data: 17/12
✓ PAYJOY-ATIVO_18.12.csv - 8399 registros - Data: 18/12
✗ ERRO em PAYJOY-ATIVO_19.12.csv: Não foi possível ler o arquivo com nenhuma combinação

============================================================
ARQUIVOS COM ERRO:
  - PAYJOY-ATIVO_19.12.csv: Não foi possível ler o arquivo com nenhuma combinação
============================================================


============================================================
Total de registros consolidados: 167874
Datas únicas: ['01/12', '02/12', '03/12', '04/12', '05/12', '08/12', '09/12', '10/12', '11/12', '12/12', '16/12', '17/12', '18/11', '18/12', '19/11', '21/11', '24/11', '25/11', '26/11', '27/11', '28/11']
Total de contratos únicos: 25233
============================================================

                 CHAVE_POPUP   DATA
0                   DBBBMRNZ  01/12
1                    DBBDKFD  01/12
2                    DBBGSDM  01/12
3                    DBBHDKF  01/12
4                    DBBHNDN  01/12
...                      ...    ...
167869  54989709ID            18/12
167870  54991533ID            18/12
167871  54991324ID            18/12
167872  54995207ID            18/12
167873  54988796ID            18/12

[167874 rows x 2 columns]

In [53]:
def consolidar_mailings_por_faixa(df_mailings, df_contratos, ordenar_datas=True, contratos_unicos=True):
    """
    Cruza os mailings com os contratos para obter faixas e gera tabela pivotada
    """
    
    # LIMPEZA: Remove espaços em branco das colunas de chave
    df_mailings['CHAVE_POPUP'] = df_mailings['CHAVE_POPUP'].astype(str).str.strip()
    df_contratos['Assigned_Portfolio'] = df_contratos['Assigned_Portfolio'].astype(str).str.strip()
    
    # Cruzamento
    df_mailings_com_faixa = df_mailings.merge(
        df_contratos,
        left_on='CHAVE_POPUP',
        right_on='Assigned_Portfolio',
        how='left'
    )
    
    # Contagem
    if contratos_unicos:
        df_contagem = df_mailings_com_faixa.groupby(['FAIXA', 'DATA'])['CHAVE_POPUP'].nunique().reset_index()
    else:
        df_contagem = df_mailings_com_faixa.groupby(['FAIXA', 'DATA'])['CHAVE_POPUP'].count().reset_index()
    
    df_contagem.columns = ['FAIXA', 'DATA', 'CONTAGEM']
    
    # Pivota
    df_pivot = df_contagem.pivot(
        index='FAIXA',
        columns='DATA',
        values='CONTAGEM'
    ).fillna(0).astype(int)
    
    # Ordena datas se solicitado
    if ordenar_datas:
        def ordenar_data(data_str):
            """Converte DD/MM para tupla (dia, mes) para ordenação"""
            try:
                dia, mes = data_str.split('/')
                return (int(mes), int(dia))
            except:
                return (99, 99)
        
        colunas_ordenadas = sorted(df_pivot.columns, key=ordenar_data)
        df_pivot = df_pivot[colunas_ordenadas]
    
    # Reset index
    df_pivot = df_pivot.reset_index()
    
    return df_pivot

# Uso:
df_pivot = consolidar_mailings_por_faixa(df_mailings, df_contratos)
df_pivot

DATA,FAIXA,03/12,04/12,05/12,08/12,09/12,10/12,11/12,12/12,16/12,17/12,18/12
0,DPD 16-30,1411,1411,1411,1401,1400,1400,1400,2379,2399,2399,2399
1,DPD 31-60,2555,2555,2555,2542,2539,2539,2539,2532,2557,2557,2557
2,DPD 61-90,2033,2033,2033,2028,2027,2027,2027,2022,2035,2035,2035
3,DPD 91-120,1408,1408,1408,1408,1407,1407,1407,1403,1408,1408,1408

In [54]:
import pandas as pd

def substituir_zeros_com_pivot(df_transposto, df_pivot):
    """
    Substitui valores 0 do df_transposto pelos valores do df_pivot,
    respeitando FAIXA + data.
    
    Args:
        df_transposto: DataFrame com estrutura [FAIXA, Indicador, 2025-12-04, 2025-12-05, ...]
        df_pivot: DataFrame com estrutura [FAIXA, 3/12, 4/12, 5/12, ...]
    
    Returns:
        DataFrame atualizado
    """
    
    df_resultado = df_transposto.copy()
    
    # Pegar as colunas de data do df_transposto
    colunas_data = [col for col in df_transposto.columns if col not in ['FAIXA', 'Indicador']]
    
    # Para cada linha do df_pivot
    for _, row_pivot in df_pivot.iterrows():
        faixa = row_pivot["FAIXA"]
        
        # Para cada coluna de data no df_transposto
        for col_transposto in colunas_data:
            # Converter coluna do df_transposto para formato do df_pivot
            if isinstance(col_transposto, str) and '-' in col_transposto:
                partes = col_transposto.split('-')
                dia = partes[2].lstrip('0') or '0'
                mes = partes[1].lstrip('0') or '0'
                col_pivot_format = f"{dia}/{mes}"
            elif hasattr(col_transposto, 'day') and hasattr(col_transposto, 'month'):
                dia = str(col_transposto.day)
                mes = str(col_transposto.month)
                col_pivot_format = f"{dia}/{mes}"
            else:
                continue
            
            # Se essa coluna existe no df_pivot
            if col_pivot_format in df_pivot.columns:
                valor_pivot = row_pivot[col_pivot_format]
                
                # Substituir os zeros APENAS para o indicador Reachable_Portfolio
                mask = (
                    (df_resultado["FAIXA"] == faixa) & 
                    (df_resultado["Indicador"] == "Reachable_Portfolio") &
                    (df_resultado[col_transposto] == 0)
                )
                df_resultado.loc[mask, col_transposto] = valor_pivot
    
    return df_resultado


df_PAYJOY = substituir_zeros_com_pivot(df_final, df_pivot)
print("DataFrame atualizado:")
df_PAYJOY

DataFrame atualizado:

,FAIXA,Indicador,2025-12-16,2025-12-17,2025-12-18
0,DPD 16-30,AHT_Excluding_Short_Calls,2385,1979,2479
1,DPD 16-30,Active_Agents,4,4,4
2,DPD 16-30,Assigned_Portfolio,2399,2399,2399
3,DPD 16-30,Contacted_Portfolio,1234,2139,2166
4,DPD 16-30,Debt_Not_Recognized,2,0,0
...,...,...,...,...,...
87,DPD 91-120,Total_Call_Attempts,1477,1150,1662
88,DPD 91-120,Total_RPCs_Right_Party_Contacts,7,1,5
89,DPD 91-120,Unique_Customers_Reached,28,18,32
90,DPD 91-120,Unique_Customers_Reached_Excl_Short_Calls,21,12,19
91,DPD 91-120,Unique_RPCs,7,1,5

In [55]:
import pandas as pd

# Exemplo: supondo que a coluna que guarda o nome do indicador se chama "Indicador"
df_filtrado = df_PAYJOY[df_PAYJOY["Indicador"] == "Reachable_Portfolio"]
df_filtrado

         FAIXA            Indicador  2025-12-16  2025-12-17  2025-12-18
14   DPD 16-30  Reachable_Portfolio        2399        2399        2399
37   DPD 31-60  Reachable_Portfolio        2557        2557        2557
60   DPD 61-90  Reachable_Portfolio        2035        2035        2035
83  DPD 91-120  Reachable_Portfolio        1408        1408        1408