In [ ]:
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> GERAR DADOS

# import importlib
# importlib.reload(queries)
from src.data_wrangling_mailingHist import tratar_base_mailing_hist
from src.db_connection import get_connection
from Projects.Ouze.src.queries import get_query_discagens, get_query_cad_devf, get_query_mailing_hist, get_query_discagens_trestto, get_query_tabulacao_aciona, get_query_base_acionamentos, get_query_dw_calendario, get_query_pagamentos, get_query_acordos
import pandas as pd

# DADOS SRC

def data_loader(conn_trc, conn_bd2, conn_src):

    df_discagens_expert = pd.read_sql(
        get_query_discagens('2025-09-01', '2025-09-30'), 
        conn_src
    )
    df_cad_devf = pd.read_sql(
        get_query_cad_devf(), 
        conn_src
    )
    df_tab_acionamentos = pd.read_sql(
        get_query_base_acionamentos('2025-09-01', '2025-09-30'), 
        conn_src
    )

    # DADOS BD2/PLANEJAMENTO
    df_maling_hist = pd.read_sql(
        get_query_mailing_hist('2025-09-01', '2025-09-30'), 
        conn_bd2
    )
    df_maling_hist = tratar_base_mailing_hist(df_maling_hist, df_cad_devf)

    df_dw_calendario = pd.read_sql(
        get_query_dw_calendario(), 
        conn_bd2
    )
    df_tabulacao_aciona = pd.read_sql(
        get_query_tabulacao_aciona(), 
        conn_bd2
    )
    df_pagamentos = pd.read_sql(
        get_query_pagamentos('2025-09-01', '2025-09-30'), 
        conn_src
    )
    df_acordos = pd.read_sql(
        get_query_acordos('2025-09-01', '2025-09-30'), 
        conn_src
    )

    # DADOS BD2/TRC
    
    df_discagens_trestto = pd.read_sql(
        get_query_discagens_trestto('2025-09-01', '2025-09-30'), 
        conn_trc
    )
    
    return df_discagens_expert, df_cad_devf, df_tab_acionamentos, df_maling_hist, df_dw_calendario, df_tabulacao_aciona, df_pagamentos, df_acordos, df_discagens_trestto

def get_connection():
    conn_trc = get_connection("SERVER_BD2", "DATABASE_TRC")
    conn_bd2 = get_connection("SERVER_BD2", "DATABASE_BD2")
    conn_src = get_connection("SERVER_SRC", "DATABASE_SRC")

    df_discagens_expert, df_cad_devf, df_tab_acionamentos, df_maling_hist, df_dw_calendario, df_tabulacao_aciona, df_pagamentos, df_acordos, df_discagens_trestto = data_loader(conn_trc, conn_bd2, conn_src)

    return df_discagens_expert, df_cad_devf, df_tab_acionamentos, df_maling_hist, df_dw_calendario, df_tabulacao_aciona, df_pagamentos, df_acordos, df_discagens_trestto

In [ ]:
import importlib
from src import(queries, data_wrangling_discagens_trestto, data_wrangling_mailingHist, data_wrangling_acionamentos, data_wrangling_discagens_expert, data_wrangling_pagamentos, utils, pipeline_funil, data_loader, csv_cleaning)
importlib.reload(utils)
importlib.reload(data_loader)
importlib.reload(pipeline_funil)
importlib.reload(data_wrangling_discagens_trestto)
importlib.reload(data_wrangling_mailingHist)
importlib.reload(data_wrangling_acionamentos)
importlib.reload(data_wrangling_discagens_expert)
importlib.reload(data_wrangling_pagamentos)
importlib.reload(queries)
importlib.reload(csv_cleaning)

# 1. Carregar e ativar autoreload
# %load_ext autoreload
# %autoreload 2

# # 2. Fazer suas importações normalmente
# from src import (
#     queries,
#     data_wrangling_discagens_trestto,
#     data_wrangling_mailingHist,
#     data_wrangling_acionamentos,
#     data_wrangling_discagens_expert,
#     data_wrangling_pagamentos,
#     utils,
#     pipeline_funil,
#     data_loader,
#     csv_cleaning
# )

In [46]:
# from src.data_wrangling_mailingHist import tratar_base_mailing_hist
# from src.data_wrangling_discagens_expert import acionamentos_expert
from src.db_connection import get_connection
from src.queries import get_query_discagens, get_query_cad_devf, get_query_mailing_hist, get_query_discagens_trestto, get_query_tabulacao_aciona, get_query_base_acionamentos, get_query_dw_calendario, get_query_pagamentos, get_query_acordos
import pandas as pd
conn_trc = get_connection("SERVER_BD2", "DATABASE_TRC")
conn_bd2 = get_connection("SERVER_BD2", "DATABASE_BD2")
conn_src = get_connection("SERVER_SRC", "DATABASE_SRC")
# df_discagens_expert = pd.read_sql(
#     get_query_discagens('2025-11-01', '2025-11-17'), 
#     conn_src
# )
# df_cad_devf = pd.read_sql(
#     get_query_cad_devf(), 
#     conn_src
# )
# df_maling_hist = pd.read_sql(
#     get_query_mailing_hist('2025-11-01', '2025-11-17'), 
#     conn_bd2
# )
# df_maling_hist = tratar_base_mailing_hist(df_maling_hist, df_cad_devf)
df_dw_calendario = pd.read_sql(
    get_query_dw_calendario('2025-11-01', '2025-11-30'), 
    conn_bd2
)
df_dw_calendario
#df_acionamentos_expert, df_analitico_expert, df_enriquecido_discagens_expert_semFaixa, df_humano_tabulados_como_robo, df_dicagens_operacaoOutros = acionamentos_expert(df_discagens_expert, df_dw_calendario, df_maling_hist)
#df_acionamentos_expert

C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_38420\2890686504.py:22: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_dw_calendario = pd.read_sql(

,dt_data,dt_ano,dt_mes,dt_dia,nr_dia_semana,nr_dia_ano,fl_dia_util,nr_dia_util,quartil,mes_abreviado
0,2025-11-03,2025,11,3,2,307,1,1,Q4,Nov
1,2025-11-04,2025,11,4,3,308,1,2,Q4,Nov
2,2025-11-05,2025,11,5,4,309,1,3,Q4,Nov
3,2025-11-06,2025,11,6,5,310,1,4,Q4,Nov
4,2025-11-07,2025,11,7,6,311,1,5,Q4,Nov
5,2025-11-10,2025,11,10,2,314,1,6,Q4,Nov
6,2025-11-11,2025,11,11,3,315,1,7,Q4,Nov
7,2025-11-12,2025,11,12,4,316,1,8,Q4,Nov
8,2025-11-13,2025,11,13,5,317,1,9,Q4,Nov
9,2025-11-14,2025,11,14,6,318,1,10,Q4,Nov
10,2025-11-17,2025,11,17,2,321,1,11,Q4,Nov
11,2025-11-18,2025,11,18,3,322,1,12,Q4,Nov
12,2025-11-19,2025,11,19,4,323,1,13,Q4,Nov
13,2025-11-21,2025,11,21,6,325,1,14,Q4,Nov
14,2025-11-24,2025,11,24,2,328,1,15,Q4,Nov
15,2025-11-25,2025,11,25,3,329,1,16,Q4,Nov
16,2025-11-26,2025,11,26,4,330,1,17,Q4,Nov
17,2025-11-27,2025,11,27,5,331,1,18,Q4,Nov
18,2025-11-28,2025,11,28,6,332,1,19,Q4,Nov

In [6]:
#from src.data_wrangling_mailingHist import tratar_base_mailing_hist, gerar_acumulado_mailing_hist
#from src.data_wrangling_discagens_expert import acionamentos_expert
from src.db_connection import get_connection
from src.queries import get_query_discagens, get_query_cad_devf, get_query_mailing_hist, get_query_discagens_trestto, get_query_tabulacao_aciona, get_query_base_acionamentos, get_query_dw_calendario, get_query_pagamentos, get_query_acordos
import pandas as pd
conn_trc = get_connection("SERVER_BD2", "DATABASE_TRC")
conn_bd2 = get_connection("SERVER_BD2", "DATABASE_BD2")
conn_src = get_connection("SERVER_SRC", "DATABASE_SRC")

# df_cad_devf = pd.read_sql(
#     get_query_cad_devf(), 
#     conn_src
# )
# df_maling_hist = pd.read_sql(
#     get_query_mailing_hist('2025-11-01', '2025-11-17'), 
#     conn_bd2
# )
# df_maling_hist = tratar_base_mailing_hist(df_maling_hist, df_cad_devf)
df_dw_calendario = pd.read_sql(
    get_query_dw_calendario('2025-11-01', '2025-11-17'), 
    conn_bd2
)
# df_maling_acumulado = gerar_acumulado_mailing_hist(df_maling_hist, df_dw_calendario)
# df_maling_acumulado
df_dw_calendario

C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_38420\1509880068.py:19: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_dw_calendario = pd.read_sql(

,dt_data,dt_ano,dt_mes,dt_dia,nr_dia_semana,nr_dia_ano,fl_dia_util,nr_dia_util,quartil,mes_abreviado
0,2025-11-03,2025,11,3,2,307,1,1,Q4,Nov
1,2025-11-04,2025,11,4,3,308,1,2,Q4,Nov
2,2025-11-05,2025,11,5,4,309,1,3,Q4,Nov
3,2025-11-06,2025,11,6,5,310,1,4,Q4,Nov
4,2025-11-07,2025,11,7,6,311,1,5,Q4,Nov
5,2025-11-10,2025,11,10,2,314,1,6,Q4,Nov
6,2025-11-11,2025,11,11,3,315,1,7,Q4,Nov
7,2025-11-12,2025,11,12,4,316,1,8,Q4,Nov
8,2025-11-13,2025,11,13,5,317,1,9,Q4,Nov
9,2025-11-14,2025,11,14,6,318,1,10,Q4,Nov
10,2025-11-17,2025,11,17,2,321,1,11,Q4,Nov

In [ ]:
from src.db_connection import get_connection
from src.queries import get_query_discagens, get_query_cad_devf, get_query_mailing_hist, get_query_discagens_trestto, get_query_tabulacao_aciona, get_query_base_acionamentos, get_query_dw_calendario, get_query_pagamentos, get_query_acordos
#from src.data_wrangling_discagens_trestto import enriquecer_discagens_trestto, acionamentos_fxAtraso_origem_trestto
from src.data_wrangling_acionamentos import tratar_acionamentos_tabulacao, confere_tabulacao_acionamentos, enriquecer_acionamentos, acionamentos_fxAtraso_origem_humano
from src.data_wrangling_discagens_trestto import acionamentos_trestto
from src.data_wrangling_mailingHist import tratar_base_mailing_hist
from src.utils import transformar_funil_formato_long
import pandas as pd
# conn_trc = get_connection("SERVER_BD2", "DATABASE_TRC")
# conn_src = get_connection("SERVER_SRC", "DATABASE_SRC")
# conn_bd2 = get_connection("SERVER_BD2", "DATABASE_BD2")
# df_discagens_trestto = pd.read_sql(
#     get_query_discagens_trestto('2025-11-01', '2025-11-20'), 
#     conn_trc
# )
# df_cad_devf = pd.read_sql(
#     get_query_cad_devf(), 
#     conn_src
# )
# df_maling_hist = pd.read_sql(
#     get_query_mailing_hist('2025-11-01', '2025-11-25'), 
#     conn_bd2
# )
# df_maling_hist = tratar_base_mailing_hist(df_maling_hist, df_cad_devf)
# df_tabulacao_aciona = pd.read_sql(
#     get_query_tabulacao_aciona(), 
#     conn_bd2
# )
# df_tab_acionamentos = pd.read_sql(
#     get_query_base_acionamentos('2025-11-01', '2025-11-25'), 
#     conn_src
# )
# df_dw_calendario = pd.read_sql(
#     get_query_dw_calendario('2025-11-01', '2025-11-25'), 
#     conn_bd2
# )
df_acionamentos_trestto, df_analitico_trestto, df_enriquecido_discagens_trestto_semFaixa = acionamentos_trestto(df_discagens_trestto, df_maling_hist, df_dw_calendario)
df_acionamentos_trestto

In [ ]:
import os
# #df_conflitos_score
#df_acionamentos_enriquecido_limpo, df_acion_semFaixa, df_acion_semDescricao, df_acion_semOrigem 
df_final.to_csv('df_final.csv', sep=';', index=False, decimal=',', encoding='utf-8-sig')
os.startfile('df_final.csv')  # abre com o programa padrão

In [ ]:
from src.data_loader import get_date_range_from_csv

var = get_date_range_from_csv()
var

In [ ]:
# INTERSEÇÃO DE CPFS DISCADOS COM E SEM FAIXA DE ATRASO

from src.data_wrangling_discagens_trestto import tratar_discagens_trestto, enriquecer_discagens_trestto, acionamentos_esforco_trestto, interseção_cpfs_discados_trestto

mesagem_resultado = interseção_cpfs_discados_trestto(df_enriquecido_discagens_trestto_limpo, df_enriquecido_discagens_trestto_semFaixa)
mesagem_resultado

In [ ]:
import pandas as pd
from datetime import datetime, timedelta
from src.db_connection import get_connection
conn_trc = get_connection("SERVER_BD2", "DATABASE_TRC")

def get_max_date(conn_trc):
    """Retorna a última data na tabela DISCAGENS_TRESTTO"""
    query = """
    SELECT MAX(data) as max_data
    FROM DISCAGENS_TRESTTO
    """
    df = pd.read_sql(query, conn_trc)
    return df['max_data'].iloc[0]

def get_insert_query(data_consulta):
    """
    Gera a query de INSERT com a data formatada para o OPENQUERY
    data_consulta: objeto datetime ou string no formato YYYY-MM-DD
    """
    # Converte para datetime se necessário
    if isinstance(data_consulta, str):
        data_consulta = datetime.strptime(data_consulta, '%Y-%m-%d')
    
    # Formata a data inicial (00:00:00) e final (00:00:00 do dia seguinte)
    data_inicio = data_consulta.strftime('%Y%m%d')
    data_fim = (data_consulta + timedelta(days=1)).strftime('%Y%m%d')
    
    query = f"""
    INSERT INTO DISCAGENS_TRESTTO (
        DATA,
        CPF,
        SUBSTATUSURA,
        DISCAGEM,
        ALO,
        CPC,
        CPCA,
        PROMESSA
    )
    SELECT
        *
    FROM OPENQUERY([Trestto],
    '
        select
            DATA
        ,   CPF
        ,   SUBSTATUSURA AS SUBSTATUSURA
        ,   SUM(DISCAGEM) AS DISCAGEM
        ,   SUM(ALO) AS ALO
        ,   SUM(CPC) AS CPC
        ,   SUM(CPCA) AS CPCA
        ,   SUM(PP) AS PROMESSA
        from(
            select
                cast(datahoraligacao as date) data
            ,   CPF
            ,   DISCAGEM = 1
            ,   SUBSTATUSURA
            ,   TELEFONELIGACAO
            ,   CASE
                    WHEN SUBSTATUSURA IN (
                        ''ClienteAlegaPagamentoMais5Dias'',''NaoEfetuouPagamentoMais5Dias'',''QuestionaValor'',
                        ''SemAgentesVirtuaisDisponiveis'',''CPFValidadoBase'',''DesejaBoletoWhatsApp'',''ErroWSDividas'',
                        ''Mudou'',''NaoEsta'',''Ocupado'',''SegundaRecusa'',''AgendamentoQualquerHorario'',''AlegaPagamento'',
                        ''ClienteDesejaFatura'',''DificuldadeFinanceira'',''EfetuouPagamentoMais5Dias'',''Morreu'',
                        ''NaoConfirmouCliente'',''NaoDesejaAcordo'',''PrimeiraRecusa'',''Abandonada'',''ConfirmouAcordo'',
                        ''ConfirmouCliente'',''Conhece'',''DesconheceDivida'',''NaoConhece'',''NaoDesejaFatura'',
                        ''NaoQuerInformarCPF'',''VouChamar'',''DesejaAcordo'',''DesejaAcordoAVista'',''DesejaFalarAtendente'',
                        ''ErroWSAcordosPlanos'',''ErroWSBuscarTitulos'',''Falecido'',''NaoRealizouPagamento'',
                        ''PagamentoNaoAgendado'',''Parente'',''QualAssunto'',''SelecionouCanalWhatsApp'',''Aguardar'',
                        ''DesejaParcelar'',''EfetuouPagamento'',''NaoDesejaReceberOferta'',''NaoResponsavelMatricula'',
                        ''OpcaoLigacao'',''PagamentoAgendado'',''QuemFala'',''ResponsavelMatricula'',''AgendamentoNoite'',
                        ''ClienteAlegaPagamentoMenos5Dias'',''DesejaNegociarWhatsApp'',''Espera'',''NaoRecebeuFatura'',
                        ''QuestionaVencimento'',''RecusaAcordo'',''Transferida'',''AgendamentoTarde'',''ClienteAgresivo'',
                        ''ErroTransferencia'',''TerceiraRecusa''
                    ) THEN 1 ELSE 0
                END AS ALO
            ,   CASE
                    WHEN SUBSTATUSURA IN (
                        ''ClienteAlegaPagamentoMais5Dias'',''NaoEfetuouPagamentoMais5Dias'',''QuestionaValor'',
                        ''CPFValidadoBase'',''DesejaBoletoWhatsApp'',''ErroWSDividas'',''SegundaRecusa'',''AlegaPagamento'',
                        ''ClienteDesejaFatura'',''DificuldadeFinanceira'',''EfetuouPagamentoMais5Dias'',
                        ''NaoDesejaAcordo'',''PrimeiraRecusa'',''ConfirmouAcordo'',''ConfirmouCliente'',
                        ''DesconheceDivida'',''NaoDesejaFatura'',''DesejaAcordo'',''DesejaAcordoAVista'',
                        ''ErroWSAcordosPlanos'',''NaoRealizouPagamento'',''PagamentoNaoAgendado'',
                        ''DesejaParcelar'',''EfetuouPagamento'',''NaoDesejaReceberOferta'',
                        ''PagamentoAgendado'',''ResponsavelMatricula'',''ClienteAlegaPagamentoMenos5Dias'',
                        ''DesejaNegociarWhatsApp'',''NaoRecebeuFatura'',''QuestionaVencimento'',''RecusaAcordo'',
                        ''ClienteAgresivo'',''TerceiraRecusa''
                    ) THEN 1 ELSE 0
                END AS CPC
            ,   CASE
                    WHEN SUBSTATUSURA IN (
                        ''NaoEfetuouPagamentoMais5Dias'',''QuestionaValor'',''DesejaBoletoWhatsApp'',''ErroWSDividas'',
                        ''SegundaRecusa'',''ClienteDesejaFatura'',''DificuldadeFinanceira'',''NaoDesejaAcordo'',''ConfirmouAcordo'',
                        ''ConfirmouCliente'',''NaoDesejaFatura'',''DesejaAcordo'',''ErroWSAcordosPlanos'',''NaoRealizouPagamento'',
                        ''PagamentoNaoAgendado'',''DesejaParcelar'',''PagamentoAgendado'',''ResponsavelMatricula'',''DesejaNegociarWhatsApp'',
                        ''NaoRecebeuFatura'',''QuestionaVencimento'',''RecusaAcordo'',''TerceiraRecusa'', ''DesejaAcordoAVista''
                    ) THEN 1 ELSE 0
                END AS CPCA
            ,   CASE
                    WHEN SUBSTATUSURA IN (
                        ''DesejaBoletoWhatsApp'',''ClienteDesejaFatura'',''ConfirmouAcordo'',
                        ''DesejaAcordo'',''DesejaAcordoAVista'',''ErroWSAcordosPlanos''
                    ) THEN 1 ELSE 0
                END AS PP
            from Analitico_TRC
            where datahoraligacao >= ''{data_inicio}'' 
              and datahoraligacao < ''{data_fim}''
        )a
        GROUP BY
            DATA
        ,   CPF
        ,   SUBSTATUSURA
        ORDER BY
            DATA
    '
    )
    """
    return query

def executar_carga_incremental(conn_trc):
    """
    Executa a carga incremental:
    1. Consulta a última data na tabela
    2. Define D-1 (ontem) como data alvo
    3. Processa TODOS os dias faltantes até D-1
    """
    try:
        # Consulta a última data
        max_data = get_max_date(conn_trc)
        print(f"Última data na tabela: {max_data}")
        
        # Define a data alvo como ONTEM (D-1)
        hoje = datetime.now().date()
        data_alvo = hoje - timedelta(days=1)
        print(f"Data alvo (D-1): {data_alvo}")
        
        # Se tabela vazia, define data inicial manualmente
        if max_data is None:
            print("⚠ Tabela vazia. Defina uma data inicial manualmente.")
            return
        
        # Converte max_data para date
        max_data = pd.to_datetime(max_data).date()
        
        # Calcula a próxima data a ser inserida (dia seguinte ao max_data)
        proxima_data = max_data + timedelta(days=1)
        
        # Verifica se já está atualizado
        if proxima_data > data_alvo:
            print(f"✓ Banco está atualizado! Última data ({max_data}) já contempla D-1 ({data_alvo})")
            print(f"Nenhuma inserção necessária.")
            return
        
        # Calcula quantos dias faltam
        dias_faltantes = (data_alvo - max_data).days
        print(f"\n⚠ Faltam {dias_faltantes} dia(s) para atualizar até D-1")
        print(f"Processando de {proxima_data} até {data_alvo}...\n")
        
        # Loop para processar cada dia faltante
        data_atual = proxima_data
        total_linhas = 0
        dias_processados = 0
        
        while data_atual <= data_alvo:
            print(f"▶ Processando data: {data_atual}")
            
            # Gera a query de INSERT
            query_insert = get_insert_query(data_atual)
            
            # Executa o INSERT
            cursor = conn_trc.cursor()
            cursor.execute(query_insert)
            conn_trc.commit()
            
            linhas_inseridas = cursor.rowcount
            total_linhas += linhas_inseridas
            dias_processados += 1
            
            print(f"  ✓ {linhas_inseridas} linhas inseridas")
            
            cursor.close()
            
            # Avança para o próximo dia
            data_atual += timedelta(days=1)
        
        print(f"\n{'='*60}")
        print(f"✓ CARGA COMPLETA!")
        print(f"  - Dias processados: {dias_processados}")
        print(f"  - Total de linhas inseridas: {total_linhas}")
        print(f"  - Período: {proxima_data} até {data_alvo}")
        print(f"{'='*60}")
        
    except Exception as e:
        print(f"\n✗ Erro durante a execução: {str(e)}")
        conn_trc.rollback()
        raise

# Uso exemplo:
executar_carga_incremental(conn_trc)

C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_38420\2982439586.py:361: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conn_trc)

Última data na tabela: 2025-11-29
Data alvo (D-1): 2025-12-01

⚠ Faltam 2 dia(s) para atualizar até D-1
Processando de 2025-11-30 até 2025-12-01...

▶ Processando data: 2025-11-30
  ✓ 0 linhas inseridas
▶ Processando data: 2025-12-01
  ✓ 98030 linhas inseridas

============================================================
✓ CARGA COMPLETA!
  - Dias processados: 2
  - Total de linhas inseridas: 98030
  - Período: 2025-11-30 até 2025-12-01
============================================================

In [55]:

caminho_csv = r"\\trc-dc-ad\Planejamento\MIS\CARTEIRAS\WILLBANK\Automations\base_tempos.csv"
def obter_ultima_data_arquivo(caminho_csv):
    """
    Lê o arquivo CSV e retorna a última data de atendimento.
    """
    try:
        # Ler CSV
        df = pd.read_csv(caminho_csv, encoding='utf-8-sig', sep=';')
        
        # Normalizar nomes de colunas (remover espaços)
        df.columns = df.columns.str.strip()
        
        if 'data_insert' not in df.columns:
            raise ValueError("Coluna 'data_insert' não encontrada no arquivo")
        
        # Remover espaços e caracteres estranhos da coluna
        df['data_insert'] = df['data_insert'].astype(str).str.strip()
        
        # Converter para datetime
        df['data_insert'] = pd.to_datetime(
            df['data_insert'].str.strip(),
            format='%d/%m/%Y',   # força o formato brasileiro
            errors='coerce'
        )

        print(df['data_insert'].sort_values().tail(10))
        
        # Verificar se alguma data foi convertida
        if df['data_insert'].isna().all():
            raise ValueError("Nenhuma data válida encontrada. Verifique o formato no CSV.")
        
        # Obter a última data válida
        ultima_data = df['data_insert'].max()
        
        print(f"Última data encontrada no arquivo: {ultima_data.strftime('%d/%m/%Y')}")
        return ultima_data
    
    except Exception as e:
        print(f"Erro ao ler arquivo: {str(e)}")
        import traceback
        traceback.print_exc()
        raise

data = obter_ultima_data_arquivo(caminho_csv)
data

751   2025-12-03
741   2025-12-03
743   2025-12-03
744   2025-12-03
746   2025-12-03
747   2025-12-03
748   2025-12-03
749   2025-12-03
742   2025-12-03
769   2025-12-03
Name: data_insert, dtype: datetime64[ns]
Última data encontrada no arquivo: 03/12/2025

Timestamp('2025-12-03 00:00:00')

In [54]:
caminho_csv = r"\\trc-dc-ad\Planejamento\MIS\CARTEIRAS\WILLBANK\Automations\base_tempos.csv"
df = pd.read_csv(caminho_csv, encoding='utf-8-sig', sep=';')
        
# Normalizar nomes de colunas (remover espaços)
df.columns = df.columns.str.strip()

if 'data_insert' not in df.columns: 
    raise ValueError("Coluna 'data_insert' não encontrada no arquivo")

# Remover espaços e caracteres estranhos da coluna
df['data_insert'] = df['data_insert'].astype(str).str.strip()

# Converter para datetime
df['data_insert'] = pd.to_datetime(
    df['data_insert'].str.strip(),
    format='%d/%m/%Y',   # força o formato brasileiro
    errors='coerce'
)

print(df['data_insert'].sort_values().tail(10))
print(df['data_insert'].unique())
print(df.loc[620:630, 'data_insert'])

683   2025-12-01
682   2025-12-01
681   2025-12-01
680   2025-12-01
679   2025-12-01
678   2025-12-01
676   2025-12-01
704   2025-12-01
689   2025-12-01
705   2025-12-01
Name: data_insert, dtype: datetime64[ns]
<DatetimeArray>
['2025-11-01 00:00:00', '2025-11-03 00:00:00', '2025-11-04 00:00:00',
 '2025-11-05 00:00:00', '2025-11-06 00:00:00', '2025-11-07 00:00:00',
 '2025-11-08 00:00:00', '2025-11-10 00:00:00', '2025-11-11 00:00:00',
 '2025-11-12 00:00:00', '2025-11-13 00:00:00', '2025-11-14 00:00:00',
 '2025-11-17 00:00:00', '2025-11-18 00:00:00', '2025-11-19 00:00:00',
 '2025-11-21 00:00:00', '2025-11-22 00:00:00', '2025-11-24 00:00:00',
 '2025-11-25 00:00:00', '2025-11-26 00:00:00', '2025-11-27 00:00:00',
 '2025-11-28 00:00:00', '2025-11-29 00:00:00', '2025-12-01 00:00:00']
Length: 24, dtype: datetime64[ns]
620   2025-11-27
621   2025-11-27
622   2025-11-27
623   2025-11-27
624   2025-11-27
625   2025-11-27
626   2025-11-27
627   2025-11-27
628   2025-11-27
629   2025-11-27
630   2025-11-27
Name: data_insert, dtype: datetime64[ns]

In [27]:
# ...existing code...
caminho_csv = r"\\trc-dc-ad\Planejamento\MIS\CARTEIRAS\WILLBANK\Automations\base_tempos.csv"
def obter_ultima_data_arquivo(caminho_csv):
    """
    Lê o CSV e retorna a MAIOR data encontrada na coluna de data.
    Detecta 'data_insert' ou 'data_atendimento' ou usa a primeira coluna.
    Remove linhas de header acidental e valores inválidos antes de calcular o max.
    """
    try:
        # Ler tudo como string para evitar inferências estranhas
        df = pd.read_csv(caminho_csv, encoding='utf-8-sig', sep=';', dtype=str, keep_default_na=False)
        df.columns = df.columns.str.strip()
        if df.shape[0] == 0:
            raise ValueError("Arquivo vazio")

        # escolher coluna de data: preferir data_insert, depois data_atendimento, senão primeira coluna
        if 'data_insert' in df.columns:
            date_col = 'data_insert'
        elif 'data_atendimento' in df.columns:
            date_col = 'data_atendimento'
        else:
            date_col = df.columns[0]

        s = df[date_col].astype(str).str.strip()

        # remover linhas que sejam exatamente o nome da coluna (header inserido) ou vazias
        mask_header_like = s.str.lower() == date_col.lower()
        mask_empty = s == '' 
        s_clean = s[~(mask_header_like | mask_empty)].copy()

        # converter com heurística (dayfirst True para formatos DD/MM/YYYY) e inferência
        s_dt = pd.to_datetime(s_clean, dayfirst=True, infer_datetime_format=True, errors='coerce')

        # relatório mínimo (útil para debug)
        n_total = len(s)
        n_valid = s_dt.notna().sum()
        n_invalid = n_total - n_valid
        print(f"Coluna detectada: '{date_col}' — total:{n_total} válidas:{n_valid} inválidas:{n_invalid}")

        if s_dt.notna().sum() == 0:
            raise ValueError("Nenhuma data válida encontrada após limpeza. Verifique formatos ou linhas de header no CSV.")

        ultima_data = s_dt.max()
        print(f"Última data encontrada no arquivo: {ultima_data.strftime('%d/%m/%Y')}")
        return ultima_data

    except FileNotFoundError:
        print(f"Arquivo não encontrado: {caminho_csv}")
        raise
    except Exception as e:
        print(f"Erro ao obter última data: {e}")
        import traceback
        traceback.print_exc()
        raise

# ...existing code...

def obter_ultima_data_arquivo(caminho_csv):
    """
    Lê o CSV e retorna a MAIOR data encontrada na coluna de data.
    - detecta 'data_insert' ou 'data_atendimento' ou usa a primeira coluna
    - lê tudo como string, limpa ruídos (quotes, prefixes tipo b'...', headers inseridos),
      tenta parse em vários formatos e retorna o max válido.
    """
    import re

    try:
        # Ler como string para evitar coerções estranhas
        df = pd.read_csv(caminho_csv, encoding='utf-8-sig', sep=';', dtype=str, keep_default_na=False)
        df.columns = df.columns.str.strip()

        if df.shape[0] == 0:
            raise ValueError("Arquivo vazio")

        # escolher coluna de data
        if 'data_insert' in df.columns:
            col = 'data_insert'
        elif 'data_atendimento' in df.columns:
            col = 'data_atendimento'
        else:
            col = df.columns[0]

        s = df[col].astype(str).str.strip()

        # remover linhas que são header inserido ou claramente vazias
        mask_header = s.str.lower() == col.lower()
        mask_empty = s == '' 
        s = s[~(mask_header | mask_empty)].copy()

        if s.empty:
            raise ValueError("Nenhum valor não-vazio encontrado na coluna de datas")

        # limpeza básica: remover quotes, prefixes b'...', controle de caracteres estranhos
        s = s.str.replace(r"^b['\"]", "", regex=True).str.replace(r"['\"]$", "", regex=True)
        s = s.str.replace(r"[^\d\-/:\s]", "", regex=True).str.strip()

        # Tentar converter diretamente (vários formatos suportados)
        dt = pd.to_datetime(s, dayfirst=True, infer_datetime_format=True, errors='coerce')

        # Se muitos NaT, tentar extrair padrões comuns (YYYY-MM-DD HH:MM:SS ou DD/MM/YYYY)
        if dt.isna().sum() > 0:
            def extract_best(x):
                if pd.isna(x):
                    return x
                txt = str(x)
                # padrões possíveis
                m = re.search(r"(\d{4}-\d{2}-\d{2}\s+\d{2}:\d{2}:\d{2})", txt)
                if m:
                    return m.group(1)
                m = re.search(r"(\d{4}-\d{2}-\d{2})", txt)
                if m:
                    return m.group(1)
                m = re.search(r"(\d{2}/\d{2}/\d{4})", txt)
                if m:
                    return m.group(1)
                return txt

            s2 = s.map(extract_best)
            dt2 = pd.to_datetime(s2, dayfirst=True, infer_datetime_format=True, errors='coerce')
            # combinar: preferir dt2 quando dt for NaT
            dt = dt.fillna(dt2)

        n_total = len(s)
        n_valid = dt.notna().sum()
        n_invalid = n_total - n_valid
        print(f"Coluna detectada: '{col}' — total:{n_total} válidas:{n_valid} inválidas:{n_invalid}")

        if n_valid == 0:
            raise ValueError("Nenhuma data válida encontrada após limpeza. Verifique o conteúdo do CSV.")

        ultima = dt.max()
        print(f"Última data encontrada no arquivo: {ultima.strftime('%d/%m/%Y')}")
        return ultima

    except FileNotFoundError:
        print(f"Arquivo não encontrado: {caminho_csv}")
        raise
    except Exception as e:
        print(f"Erro ao obter última data: {e}")
        import traceback
        traceback.print_exc()
        raise

# ...existing code...

def obter_ultima_data_arquivo(caminho_csv):
    """
    Lê o arquivo CSV e retorna a última data de atendimento.
    
    Parâmetros:
    -----------
    caminho_csv : str
        Caminho do arquivo CSV
    
    Retorna:
    --------
    datetime : Última data encontrada no arquivo
    """
    try:
        # Ler CSV com delimitador ponto e vírgula
        df = pd.read_csv(caminho_csv, encoding='utf-8-sig', sep=';')
        
        # Verificar se a coluna existe
        print(f"Colunas encontradas no arquivo ({len(df.columns)} colunas):")
        print(list(df.columns)[:10])  # Mostrar apenas as 10 primeiras
        
        if 'data_atendimento' not in df.columns:
            raise ValueError("Coluna 'data_atendimento' não encontrada no arquivo")
        
        # Mostrar exemplo de como a data está no arquivo
        print(f"Exemplo de data no arquivo: {df['data_atendimento'].iloc[0]}")
        
        # Tentar converter para datetime com dayfirst=True (formato brasileiro)
        df['data_atendimento'] = pd.to_datetime(df['data_atendimento'], dayfirst=True, errors='coerce')
        
        # Verificar se conseguiu converter
        if df['data_atendimento'].isna().all():
            raise ValueError("Não foi possível converter nenhuma data. Verifique o formato das datas no arquivo.")
        
        # Obter a última data
        ultima_data = df['data_atendimento'].max()
        
        # Verificar se a última data é válida
        if pd.isna(ultima_data):
            raise ValueError("Última data é inválida (NaT)")
        
        print(f"Última data encontrada no arquivo: {ultima_data.strftime('%d/%m/%Y')}")
        
        return ultima_data
        
    except Exception as e:
        print(f"Erro ao ler arquivo: {str(e)}")
        import traceback
        traceback.print_exc()
        raise

ultima_data = obter_ultima_data_arquivo(caminho_csv)
ultima_data
# ...existing code...

Colunas encontradas no arquivo (34 colunas):
['data_insert', 'hora_insert', 'id_agente', 'nome_agente', 'cpf_agente', 'nome_supervisor', 'coluna_fixa', 'data_atendimento', 'tempo_logado', 'hora_login']
Exemplo de data no arquivo: 01/11/2025
Última data encontrada no arquivo: 26/11/2025

Timestamp('2025-11-26 00:00:00')