In [ ]:
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> GERAR DADOS

# import importlib
# importlib.reload(queries)

from src.db_connection import get_connection
from queries import get_query_discagens, get_query_cad_devf, get_query_mailing_hist, get_query_discagens_trestto, get_query_tabulacao_aciona, get_query_base_acionamentos
import pandas as pd

conn_src = get_connection("SERVER_SRC", "DATABASE_SRC")
# Tudo em uma linha
df_discagens_expert = pd.read_sql(
    get_query_discagens('2025-09-01', '2025-09-30'), 
    conn_src
)
df_cad_devf = pd.read_sql(
    get_query_cad_devf(), 
    conn_src
)

conn_bd2 = get_connection("SERVER_BD2", "DATABASE_BD2")
df_maling_hist = pd.read_sql(
    get_query_mailing_hist('2025-09-01', '2025-09-30'), 
    conn_bd2
)

conn_trc = get_connection("SERVER_BD2", "DATABASE_TRC")
df_discagens_trestto = pd.read_sql(
    get_query_discagens_trestto('2025-09-01', '2025-09-30'), 
    conn_trc
)
df_tabualacao_aciona = pd.read_sql(
    get_query_tabulacao_aciona(), 
    conn_bd2
)

df_tab_acionamentos = pd.read_sql(
    get_query_base_acionamentos('2025-09-01', '2025-09-30'), 
    conn_src
)

C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_6164\2995825967.py:12: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_discagens_expert = pd.read_sql(
C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_6164\2995825967.py:16: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_cad_devf = pd.read_sql(
C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_6164\2995825967.py:22: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_maling_hist = pd.read_sql(
C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_6164\2995825967.py:28: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_discagens_trestto = pd.read_sql(
C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_6164\2995825967.py:32: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df_tabualacao_aciona = pd.read_sql(

In [ ]:
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> TRATAMENTO DOS DADOS
from src.data_wrangling_discagens_expert import tratar_base_discagens
from src.data_wrangling_mailingHist import tratar_base_mailing_hist
from src.data_wrangling_discagens_trestto import tratar_discagens_trestto
from src.data_wrangling_acionamentos import tratar_acionamentos

# Aplicar tratamento
# SEGMENTAÇÃO TIPO DE OPERAÇÃO, ADICIONAR DDD
df_discagens_expert = tratar_base_discagens(df_discagens_expert)
# ADICIONAR PRODUTO, FAIXA DE ATRASO E VALOR PRINCIPAL
df_maling_hist = tratar_base_mailing_hist(df_maling_hist, df_cad_devf)
# DATA FRAMES ESFORÇO, ÚNICOS TRATADOS, COM BASE NA MAILING HIST
df_trestto_esforco, df_trestto_unique = tratar_discagens_trestto(
    df_discagens_trestto, 
    df_maling_hist
)
# CONVERTE VALORES DE DISCAGENS PARA INT
df_tabualacao_aciona = tratar_acionamentos(df_tabualacao_aciona)
#df_mailing_hist_cruz = tratar_base_discagens(df_maling_hist)

print(f"✓ Esforço diário: {len(df_trestto_esforco)} dias")
print(df_trestto_esforco.head())

print(f"\n✓ Únicos diário: {len(df_trestto_unique)} dias")
print(df_trestto_unique.head())

📊 Antes da consolidação - Trestto: 2,762,568
📊 Após consolidação - Trestto: 2,648,475
📊 Mailing: 6,255,364
📊 Após join: 1,099,803

c:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\src\data_wrangling_discagens_trestto.py:39: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_esforco = df_join.groupby(['DATA', 'PRODUTO', 'FX_ATRASO'], as_index=False)[colunas_metricas].sum()
c:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\src\data_wrangling_discagens_trestto.py:49: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_unique = df_unique.groupby(['DATA', 'PRODUTO', 'FX_ATRASO'], as_index=False)[colunas_metricas].sum()

📊 Antes da consolidação - Trestto: 2,762,568
📊 Após consolidação - Trestto: 2,648,475
📊 Mailing: 6,255,364
📊 Após join: 1,099,803

c:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\src\data_wrangling_discagens_trestto.py:39: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_esforco = df_join.groupby(['DATA', 'PRODUTO', 'FX_ATRASO'], as_index=False)[colunas_metricas].sum()
c:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\Ouze\src\data_wrangling_discagens_trestto.py:49: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_unique = df_unique.groupby(['DATA', 'PRODUTO', 'FX_ATRASO'], as_index=False)[colunas_metricas].sum()

✓ Esforço diário: 750 dias
         DATA PRODUTO FX_ATRASO  DISCAGEM   ALO  CPC  CPCA  PROMESSA
0  2025-09-01     API   Menor 0         0     0    0     0         0
1  2025-09-01     API      0-30    105370  3337  526   322       186
2  2025-09-01     API     31-60     24001   461   42    27        12
3  2025-09-01     API     61-90         0     0    0     0         0
4  2025-09-01     API    91-120     19075   343   33    17        12

✓ Únicos diário: 750 dias
         DATA PRODUTO FX_ATRASO  DISCAGEM   ALO  CPC  CPCA  PROMESSA
0  2025-09-01     API   Menor 0         0     0    0     0         0
1  2025-09-01     API      0-30     29489  2645  505   312       186
2  2025-09-01     API     31-60      7385   376   42    27        12
3  2025-09-01     API     61-90         0     0    0     0         0
4  2025-09-01     API    91-120      7147   299   33    17        12

In [150]:
#df_maling_hist.head()
#df_cad_devf.head()
df_discagens_expert
#df_tabualacao_aciona
#df_discagens_trestto
#df_trestto_esforco

,DATA,id,CONTRATO,CPF,ddd,fone,GrupoPrincipal,UltCodSigRecPublica,ResultadoClassificacao,MotivoEncerramentoBilhete,Instante200OKPub,Agente,tempoconversacao_ms,OPERACAO,ESTADO,ORIGEM
0,2025-09-01,66,48941489id,43640864000180,27,998267780,4047,480,,foneforadeservico,1899-12-30 00:00:00,,0,URA CPC,ES,Humano
1,2025-09-01,149,49012660id,57722707000129,11,945760003,4636,480,,foneforadeservico,1899-12-30 00:00:00,,0,AGV NEGOCIADORA,SP,Robô
2,2025-09-01,196,47525229id,55280229000119,12,996448349,4636,404,,foneinexistente,1899-12-30 00:00:00,,0,AGV NEGOCIADORA,SP,Robô
3,2025-09-01,203,42643945id,54542547000148,45,999946130,4636,404,,foneinexistente,1899-12-30 00:00:00,,0,AGV NEGOCIADORA,PR,Robô
4,2025-09-01,220,41849079id,53330359000193,62,999623988,4047,200,cxpre,bloqueiodetector,2025-09-01 08:00:09,,0,URA CPC,GO,Humano
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2800037,2025-09-30,56654929,,,49,984070692,4309,,,abandonomfila,2025-09-30 18:41:40,,0,Outros,SC,Humano
2800038,2025-09-30,56672110,,,65,984312673,4309,,,abandonomfila,2025-09-30 18:49:59,,0,Outros,MT,Humano
2800039,2025-09-30,56676841,,,11,964523094,4309,,,abandonomfila,2025-09-30 18:53:57,,0,Outros,SP,Humano
2800040,2025-09-30,56806323,,,11,946246558,4017,,,abandonomfila,2025-09-30 20:32:29,,0,RECEPTIVO,SP,Humano
2800041,2025-09-30,56806324,,,11,946246558,4017,,,abandonomfila,2025-09-30 20:33:51,,0,RECEPTIVO,SP,Humano

In [ ]:
# VERIFICAR CONFLITOS DE FAIXA DE ATRASO POR CONTRATO E DATA NA BASE MAILING HIST
duplicados_por_data = df_maling_hist.duplicated(subset=['CONTRATO', 'DATA'], keep=False)
df_cpfs_duplicados = df_maling_hist[duplicados_por_data]
# Conta quantas faixas de atraso diferentes existem por CPF e DATA
faixa_por_cpf_data = df_maling_hist.groupby(['CONTRATO', 'DATA'])['FX_ATRASO'].nunique()

# Filtra os casos com mais de uma faixa
cpf_data_conflito = faixa_por_cpf_data[faixa_por_cpf_data > 1].reset_index()
df_conflito_faixa = df_maling_hist.merge(cpf_data_conflito, on=['CONTRATO', 'DATA'], how='inner')
df_conflito_faixa

Empty DataFrame
Columns: [DATA, CONTRATO, CPF, ATRASO, COD_CLI, COD_CAR, PRODUTO, FX_ATRASO_x, VALORPRIN_FIN, FX_ATRASO_y]
Index: []

In [ ]:
# ENRIQUECER BASE DE ACIONAMENTOS COM INFORMAÇÕES DA TABULAÇÃO
df_tab_acionamentos['COD_ACIONAMENTO'] = df_tab_acionamentos['COD_ACIONAMENTO'].astype(str)
df_tabualacao_aciona['COD_ACIONA'] = df_tabualacao_aciona['COD_ACIONA'].astype(str)

# Agora fazer o merge
df_tab_acionamentos_tabulados = df_tab_acionamentos.merge(
    df_tabualacao_aciona[['COD_ACIONA', 'DESC_ACIONA', 'CPC', 'CPCA', 'PROMESSA']],
    left_on='COD_ACIONAMENTO',
    right_on='COD_ACIONA',
    how='left'
).drop('COD_ACIONA', axis=1)

# Converter múltiplas colunas de uma vez
colunas_para_int = ['CPC', 'CPCA', 'PROMESSA']
df_tab_acionamentos_tabulados[colunas_para_int] = df_tab_acionamentos_tabulados[colunas_para_int].fillna(0).astype(int)
df_tab_acionamentos_tabulados['ACIONAMENTOS'] = 1
df_tab_acionamentos_tabulados.head()

,DATA_ACIONA,CONTRATO_FIN,CPF_DEV,COD_ACIONAMENTO,DESC_ACIONA,CPC,CPCA,PROMESSA
0,2025-09-16,22165236ID,16719439707,9000,EM NEGOCIAÇÃO WHATSAPP,1,1,0
1,2025-09-10,29256345ID,39962927000148,8820,ATENDE E DESLIGA - GETNET,0,0,0
2,2025-09-12,29256345ID,39962927000148,8820,ATENDE E DESLIGA - GETNET,0,0,0
3,2025-09-30,29258817ID,16987214000133,7077,ENVIO DE SMS - GETNET,0,0,0
4,2025-09-30,29261083ID,23986881000167,7077,ENVIO DE SMS - GETNET,0,0,0

In [ ]:
# ENRIQUECER BASE DE ACIONAMENTOS COM INFORMAÇÕES DA MAILING HIST
# df_tab_acionamentos_tabulados
# df_maling_hist
df_mailing_temp = df_maling_hist.rename(columns={
    'CONTRATO': 'CONTRATO_FIN',
    'DATA': 'DATA_ACIONA'
})
# Merge mantendo todas as colunas do df de acionamentos e adicionando fx_atraso e valorprin_fin
df_acionamentos_segmentados = df_tab_acionamentos_tabulados.merge(
    df_mailing_temp[['CONTRATO_FIN', 'DATA_ACIONA', 'FX_ATRASO', 'VALORPRIN_FIN']],
    on=['CONTRATO_FIN', 'DATA_ACIONA'],
    how='left'
)
df_acionamentos_segmentados

In [151]:
df_acionamentos_segmentados

,DATA_ACIONA,CONTRATO_FIN,CPF_DEV,COD_ACIONAMENTO,DESC_ACIONA,CPC,CPCA,PROMESSA,ACIONAMENTOS,FX_ATRASO,VALORPRIN_FIN
0,2025-09-16,22165236ID,16719439707,9000,EM NEGOCIAÇÃO WHATSAPP,1,1,0,1,NaN,NaN
1,2025-09-10,29256345ID,39962927000148,8820,ATENDE E DESLIGA - GETNET,0,0,0,1,361-720,577.46
2,2025-09-12,29256345ID,39962927000148,8820,ATENDE E DESLIGA - GETNET,0,0,0,1,361-720,577.46
3,2025-09-30,29258817ID,16987214000133,7077,ENVIO DE SMS - GETNET,0,0,0,1,361-720,905.03
4,2025-09-30,29261083ID,23986881000167,7077,ENVIO DE SMS - GETNET,0,0,0,1,Maior 720,890.37
...,...,...,...,...,...,...,...,...,...,...,...
8620,2025-09-29,53500195ID,7676165000127,8745,INFORMA ENTREGA NOS CORREIOS - GETNET,1,0,0,1,0-30,639.30
8621,2025-09-26,53500197ID,32788914000155,7021,PROMESSA DE PAGAMENTO - GETNET,1,1,1,1,0-30,22.18
8622,2025-09-29,53534574ID,40279030000101,9606,CLIENTE SOLICITA DEVOLVER EQUIPAMENTO - GETNET,1,1,0,1,NaN,NaN
8623,2025-09-29,53534585ID,72220916000168,8914,DESCONHECE DÍVIDA EQUIPAMENTO - GETNET,1,0,0,1,NaN,NaN
8624,2025-09-30,53534605ID,13690577000114,9606,CLIENTE SOLICITA DEVOLVER EQUIPAMENTO - GETNET,1,1,0,1,31-60,639.30

In [159]:
#df_acionamentos_segmentados
print(f"📊 Antes do join - discagens expert: {len(df_discagens_expert):,} | acionamentos: {len(df_acionamentos_segmentados):,}")

df_acionamentos_segmentados['CONTRATO_FIN'] = df_acionamentos_segmentados['CONTRATO_FIN'].astype(str).str.upper()
df_discagens_expert['CONTRATO'] = df_discagens_expert['CONTRATO'].astype(str).str.upper()
df_acionamentos_segmentados['DATA_ACIONA'] = pd.to_datetime(df_acionamentos_segmentados['DATA_ACIONA'])
df_discagens_expert['DATA'] = pd.to_datetime(df_discagens_expert['DATA'])

df_discagens_temp = df_discagens_expert.rename(columns={
    'CONTRATO': 'CONTRATO_FIN',
    'DATA': 'DATA_ACIONA'
})
df_acionamentos_segmentado_ = df_acionamentos_segmentados.merge(
    df_discagens_temp[['CONTRATO_FIN', 'DATA_ACIONA', 'ESTADO', 'ORIGEM']],
    on=['CONTRATO_FIN', 'DATA_ACIONA'],
    how='left'
)

df_acionamentos_segmentado_

📊 Antes do join - discagens expert: 2,800,042 | acionamentos: 8,625

,DATA_ACIONA,CONTRATO_FIN,CPF_DEV,COD_ACIONAMENTO,DESC_ACIONA,CPC,CPCA,PROMESSA,ACIONAMENTOS,FX_ATRASO,VALORPRIN_FIN,ESTADO,ORIGEM
0,2025-09-16,22165236ID,16719439707,9000,EM NEGOCIAÇÃO WHATSAPP,1,1,0,1,NaN,NaN,NaN,NaN
1,2025-09-10,29256345ID,39962927000148,8820,ATENDE E DESLIGA - GETNET,0,0,0,1,361-720,577.46,NaN,NaN
2,2025-09-12,29256345ID,39962927000148,8820,ATENDE E DESLIGA - GETNET,0,0,0,1,361-720,577.46,NaN,NaN
3,2025-09-30,29258817ID,16987214000133,7077,ENVIO DE SMS - GETNET,0,0,0,1,361-720,905.03,NaN,NaN
4,2025-09-30,29261083ID,23986881000167,7077,ENVIO DE SMS - GETNET,0,0,0,1,Maior 720,890.37,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8620,2025-09-29,53500195ID,7676165000127,8745,INFORMA ENTREGA NOS CORREIOS - GETNET,1,0,0,1,0-30,639.30,NaN,NaN
8621,2025-09-26,53500197ID,32788914000155,7021,PROMESSA DE PAGAMENTO - GETNET,1,1,1,1,0-30,22.18,NaN,NaN
8622,2025-09-29,53534574ID,40279030000101,9606,CLIENTE SOLICITA DEVOLVER EQUIPAMENTO - GETNET,1,1,0,1,NaN,NaN,NaN,NaN
8623,2025-09-29,53534585ID,72220916000168,8914,DESCONHECE DÍVIDA EQUIPAMENTO - GETNET,1,0,0,1,NaN,NaN,NaN,NaN
8624,2025-09-30,53534605ID,13690577000114,9606,CLIENTE SOLICITA DEVOLVER EQUIPAMENTO - GETNET,1,1,0,1,31-60,639.30,NaN,NaN

In [158]:
df_humano = df_acionamentos_segmentado_[df_acionamentos_segmentado_['ORIGEM'].str.upper() == 'HUMANO']
df_humano

Empty DataFrame
Columns: [DATA_ACIONA, CONTRATO_FIN, CPF_DEV, COD_ACIONAMENTO, DESC_ACIONA, CPC, CPCA, PROMESSA, ACIONAMENTOS, FX_ATRASO, VALORPRIN_FIN, ESTADO, ORIGEM]
Index: []

In [ ]:
# # ACIONAMENTOS DUPLICADOS
df_acionamentos_score = df_acionamentos_segmentados.copy()

# Criar coluna de score
df_acionamentos_score['TABULACAO_SCORE'] = (
    df_acionamentos_score['PROMESSA'].astype(int) * 3 +
    df_acionamentos_score['CPCA'].astype(int) * 2 +
    df_acionamentos_score['CPC'].astype(int) * 1
)

# Identificar CPF + DATA com mais de um score
cpf_data_score_counts = df_acionamentos_score.groupby(['CONTRATO_FIN', 'DATA_ACIONA'])['TABULACAO_SCORE'].nunique()

# Filtrar os casos com mais de um score (duplicidade com variação)
cpf_data_com_conflito = cpf_data_score_counts[cpf_data_score_counts > 1].reset_index()

# Remover a coluna de score para evitar duplicação no merge
cpf_data_com_conflito = cpf_data_com_conflito.drop(columns='TABULACAO_SCORE')

# Filtrar registros completos com esses casos
df_conflitos_score = df_acionamentos_score.merge(cpf_data_com_conflito, on=['CONTRATO_FIN', 'DATA_ACIONA'], how='inner')
df_conflitos_score

,DATA_ACIONA,CONTRATO_FIN,CPF_DEV,COD_ACIONAMENTO,DESC_ACIONA,CPC,CPCA,PROMESSA,ACIONAMENTOS,FX_ATRASO,VALORPRIN_FIN,TABULACAO_SCORE
0,2025-09-01,30028891ID,6234024000191,8914,DESCONHECE DÍVIDA EQUIPAMENTO - GETNET,1,0,0,1,361-720,2974.86,1
1,2025-09-01,30028891ID,6234024000191,7077,ENVIO DE SMS - GETNET,0,0,0,1,361-720,2974.86,0
2,2025-09-01,30028891ID,6234024000191,7077,ENVIO DE SMS - GETNET,0,0,0,1,361-720,2974.86,0
3,2025-09-30,30073959ID,19573766000193,7026,SEM PREVISÃO DE PAGAMENTO - GETNET,1,1,0,1,361-720,782.82,3
4,2025-09-30,30073959ID,19573766000193,7077,ENVIO DE SMS - GETNET,0,0,0,1,361-720,782.82,0
...,...,...,...,...,...,...,...,...,...,...,...,...
70,2025-09-30,50547942ID,47324525000146,7021,PROMESSA DE PAGAMENTO - GETNET,1,1,1,1,121-150,2159.45,6
71,2025-09-10,53178972ID,28896996000184,8820,ATENDE E DESLIGA - GETNET,0,0,0,1,31-60,63.92,0
72,2025-09-10,53178972ID,28896996000184,7175,ALEGA PAGAMENTO - GETNET,1,0,0,1,31-60,63.92,1
73,2025-09-18,53390137ID,58442025000125,8823,CLIENTE SE RECUSA A CONFIRMAR DADOS - GETNET,0,0,0,1,0-30,15.94,0
74,2025-09-18,53390137ID,58442025000125,8914,DESCONHECE DÍVIDA EQUIPAMENTO - GETNET,1,0,0,1,0-30,15.94,1

In [ ]:
# ACIONAMENTOS UNIQUE COM MELHOR SCORE
df_acionamentos_melhorScore = df_acionamentos_segmentados.copy()

df_acionamentos_melhorScore['TABULACAO_SCORE'] = (
    df_acionamentos_melhorScore['PROMESSA'].astype(int) * 3 +
    df_acionamentos_melhorScore['CPCA'].astype(int) * 2 +
    df_acionamentos_melhorScore['CPC'].astype(int) * 1
)

df_ordenado = df_acionamentos_melhorScore.sort_values(
    ['CONTRATO_FIN', 'DATA_ACIONA', 'TABULACAO_SCORE'],
    ascending=[True, True, False]
)
df_unique = df_ordenado.drop_duplicates(subset=['CONTRATO_FIN', 'DATA_ACIONA'])
df_acionamentos_unique = df_unique.groupby(['DATA_ACIONA','FX_ATRASO']).agg({
    'ACIONAMENTOS': 'sum',
    'CPC': 'sum',
    'CPCA': 'sum',
    'PROMESSA': 'sum',
    'VALORPRIN_FIN': 'sum',  # ou 'mean' se quiser média
}).reset_index()

df_acionamentos_unique

C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_6164\1328021878.py:15: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_acionamentos_unique = df_unique.groupby(['DATA_ACIONA','FX_ATRASO']).agg({

    DATA_ACIONA  FX_ATRASO  ACIONAMENTOS  CPC  CPCA  PROMESSA  VALORPRIN_FIN
0    2025-09-01    Menor 0             2    2     0         0         260.58
1    2025-09-01       0-30            32   17     9         4        1885.71
2    2025-09-01      31-60             4    2     1         0         117.18
3    2025-09-01      61-90             2    0     0         0        3835.80
4    2025-09-01     91-120             9    1     1         0       18682.87
..          ...        ...           ...  ...   ...       ...            ...
235  2025-09-30    121-150            27    8     6         2       14831.25
236  2025-09-30    151-180            29    7     6         3       20655.04
237  2025-09-30    181-360           233    1     1         1      238119.86
238  2025-09-30    361-720           920   12    10         2      926305.09
239  2025-09-30  Maior 720            29    0     0         0       48958.40

[240 rows x 7 columns]

In [147]:
# ACIONAMENTOS ESFORÇO
df_acionamentos_esforco = df_acionamentos_segmentados.copy()

df_acionamentos_esforco = df_acionamentos_esforco.groupby(['DATA_ACIONA','FX_ATRASO']).agg({
    'ACIONAMENTOS': 'sum',
    'CPC': 'sum',
    'CPCA': 'sum',
    'PROMESSA': 'sum',
    'VALORPRIN_FIN': 'sum',  # ou 'mean' se quiser média
}).reset_index()

df_acionamentos_esforco

C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_6164\1588866038.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_acionamentos_esforco = df_acionamentos_esforco.groupby(['DATA_ACIONA','FX_ATRASO']).agg({

    DATA_ACIONA  FX_ATRASO  ACIONAMENTOS  CPC  CPCA  PROMESSA  VALORPRIN_FIN
0    2025-09-01    Menor 0             2    2     0         0         260.58
1    2025-09-01       0-30            32   17     9         4        1885.71
2    2025-09-01      31-60             4    2     1         0         117.18
3    2025-09-01      61-90             4    0     0         0        7671.60
4    2025-09-01     91-120            17    1     1         0       37305.94
..          ...        ...           ...  ...   ...       ...            ...
235  2025-09-30    121-150            28    8     6         2       16990.70
236  2025-09-30    151-180            30    7     6         3       21495.46
237  2025-09-30    181-360           233    1     1         1      238119.86
238  2025-09-30    361-720           931   12    10         2      936734.55
239  2025-09-30  Maior 720            30    0     0         0       49834.59

[240 rows x 7 columns]

In [142]:
import os
# #df_conflitos_score
df_acionamentos_segmentados.to_csv('base_acionamento_segmentados.csv', sep=';', index=False, encoding='utf-8-sig')
os.startfile('base_acionamento_segmentados.csv')  # abre com o programa padrão

In [88]:
import os
df_tab_acionamentos_tabulados_ = df_tab_acionamentos_tabulados.copy()
#df_acionamentos_unique = df_tab_acionamentos_tabulados.drop_duplicates(subset=['CPF_DEV', 'DATA_ACIONA'])
#df_acionamentos_unique.groupby('DATA_ACIONA')[['CPC', 'CPCA', 'PROMESSA']].sum().reset_index()
df_tab_acionamentos_tabulados_['TABULACAO_SCORE'] = (
    df_tab_acionamentos_tabulados['PROMESSA'].astype(int) * 3 +
    df_tab_acionamentos_tabulados['CPCA'].astype(int) * 2 +
    df_tab_acionamentos_tabulados['CPC'].astype(int) * 1
)
df_tab_acionamentos_tabulados_
# DUPLICADOS POR CPF E DATA / GERA ARQUIVO CSV
# df_duplicados_por_data = df_tab_acionamentos_tabulados[df_tab_acionamentos_tabulados.duplicated(subset=['CPF_DEV', 'DATA_ACIONA'], keep=False)]
# df_duplicados_por_data.to_csv('acionamentos_duplicados.csv', sep=';', index=False, encoding='utf-8-sig')
# df_duplicados_por_data
df_tab_acionamentos_tabulados_.to_csv('acionamentos_duplicados.csv', sep=';', index=False, encoding='utf-8-sig')
os.startfile('acionamentos_duplicados.csv')  # abre com o programa padrão

In [ ]:
# Agrupa por CPF e conta quantos scores únicos existem
cpfs_com_scores_diferentes = df_tab_acionamentos_tabulados_.groupby(['CPF_DEV', 'DATA_ACIONA'])['TABULACAO_SCORE'].nunique()

# Filtra os CPFs que têm mais de um score
cpfs_varios_scores = cpfs_com_scores_diferentes[cpfs_com_scores_diferentes > 1].index
cpfs_varios_scores

MultiIndex([('16811048000110', 2025-09-26),
            ('19573766000193', 2025-09-30),
            ('25087538000106', 2025-09-18),
            ('28896996000184', 2025-09-10),
            ('30348498000220', 2025-09-18),
            ('3543057430    ', 2025-09-15),
            ('39807401372   ', 2025-09-16),
            ('40846877000112', 2025-09-10),
            ('41681728000103', 2025-09-16),
            ('44796651000105', 2025-09-03),
            ('46699372000159', 2025-09-27),
            ('47324525000146', 2025-09-30),
            ('48359314000101', 2025-09-30),
            ('49043633000176', 2025-09-05),
            ('49848075000116', 2025-09-27),
            ('50466629000108', 2025-09-16),
            ('50838981000119', 2025-09-16),
            ('52193823000184', 2025-09-22),
            ('54165049000123', 2025-09-09),
            ('54533210000174', 2025-09-18),
            ('54576274000152', 2025-09-16),
            ('54698250000176', 2025-09-15),
            ('55006784000157', 2025-09-16),
            ('55006784000157', 2025-09-18),
            ('55135154000182', 2025-09-19),
            ('56075016000118', 2025-09-30),
            ('56201375000174', 2025-09-09),
            ('57514920000145', 2025-09-11),
            ('58103859000106', 2025-09-30),
            ('58442025000125', 2025-09-18),
            ('58667351000130', 2025-09-09),
            ('5902072000148 ', 2025-09-15),
            ('6234024000191 ', 2025-09-01),
            ('649655000195  ', 2025-09-11),
            ('73791733753   ', 2025-09-16),
            ('9040900000137 ', 2025-09-29),
            ('981976000192  ', 2025-09-16)],
           names=['CPF_DEV', 'DATA_ACIONA'])

In [104]:
#cpfs_com_scores_diferentes
df_1 = df_tab_acionamentos_tabulados_[['CPF_DEV', 'DATA_ACIONA', 'TABULACAO_SCORE']].drop_duplicates().sort_values(['CPF_DEV', 'DATA_ACIONA'])
df_1

             CPF_DEV DATA_ACIONA  TABULACAO_SCORE
1020  10003018938     2025-09-05                0
1394  1002216885      2025-09-12                3
5911  10057534900     2025-09-12                0
2659  10058440976     2025-09-12                0
1180  10089363833     2025-09-02                0
...              ...         ...              ...
4081  99688042900     2025-09-29                1
1211  9969566709      2025-09-30                0
1007  9978423427      2025-09-12                0
1086  99864665553     2025-09-10                0
1087  99864665553     2025-09-11                0

[7796 rows x 3 columns]

In [ ]:
# duplicados_por_data = df_discagens_trestto.duplicated(subset=['CPF', 'DATA'], keep=False)# total_duplicados = duplicados_por_data.sum()

# print(f"Total de CPFs duplicados por data: {total_duplicados}")
df_trestto_esforco_menor_0 = df_trestto_esforco.groupby(['DATA', 'FX_ATRASO'])['DISCAGEM'].sum().reset_index()
df_trestto_esforco_menor_0.head()


# Seleciona as colunas desejadas
# colunas_exibir = ['DATA', 'CPF', 'DISCAGEM', 'ALO', 'CPC', 'CPCA', 'PROMESSA']

# # Filtra os registros duplicados por CPF e DATA
# duplicados = df_discagens_trestto[df_discagens_trestto.duplicated(subset=['CPF', 'DATA'], keep=False)]

# # Cria o DataFrame com as colunas desejadas
# df_duplicados = duplicados[colunas_exibir].sort_values(by=['DATA', 'CPF'])

# # Exibe os dados duplicados
# print(df_duplicados)

C:\Users\claudiano.alves\AppData\Local\Temp\ipykernel_26960\2858724473.py:5: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df_trestto_esforco_menor_0 = df_trestto_esforco.groupby(['DATA', 'FX_ATRASO'])['DISCAGEM'].sum().reset_index()

         DATA FX_ATRASO  DISCAGEM
0  2025-09-01   Menor 0         0
1  2025-09-01      0-30    105370
2  2025-09-01     31-60     24001
3  2025-09-01     61-90         0
4  2025-09-01    91-120     19075

In [50]:
from src.data_wrangling_mailingHist import tratar_base_mailing_hist, adicionar_valor_principal
#df_cad_devf.head()
#df_cad_devf_ativo = df_cad_devf[df_cad_devf['STATCONT_FIN'] == 0]
df_mailing_hist_valor = adicionar_valor_principal(df_maling_hist, df_cad_devf)
#df_cad_devf_ativo.head()
df_mailing_hist_valor.head()

📊 Antes do join - Mailing: 6,255,364 | CAD_DEVF: 2,996,445
📊 Após join: 6,255,364
📊 Contratos com valor: 6,248,734
📊 Contratos sem valor: 6,630

,DATA,CONTRATO,CPF,ATRASO,COD_CLI,COD_CAR,PRODUTO,FX_ATRASO,VALORPRIN_FIN
0,2025-09-01,41976615ID,11197448730,452,228,2,API,361-720,461.79
1,2025-09-01,37087148ID,372010000158,205,228,2,API,181-360,59.80
2,2025-09-01,48331916ID,717568000128,24,228,2,API,0-30,29.90
3,2025-09-01,30033123ID,1853892000136,200,228,2,API,181-360,443.80
4,2025-09-01,52227058ID,1467973000106,53,228,2,API,31-60,79.90

In [34]:
df_sem_valorprin = df_maling_hist[df_maling_hist['VALORPRIN_FIN'].isna()]
df_sem_valorprin.head()

,DATA,CONTRATO,CPF,ATRASO,COD_CLI,COD_CAR,PRODUTO,FX_ATRASO,VALORPRIN_FIN
7064,2025-09-01,48278427ID,46276884000102,237,198,1,Agenda Negativa,181-360,NaN
7772,2025-09-01,47404709ID,12124334751,251,198,1,Agenda Negativa,181-360,NaN
8451,2025-09-01,48457324ID,58273655000113,224,198,1,Agenda Negativa,181-360,NaN
8631,2025-09-01,47332694ID,55726272000165,265,198,1,Agenda Negativa,181-360,NaN
9679,2025-09-01,48745363ID,54400113000103,216,198,1,Agenda Negativa,181-360,NaN

In [ ]:
# # >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> CARREGANDO BASE DE ACIONAMENTOS <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<#
df_discagens.head()
# print(df_discagens_trestto.nunique())
# print(df_discagens_trestto.groupby('DATA')['CPF'].nunique().reset_index(name='CPFs_unicos')
# )
# print(len(df_discagens_trestto))
# print(len(df_maling_hist))
#df_maling_hist.head()
# query = f"""
#     SELECT 
# 		CAST(A.DATA_ACIONA AS DATE) DATA_ACIONA,
#         CAST(DATA_ACIONA2 AS DATE) AS DATA,
#         A.CONTRATO_FIN,
#         C.CPF_DEV,
#         B.COD_ACIONAMENTO,
#         B.DESC_ACIONAMENTO,
#         C.DTDEVOL_FIN,
#         C.VALORPRIN_FIN,
#         C.VALOR_FIN,
#         C.COD_CLI,
#         C.COD_CAR,
#         'HUMANO' TIPO,
#     FROM ACIONA D
#     LEFT JOIN CAD_ACIONAMENTO B ON A.COD_ACIONAMENTO = B.COD_ACIONAMENTO
#     WHERE CAST(DATA_ACIONA2 AS DAT4) BETWEEN '{dt_ini}' AND '{dt_fim}' AND COD_RECUP NOT IN (15721)
# """
# df_aciona = pd.read_sql(query, conn)
# df_aciona.head()

# df_aciona = pd.read_sql(f"SELECT DATA_ACIONA2 FROM ACIONA", conn)
# df_aciona.head()

,DATA,id,CONTRATO,CPF,ddd,fone,GrupoPrincipal,UltCodSigRecPublica,ResultadoClassificacao,MotivoEncerramentoBilhete,Instante200OKPub,Agente,tempoconversacao_ms,OPERACAO,ESTADO
0,2025-09-01,66,48941489id,43640864000180,27,998267780,4047,480,,foneforadeservico,1899-12-30 00:00:00,,0,URA CPC,ES
1,2025-09-01,149,49012660id,57722707000129,11,945760003,4636,480,,foneforadeservico,1899-12-30 00:00:00,,0,AGV NEGOCIADORA,SP
2,2025-09-01,196,47525229id,55280229000119,12,996448349,4636,404,,foneinexistente,1899-12-30 00:00:00,,0,AGV NEGOCIADORA,SP
3,2025-09-01,203,42643945id,54542547000148,45,999946130,4636,404,,foneinexistente,1899-12-30 00:00:00,,0,AGV NEGOCIADORA,PR
4,2025-09-01,220,41849079id,53330359000193,62,999623988,4047,200,cxpre,bloqueiodetector,2025-09-01 08:00:09,,0,URA CPC,GO

In [52]:
# >>>>>>>>>>>>>>>>>>>>>>>>>>> TESTES <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
# tipo da coluna
from src import data_wrangling_discagens_trestto
from src import data_wrangling_mailingHist
import importlib
import queries
importlib.reload(data_wrangling_discagens_trestto)
importlib.reload(data_wrangling_mailingHist)
importlib.reload(queries)
# >>>>>>>>>>>>>>>>>>>>>>> VERIFICAR TIPO DE DADO DE UMA COLUNA ESPECÍFICA
#print(df_discagens['ddd'].dtype)
# primeiros valores (mostra índices também)
#df_discagens['ddd'].head(30)

# >>>>>>>>>>>>>>>>>>>>>>> MOSTRAR PARTE DO DATAFRAME
# df_discagens.head()

# >>>>>>>>>>>>>>>>>>>>>>> FILTRAR DADOS DE UMA COLUNA ESPECÍFICA
# df_ativo = df_mailing_hist[df_mailing_hist['ID_CAR'].notna()]
# df_ativo.head()

# import pandas as pd
# Supondo que seu DataFrame seja 'df'

# valores_unicos = df_cad_devf['DESC_CAR'].unique()
# print(valores_unicos)

# >>>>>>>>>>>>>>>>>>>>>>> CONTAR VALORES ÚNICOS DE UMA COLUNA ESPECÍFICA
# len(df_ativo)
# df_discagens['OPERACAO'].value_counts().reset_index().rename(columns={'index': 'OPERACAO', 'OPERACAO': 'QTD'})
#  print(filtro)
#len(df_discagens)
#print("Linhas:", df_discagens.shape[0], " | Colunas:", df_discagens.shape[1])
#df_discagens.columns.tolist()
#df_discagens['Agente'].unique()
#type(df_discagens)

# >>>>>>>>>>>>>>>>>>>>>>> resumo por estado
# df_resumo = (
#     df_discagens
#     .groupby('ESTADO')['CPF']
#     .nunique()
#     .reset_index()
#     .rename(columns={'CPF': 'QTD_CPF_DISTINTOS'})
#     .sort_values(by='QTD_CPF_DISTINTOS', ascending=False)
# )
# df_resumo.head()
# print(df_resumo)
# >>>>>>>>>>>>>>>>>>>>>>>>>>> TESTANDO AS CONEXÕES <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<
# server = os.getenv('SERVER_BD2')
# database = os.getenv('DATABASE_TRC')
# print(f"Valor do Servidor: {server}")
# print(f"Valor do Banco de Dados: {database}") 

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> RECARREGANDO O .ENV <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<#
# from dotenv import load_dotenv
# import os

# # Recarrega o .env
# load_dotenv(dotenv_path='.env', override=True)

# # Testa se as variáveis foram carregadas
# print(os.getenv("SERVER_BD2"))
# print(os.getenv("DATABASE_TRC"))

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> AGRUPANDO DADOS COM SOMA (TRESTTO) <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<#
#df_discagens_trestto = df_discagens_trestto.groupby('DATA')['ALO'].sum().reset_index()


# data_inicial = '2025-09-30'
# data_final = '2025-09-30'

# Filtrar entre datas
# df_discagens_trestto_sum = df_discagens_trestto_sum[(df_discagens_trestto_sum['DATA'] >= data_inicial) & (df_discagens_trestto_sum['DATA'] <= data_final)]

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> FECHANDO AS CONEXÕES <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<#
# if 'conn' in locals() and conn:
#     conn.close()
#     print("Conexão com o banco de dados fechada com sucesso.")