In [1]:
%load_ext autoreload
%autoreload 2

# import sys 
# sys.path.append("..") 
import sys
sys.path.append(r"C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects")

In [2]:
import importlib 
#from utils import queries
#from utils.mailing import pipelines, metricas_acumuladas, data_processing
#from Renner.src.mailing import metricas_acumuladas, data_processing, pipelines
#from utils.acionamentos import metricas_acumuladas
#from utils.discagens.expert import pipelines, data_processing, metricas_acumuladas
#from utils.acionamentos import pipelines, metricas_acumuladas, data_processing
#from utils.discagens.expert.Ringing import metricas_acumuladas
#from utils.pagamentos import pipelines, metricas_acumuladas, data_processing
#from utils import utils, config, queries
#from utils.digital_channels import data_processing, metricas_acumuladas
#from utils.discagens.expert.Ringing import metricas_acumuladas
from utils._database import insert
from Cresol.src import database, config
#from Cresol.src.discagens import discagens_pipeline
#from Renner.src.mailing import data_processing, as
#from Renner.utils import queries

# importlib.reload(data_loader)
# importlib.reload(queries)
# importlib.reload(data_wrangling_mailingHist)
# #importlib.reload(queries)
#importlib.reload(utils)
importlib.reload(database)
importlib.reload(config)
importlib.reload(insert)
#importlib.reload(metricas_acumuladas)
#importlib.reload(pipelines)
#importlib.reload(data_processing)
#importlib.reload(data_loader)
#importlib.reload(queries)

In [3]:
# sobe para Projects 
from Cresol.src.data_loader import load_data_cresol

dados = load_data_cresol('2026-01-01', '2026-01-31')

(
df_discagens_expert,
df_mailing_hist, 
df_tab_acionamentos, 
df_tabulacao_aciona,
df_dw_calendario, 
df_pagamentos, 
df_acordos, 
df_sms,
df_rcs,
df_email,
df_whats
) = dados.values()

🔌 Conectando aos bancos de dados...
✅ Conexões estabelecidas

📊 Carregando dados de 2026-01-01 até 2026-01-31...

C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\utils\data_loader.py:227: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conexao)

[1/11] ✓ Discagens Expert: 965.316 registros (4m 38s)
[2/11] ✓ Mailing Histórico: 969.604 registros (5m 50s)
[3/11] ✓ Tabulação de Acionamentos: 37.395 registros (26s)
[4/11] ✓ Tabulação Acionamentos: 9.794 registros (0s)
[5/11] ✓ Calendário: 21 registros (0s)
[6/11] ✓ Pagamentos: 0 registros (2s)

C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\utils\data_loader.py:227: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conexao)

[7/11] ✓ Acordos: 1.892 registros (1s)
[8/11] ✓ SMS: 19.482 registros (0s)
[9/11] ✓ RCS: 20.211 registros (0s)
[10/11] ✓ Email: 0 registros (2s)

C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\utils\data_loader.py:227: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conexao)

[11/11] ✓ WhatsApp: 0 registros (0s)

✅ Carregamento concluído em 11m 3s
🔌 Conexão TRC fechada
🔌 Conexão BD2 fechada
🔌 Conexão SRC fechada

In [8]:
#df_discagens_expert
df_mailing_hist
df_mailing_acumulado
#df_discagens_expert.shape
# Converte a visão de valores em uma lista e acessa o primeiro
# df = list(df_discagens_expert)[0]

# print(df.shape)
# df.info()

# Se você usou algo como: dfs_dit = pd.read_excel('arquivo.xlsx', sheet_name=None)
# Para iterar e identificar cada um:

NameError: name 'df_mailing_hist' is not defined

In [ ]:
from utils.mailing.pipelines import processar_mailing_completo
from Cresol.src.mailing.data_processing import add_pf_pj, add_pa
from Cresol.src.config import LOG_MAILING, segmentacoes_extras

df_mailing_analitico, df_mailing_acumulado = processar_mailing_completo(
    df_mailing_hist,
    df_dw_calendario,
    segmentacoes=segmentacoes_extras,
    tratamentos_extras=[
        add_pf_pj,
        add_pa,
    ],
    arquivo_log=LOG_MAILING,
)
df_mailing_acumulado

============================================================
✓ 2 DataFrames unidos com sucesso
✓ Total de linhas: 462
✓ Total de colunas: 10
============================================================

============================================================
✓ 2 DataFrames unidos com sucesso
✓ Total de linhas: 682
✓ Total de colunas: 10
============================================================

============================================================
✓ 2 DataFrames unidos com sucesso
✓ Total de linhas: 1,144
✓ Total de colunas: 11
============================================================

,DATA,Indicador,qte,PF_PJ,PA,MesAbreviado,nr_dia_util,quartil,dt_mes,VALOR,TIPO
0,2026-01-02,Contratos,97,PF,ASCOOB CRESOL,Jan,1,Q1,1,1.324306e+06,Funil
1,2026-01-02,Contratos,972,PF,CENTRAL BRASIL EXTRA,Jan,1,Q1,1,1.835412e+07,Funil
2,2026-01-02,Contratos,16630,PF,CRESOL BASER,Jan,1,Q1,1,1.431388e+09,Funil
3,2026-01-02,Contratos,499,PF,CRESOL SICOPER,Jan,1,Q1,1,3.614015e+07,Funil
4,2026-01-02,Contratos,6119,PF,CRESOL SICOPER CALLCENTER,Jan,1,Q1,1,1.086046e+08,Funil
...,...,...,...,...,...,...,...,...,...,...,...
1139,2026-01-29,Carteira (CPFs),23642,Unique,Unique,Jan,20,Q1,1,1.552664e+09,Daily
1140,2026-01-30,Contratos,32727,Unique,Unique,Jan,21,Q1,1,2.325911e+09,Daily
1141,2026-01-30,Carteira (CPFs),23140,Unique,Unique,Jan,21,Q1,1,1.533384e+09,Daily
1142,2026-01-31,Contratos,32267,Unique,Unique,N/A,0,N/A,0,2.290624e+09,Daily
1143,2026-01-31,Carteira (CPFs),22805,Unique,Unique,N/A,0,N/A,0,1.509900e+09,Daily

In [ ]:
df_mailing_analitico
df_massivos_analitico
df_discagens_analitico
df_acionamentos_analitico
#print(df_massivos_analitico.columns)

,DATA,CONTRATO,CPF,ID_CAR,ATRASO,COD_CLI,VALOR,PF_PJ,PA
0,2026-01-01,500106120230208686,39094855968,89.0,19,181,18664.94,PF,CRESOL BASER
1,2026-01-01,500201220250178977,3348095921,91.0,14,231,91312.78,PF,CRESOL SICOPER CALLCENTER
2,2026-01-01,500104920250609529,93416237900,89.0,16,181,213.70,PF,CRESOL BASER
3,2026-01-01,500108920250304200,78251737249,89.0,38,181,31405.56,PF,CRESOL BASER
4,2026-01-01,500109720250157973,70802135170,89.0,27,181,10717.88,PF,CRESOL BASER
...,...,...,...,...,...,...,...,...,...
969599,2026-01-29,500201220250166758,4498986954,91.0,19,231,5752.18,PF,CRESOL SICOPER CALLCENTER
969600,2026-01-29,500103820240830626,26626002848,89.0,1092,181,32375.69,PF,CRESOL BASER
969601,2026-01-29,500103820241539630,3832786511,89.0,2856,181,661137.36,PF,CRESOL BASER
969602,2026-01-29,500103820240746293,93292406587,89.0,815,181,54.96,PF,CRESOL BASER
969603,2026-01-29,500100320260007943,13137979951,89.0,110,181,12785.53,PF,CRESOL BASER

In [31]:
from Cresol.src.config import TRANSFORMACOES_DISCAGENS, LOG_DISCAGENS, segmentacoes_extras
from utils.discagens.expert.data_processing import aplicar_transformacoes_discagens

df_discagens_analitico, df_discagens_sem_relacionamento = aplicar_transformacoes_discagens(
    df=df_discagens_expert,
    config=TRANSFORMACOES_DISCAGENS,
    df_mailing=df_mailing_analitico,
    df_calendario=df_dw_calendario,
    segmentacoes_extras=segmentacoes_extras,
    arquivo_log=LOG_DISCAGENS,
)
df_discagens_analitico

,DATA,ID_DISCAGEM,CONTRATO,AGENTE,DDD,TELEFONE,DATA_ENCERRAMENTO,CAMPANHA,COD_SIP,CLASS_RETORNO,...,ATRASO,COD_CLI,VALOR,PF_PJ,PA,CPF,nr_dia_util,quartil,dt_mes,mes_abreviado
0,2026-01-05,15,500100820250081873,,45,999239949,2026-01-05 09:47:04,4304,200,cxpos,...,87.0,181.0,14166.63,PF,CRESOL BASER,4197996993,2,Q1,1,Jan
1,2026-01-05,26,500103820250221971,,74,981015225,2026-01-05 09:47:04,4304,200,cxpos,...,82.0,181.0,14934.00,PF,CRESOL BASER,94057427104,2,Q1,1,Jan
2,2026-01-05,136,500103820240957262,,75,991897713,2026-01-05 09:47:09,4786,200,cxpre,...,2294.0,181.0,57401.89,PF,CRESOL BASER,730899586,2,Q1,1,Jan
3,2026-01-05,210,500203320240346748,,51,996799584,1899-12-30 00:00:00,4304,408,cxpre,...,83.0,230.0,13205.55,PF,CRESOL SICOPER,78685737087,2,Q1,1,Jan
4,2026-01-05,246,500103820241676382,,11,946080245,1899-12-30 00:00:00,4786,480,,...,3511.0,181.0,112941.29,PF,CRESOL BASER,59253029587,2,Q1,1,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
965311,2026-01-30,49434253,500204420220017811,,49,999940743,1899-12-30 00:00:00,4786,,cxpre,...,44.0,231.0,981.61,PF,CRESOL SICOPER CALLCENTER,6340726925,21,Q1,1,Jan
965312,2026-01-30,49434398,500103820241540273,,75,999664096,2026-01-30 17:49:48,4786,200,silencio,...,3152.0,181.0,146052.65,PF,CRESOL BASER,23989130587,21,Q1,1,Jan
965313,2026-01-30,49434614,500103820240230199,,75,32722358,1899-12-30 00:00:00,4786,480,,...,6037.0,181.0,31475.54,PF,CRESOL BASER,58060278568,21,Q1,1,Jan
965314,2026-01-30,49435006,500204520220098842,,55,999991519,1899-12-30 00:00:00,4786,408,,...,42.0,231.0,936.60,PF,CRESOL SICOPER CALLCENTER,62458256015,21,Q1,1,Jan
965315,2026-01-30,49435216,500103820240691408,,43,984154081,1899-12-30 00:00:00,4786,480,,...,3566.0,181.0,168884.20,PF,CRESOL BASER,5490266570,21,Q1,1,Jan

In [49]:
from Cresol.src.config import TRANSFORMACOES_DISCAGENS, LOG_DISCAGENS, segmentacoes_extras
from utils.discagens.expert.metricas_acumuladas import processar_acumulados_discagens_completo

df_discagens_acumulado = processar_acumulados_discagens_completo(
    df_discagens=df_discagens_analitico,
    segmentacoes_extras=segmentacoes_extras,
    retorno='consolidado',
    arquivo_log=LOG_DISCAGENS
)
df_discagens_acumulado

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 240
✓ Total de colunas: 10
============================================================

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 240
✓ Total de colunas: 10
============================================================

============================================================
✓ 2 DataFrames unidos com sucesso
✓ Total de linhas: 480
✓ Total de colunas: 11
============================================================

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 480
✓ Total de colunas: 10
============================================================

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 480
✓ Total de colunas: 10
============================================================

============================================================
✓ 2 DataFrames unidos com sucesso
✓ Total de linhas: 960
✓ Total de colunas: 11
============================================================

============================================================
✓ 2 DataFrames unidos com sucesso
✓ Total de linhas: 1,440
✓ Total de colunas: 11
============================================================

,DATA,Indicador,qte,PF_PJ,PA,MesAbreviado,nr_dia_util,quartil,dt_mes,VALOR,TIPO
0,2026-01-05,Trabalhado,53,PF,ASCOOB CRESOL,Jan,2,Q1,1,3.514587e+05,Funil
1,2026-01-05,Trabalhado,426,PF,CENTRAL BRASIL EXTRA,Jan,2,Q1,1,8.214105e+06,Funil
2,2026-01-05,Trabalhado,7539,PF,CRESOL BASER,Jan,2,Q1,1,6.536391e+08,Funil
3,2026-01-05,Trabalhado,199,PF,CRESOL SICOPER,Jan,2,Q1,1,1.959359e+07,Funil
4,2026-01-05,Trabalhado,555,PF,CRESOL SICOPER CALLCENTER,Jan,2,Q1,1,8.341752e+06,Funil
...,...,...,...,...,...,...,...,...,...,...,...
1435,2026-01-28,Outros,31305,Esforço,Esforço,Jan,19,Q1,1,2.266541e+09,Daily
1436,2026-01-29,ATIVO,13253,Esforço,Esforço,Jan,20,Q1,1,1.231196e+09,Daily
1437,2026-01-29,Outros,31551,Esforço,Esforço,Jan,20,Q1,1,2.252688e+09,Daily
1438,2026-01-30,ATIVO,6677,Esforço,Esforço,Jan,21,Q1,1,4.264689e+08,Daily
1439,2026-01-30,Outros,35358,Esforço,Esforço,Jan,21,Q1,1,2.499433e+09,Daily

In [42]:
from Cresol.src.config import TRANSFORMACOES_DISCAGENS, LOG_DISCAGENS, segmentacoes_extras
from utils.discagens.expert.metricas_acumuladas import processar_acumulados_discagens

df_discagens_acumulado = processar_acumulados_discagens(
    df_discagens=df_discagens_analitico,
    segmentacoes=segmentacoes_extras,
    retorno='consolidado',
    arquivo_log=LOG_DISCAGENS
)
df_discagens_acumulado

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 240
✓ Total de colunas: 10
============================================================

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 240
✓ Total de colunas: 10
============================================================

============================================================
✓ 2 DataFrames unidos com sucesso
✓ Total de linhas: 480
✓ Total de colunas: 11
============================================================

,DATA,Indicador,qte,PF_PJ,PA,MesAbreviado,nr_dia_util,quartil,dt_mes,VALOR,TIPO
0,2026-01-05,Trabalhado,53,PF,ASCOOB CRESOL,Jan,2,Q1,1,3.514587e+05,Funil
1,2026-01-05,Trabalhado,426,PF,CENTRAL BRASIL EXTRA,Jan,2,Q1,1,8.214105e+06,Funil
2,2026-01-05,Trabalhado,7539,PF,CRESOL BASER,Jan,2,Q1,1,6.536391e+08,Funil
3,2026-01-05,Trabalhado,199,PF,CRESOL SICOPER,Jan,2,Q1,1,1.959359e+07,Funil
4,2026-01-05,Trabalhado,555,PF,CRESOL SICOPER CALLCENTER,Jan,2,Q1,1,8.341752e+06,Funil
...,...,...,...,...,...,...,...,...,...,...,...
475,2026-01-26,Trabalhado,56687,Esforço,Esforço,Jan,17,Q1,1,1.752704e+09,Daily
476,2026-01-27,Trabalhado,46481,Esforço,Esforço,Jan,18,Q1,1,3.157770e+09,Daily
477,2026-01-28,Trabalhado,44294,Esforço,Esforço,Jan,19,Q1,1,2.971129e+09,Daily
478,2026-01-29,Trabalhado,44804,Esforço,Esforço,Jan,20,Q1,1,3.483884e+09,Daily
479,2026-01-30,Trabalhado,42035,Esforço,Esforço,Jan,21,Q1,1,2.925902e+09,Daily

In [165]:
from Cresol.src.config import LOG_DISCAGENS, segmentacoes_extras
from utils.discagens.expert.Ringing.metricas_acumuladas import processar_acumulados_ringing

# Retorno consolidado (um DataFrame único)
df_ringing_acumulados = processar_acumulados_ringing(
    df_discagens=df_discagens_analitico,
    segmentacoes=segmentacoes_extras,
    consolidado=True,
    arquivo_log=LOG_DISCAGENS,
)
df_ringing_acumulados

============================================================
✓ 6 DataFrames unidos com sucesso
✓ Total de linhas: 480
✓ Total de colunas: 11
============================================================

,DATA,Indicador,qte,PF_PJ,PA,MesAbreviado,nr_dia_util,quartil,dt_mes,VALOR,TIPO
0,2026-01-05,Ringing,36,PF,ASCOOB CRESOL,Jan,2,Q1,1,2.270158e+05,Funil
1,2026-01-05,Ringing,246,PF,CENTRAL BRASIL EXTRA,Jan,2,Q1,1,4.936702e+06,Funil
2,2026-01-05,Ringing,4988,PF,CRESOL BASER,Jan,2,Q1,1,4.577708e+08,Funil
3,2026-01-05,Ringing,103,PF,CRESOL SICOPER,Jan,2,Q1,1,7.136199e+06,Funil
4,2026-01-05,Ringing,387,PF,CRESOL SICOPER CALLCENTER,Jan,2,Q1,1,5.759879e+06,Funil
...,...,...,...,...,...,...,...,...,...,...,...
475,2026-01-26,Ringing,28245,Esforço,Esforço,Jan,17,Q1,1,1.021507e+09,Daily
476,2026-01-27,Ringing,22471,Esforço,Esforço,Jan,18,Q1,1,1.572427e+09,Daily
477,2026-01-28,Ringing,21566,Esforço,Esforço,Jan,19,Q1,1,1.463868e+09,Daily
478,2026-01-29,Ringing,18545,Esforço,Esforço,Jan,20,Q1,1,1.517666e+09,Daily
479,2026-01-30,Ringing,7872,Esforço,Esforço,Jan,21,Q1,1,5.054150e+08,Daily

In [ ]:
from Cresol.src.config import LOG_DISCAGENS, segmentacoes_extras
from utils.discagens.expert.Ringing.metricas_acumuladas import processar_acumulados_atendidas

# Retorno consolidado (um DataFrame único)
df_ringing_acumulados = processar_acumulados_atendidas(
    df_discagens=df_discagens_analitico,
    segmentacoes=segmentacoes_extras,
    consolidado=True,
    arquivo_log=LOG_DISCAGENS,
)
df_ringing_acumulados

In [88]:
# Verificar o df antes do filtro
print(df_discagens_analitico[['DATA_ENCERRAMENTO', 'COD_SIP']].dtypes)
print()

# Verificar quantos registros passam em cada filtro
print("Total:", len(df_discagens_analitico))
print("COD_SIP == 200:", (df_discagens_analitico['COD_SIP'] == 200).sum())
print("DATA_ENCERRAMENTO != '1899-12-30':", (df_discagens_analitico['DATA_ENCERRAMENTO'].astype(str).str[:10] != '1899-12-30').sum())
print("Ambos:", len(df_discagens_analitico[
    (df_discagens_analitico['DATA_ENCERRAMENTO'].astype(str).str[:10] != '1899-12-30') &
    (df_discagens_analitico['COD_SIP'] == 200)
]))

# Verificar amostra dos valores reais
print()
print(df_discagens_analitico['DATA_ENCERRAMENTO'].value_counts().head())
print()
print(df_discagens_analitico['COD_SIP'].value_counts().head())

DATA_ENCERRAMENTO    datetime64[ns]
COD_SIP                      object
dtype: object

Total: 914777
COD_SIP == 200: 0
DATA_ENCERRAMENTO != '1899-12-30': 427381
Ambos: 0

DATA_ENCERRAMENTO
1899-12-30 00:00:00    487396
2026-01-21 16:52:13        10
2026-01-14 11:27:20         8
2026-01-20 15:04:58         8
2026-01-19 09:55:02         8
Name: count, dtype: int64

COD_SIP
200    427381
480    210688
404    131424
408     77878
500     23267
Name: count, dtype: int64

In [76]:
df_tab_acionamentos
df_sem_relacionamento
#df_sem_descricao
#df_tabulacao_aciona

,DATA_ACIONA,HORA,CONTRATO_FIN,CPF_DEV,COD_ACIONA,DESC_ACIONAMENTO,COD_RECUP,NOME_RECUP,LOGIN_RECUP,ULTGRUPO_RECUP,...,ID_CAR,ATRASO,VALOR,PF_PJ,PA,COD_CLI,nr_dia_util,quartil,dt_mes,mes_abreviado
0,2026-01-23,00:00:00,500300520180029319,808154052,11150,ENVIO DE RCS - CRESOL,18640,MARIA LUIZA MOREIRA ARAUJO,MARIAM.ARAUJO,None,...,NaN,NaN,NaN,NaN,NaN,181,16.0,Q1,1.0,Jan
1,2026-01-29,00:00:00,10100500000043745,5169832966,11150,ENVIO DE RCS - CRESOL,18640,MARIA LUIZA MOREIRA ARAUJO,MARIAM.ARAUJO,None,...,NaN,NaN,NaN,NaN,NaN,181,20.0,Q1,1.0,Jan
2,2026-01-29,00:00:00,10100800000040282,4803115958,11150,ENVIO DE RCS - CRESOL,18640,MARIA LUIZA MOREIRA ARAUJO,MARIAM.ARAUJO,None,...,NaN,NaN,NaN,NaN,NaN,181,20.0,Q1,1.0,Jan
3,2026-01-15,00:00:00,500100520170005792,7166612924,11150,ENVIO DE RCS - CRESOL,18640,MARIA LUIZA MOREIRA ARAUJO,MARIAM.ARAUJO,None,...,NaN,NaN,NaN,NaN,NaN,181,10.0,Q1,1.0,Jan
4,2026-01-15,00:00:00,500106120180006247,9806940946,11150,ENVIO DE RCS - CRESOL,18640,MARIA LUIZA MOREIRA ARAUJO,MARIAM.ARAUJO,None,...,NaN,NaN,NaN,NaN,NaN,181,10.0,Q1,1.0,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31313,2026-01-28,00:00:00,500200420230305143,43386084000156,11150,ENVIO DE RCS - CRESOL,18640,MARIA LUIZA MOREIRA ARAUJO,MARIAM.ARAUJO,None,...,NaN,NaN,NaN,NaN,NaN,231,19.0,Q1,1.0,Jan
31315,2026-01-28,00:00:00,500200420240056546,11423511905,11150,ENVIO DE RCS - CRESOL,18640,MARIA LUIZA MOREIRA ARAUJO,MARIAM.ARAUJO,None,...,NaN,NaN,NaN,NaN,NaN,231,19.0,Q1,1.0,Jan
31317,2026-01-15,00:00:00,500200420240085198,3921243432,11150,ENVIO DE RCS - CRESOL,18640,MARIA LUIZA MOREIRA ARAUJO,MARIAM.ARAUJO,None,...,NaN,NaN,NaN,NaN,NaN,231,10.0,Q1,1.0,Jan
31320,2026-01-15,00:00:00,500200420240202397,43386084000156,11150,ENVIO DE RCS - CRESOL,18640,MARIA LUIZA MOREIRA ARAUJO,MARIAM.ARAUJO,None,...,NaN,NaN,NaN,NaN,NaN,231,10.0,Q1,1.0,Jan
31321,2026-01-28,00:00:00,500200420240202397,43386084000156,11150,ENVIO DE RCS - CRESOL,18640,MARIA LUIZA MOREIRA ARAUJO,MARIAM.ARAUJO,None,...,NaN,NaN,NaN,NaN,NaN,231,19.0,Q1,1.0,Jan

In [75]:
from utils.acionamentos.metricas_acumuladas import processar_acumulados_acionamentos
from utils.acionamentos.data_processing import enriquecer_acionamentos, processar_acionamentos
from Cresol.src.config import TRANSFORMACOES_DISCAGENS, LOG_ACIONAMENTOS, segmentacoes_extras

df_acionamentos_analitico, df_acionamentos_sem_relacionamento, df_sem_descricao = processar_acionamentos(
    df_tab_acionamentos=df_tab_acionamentos,
    df_tabulacao_aciona=df_tabulacao_aciona,
    df_mailing_hist=df_mailing_analitico,
    df_dw_calendario=df_dw_calendario,
    segmentacoes_extras=segmentacoes_extras,
    arquivo_log=LOG_ACIONAMENTOS,
)
df_acionamentos_analitico

,DATA_ACIONA,HORA,CONTRATO_FIN,CPF_DEV,COD_ACIONA,DESC_ACIONAMENTO,COD_RECUP,NOME_RECUP,LOGIN_RECUP,ULTGRUPO_RECUP,...,ID_CAR,ATRASO,VALOR,PF_PJ,PA,COD_CLI,nr_dia_util,quartil,dt_mes,mes_abreviado
3245,2026-01-15,00:00:00,500100320230747586,12949342000131,11150,ENVIO DE RCS - CRESOL,18640,MARIA LUIZA MOREIRA ARAUJO,MARIAM.ARAUJO,None,...,89.0,87.0,1270429.80,PJ,CRESOL BASER,181.0,10.0,Q1,1.0,Jan
3246,2026-01-16,10:08:50.346666,500100320230747586,12949342000131,5281,ENVIO DE WHATS - AÇÃO,12036,ANIELY OLIVEIRA DE LIMA,ANIELY_VV,OUZE,...,89.0,88.0,1270771.49,PJ,CRESOL BASER,181.0,11.0,Q1,1.0,Jan
3247,2026-01-26,00:00:00,500100320230747586,12949342000131,11150,ENVIO DE RCS - CRESOL,18640,MARIA LUIZA MOREIRA ARAUJO,MARIAM.ARAUJO,None,...,89.0,98.0,1171449.15,PJ,CRESOL BASER,181.0,17.0,Q1,1.0,Jan
3248,2026-01-28,00:00:00,500100320230747586,12949342000131,11150,ENVIO DE RCS - CRESOL,18640,MARIA LUIZA MOREIRA ARAUJO,MARIAM.ARAUJO,None,...,89.0,100.0,1289755.74,PJ,CRESOL BASER,181.0,19.0,Q1,1.0,Jan
3757,2026-01-26,15:19:32.826666,500106920210121159,10468893000158,5286,PROMESSA DE PAGAMENTO - CRESOL,12036,ANIELY OLIVEIRA DE LIMA,ANIELY_VV,OUZE,...,89.0,174.0,5252.44,PJ,CRESOL BASER,181.0,17.0,Q1,1.0,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31664,2026-01-21,13:47:14.920000,500202720250083555,9278344990,5281,ENVIO DE WHATS - AÇÃO,12036,ANIELY OLIVEIRA DE LIMA,ANIELY_VV,OUZE,...,NaN,131.0,4332.39,PF,CENTRAL BRASIL EXTRA,254.0,14.0,Q1,1.0,Jan
31665,2026-01-30,13:22:47.520000,500202720250083555,9278344990,5283,LINHA MUDA / NÃO ATENDE - CRESOL,12036,ANIELY OLIVEIRA DE LIMA,ANIELY_VV,OUZE,...,NaN,140.0,4363.57,PF,CENTRAL BRASIL EXTRA,254.0,21.0,Q1,1.0,Jan
31666,2026-01-14,09:00:43.223333,500202720250097308,9278344990,5281,ENVIO DE WHATS - AÇÃO,12036,ANIELY OLIVEIRA DE LIMA,ANIELY_VV,OUZE,...,NaN,91.0,5293.77,PF,CENTRAL BRASIL EXTRA,254.0,9.0,Q1,1.0,Jan
31667,2026-01-21,13:47:14.943333,500202720250097308,9278344990,5281,ENVIO DE WHATS - AÇÃO,12036,ANIELY OLIVEIRA DE LIMA,ANIELY_VV,OUZE,...,NaN,98.0,5436.05,PF,CENTRAL BRASIL EXTRA,254.0,14.0,Q1,1.0,Jan
31668,2026-01-30,13:22:47.636666,500202720250097308,9278344990,5283,LINHA MUDA / NÃO ATENDE - CRESOL,12036,ANIELY OLIVEIRA DE LIMA,ANIELY_VV,OUZE,...,NaN,107.0,5465.21,PF,CENTRAL BRASIL EXTRA,254.0,21.0,Q1,1.0,Jan

In [134]:
from utils.acionamentos.metricas_acumuladas import processar_acumulados_acionamentos
from Cresol.src.config import LOG_ACIONAMENTOS, segmentacoes_extras

df_acionamentos_acumulados = processar_acumulados_acionamentos(
    df_acionamentos=df_acionamentos_analitico,
    segmentacoes=segmentacoes_extras,
    retorno='consolidado',
    arquivo_log=LOG_ACIONAMENTOS
)
df_acionamentos_acumulados

✓ DataFrame 1: Colunas renomeadas: DATA_ACIONA -> DATA
✓ DataFrame 2: Colunas renomeadas: DATA_ACIONA -> DATA
✓ DataFrame 3: Colunas renomeadas: DATA_ACIONA -> DATA

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 796
✓ Total de colunas: 10
============================================================
✓ DataFrame 1: Colunas renomeadas: DATA_ACIONA -> DATA
✓ DataFrame 2: Colunas renomeadas: DATA_ACIONA -> DATA
✓ DataFrame 3: Colunas renomeadas: DATA_ACIONA -> DATA

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 800
✓ Total de colunas: 10
============================================================

============================================================
✓ 2 DataFrames unidos com sucesso
✓ Total de linhas: 1,596
✓ Total de colunas: 11
============================================================

,DATA,Indicador,qte,PF_PJ,PA,MesAbreviado,nr_dia_util,quartil,dt_mes,VALORPRIN_FIN,TIPO
0,2026-01-05,Acionamentos,5.0,PF,CENTRAL BRASIL EXTRA,Jan,2,Q1,1,31096.82,Funil
1,2026-01-05,Acionamentos,80.0,PF,CRESOL BASER,Jan,2,Q1,1,2997270.97,Funil
2,2026-01-05,Acionamentos,8.0,PF,CRESOL SICOPER CALLCENTER,Jan,2,Q1,1,199386.07,Funil
3,2026-01-05,Acionamentos,31.0,PJ,CRESOL BASER,Jan,2,Q1,1,3528257.24,Funil
4,2026-01-05,Acionamentos,4.0,PJ,CRESOL SICOPER CALLCENTER,Jan,2,Q1,1,178843.54,Funil
...,...,...,...,...,...,...,...,...,...,...,...
1591,2026-01-30,Promessa,45.0,Esforço,Esforço,Jan,21,Q1,1,6279719.78,Daily
1592,2026-01-31,Acionamentos,115.0,Esforço,Esforço,N/A,0,0,0,2362725.37,Daily
1593,2026-01-31,CPC,0.0,Esforço,Esforço,N/A,0,0,0,0.00,Daily
1594,2026-01-31,CPCA,0.0,Esforço,Esforço,N/A,0,0,0,0.00,Daily
1595,2026-01-31,Promessa,0.0,Esforço,Esforço,N/A,0,0,0,0.00,Daily

In [109]:
df_sms,
df_rcs,
df_email
#df_whats

Empty DataFrame
Columns: [DATA, CPF, PF_PJ]
Index: []

In [114]:
from Cresol.src.config import LOG_CHANNELS, segmentacoes_extras
from utils.digital_channels.data_processing import processar_massivos

df_massivos_analitico, df_sem_relacionamento = processar_massivos(
    df_sms=df_sms,
    df_rcs=df_rcs,
    df_email=df_email,
    df_whats=df_whats,
    df_mailing_hist=df_mailing_analitico,
    df_dw_calendario=df_dw_calendario,
    segmentacoes_extras=segmentacoes_extras,
    arquivo_log=LOG_CHANNELS,
)
df_massivos_analitico

,CPF,DATA,CANAL,CONTRATO,ID_CAR,ATRASO,COD_CLI,VALOR,PF_PJ,PA,nr_dia_util,quartil,dt_mes,mes_abreviado
0,21719722000170,2026-01-05,SMS,500100320250629276,89.0,21.0,181.0,80423.10,PJ,CRESOL BASER,2.0,Q1,1.0,Jan
1,16257774004,2026-01-05,SMS,500106920230250327,89.0,174.0,181.0,78202.26,PF,CRESOL BASER,2.0,Q1,1.0,Jan
2,50484132000104,2026-01-05,SMS,500100320251190575,89.0,116.0,181.0,12971.56,PJ,CRESOL BASER,2.0,Q1,1.0,Jan
3,3888716950,2026-01-05,SMS,500100920240400454,89.0,32.0,181.0,80145.31,PF,CRESOL BASER,2.0,Q1,1.0,Jan
4,4942509920,2026-01-05,SMS,500106120250179411,89.0,26.0,181.0,80108.04,PF,CRESOL BASER,2.0,Q1,1.0,Jan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27223,5185253924,2026-01-30,RCS,500103120240305020,89.0,36.0,181.0,824.73,PF,CRESOL BASER,21.0,Q1,1.0,Jan
27224,40494634000162,2026-01-30,RCS,500103820241057096,89.0,66.0,181.0,2295.81,PJ,CRESOL BASER,21.0,Q1,1.0,Jan
27225,9347414689,2026-01-30,RCS,500109520250755572,89.0,7.0,181.0,3087.40,PF,CRESOL BASER,21.0,Q1,1.0,Jan
27226,89450973920,2026-01-30,RCS,500300520250010926,89.0,15.0,181.0,10227.57,PF,CRESOL BASER,21.0,Q1,1.0,Jan
27227,7410297905,2026-01-30,RCS,500104920250139592,89.0,20.0,181.0,40652.67,PF,CRESOL BASER,21.0,Q1,1.0,Jan

In [127]:
from utils.digital_channels.metricas_acumuladas import processar_acumulados_massivos
from Cresol.src.config import LOG_CHANNELS, segmentacoes_extras

# Retorno consolidado com coluna TIPO
df_massivos_acumulado = processar_acumulados_massivos(
    df_massivos=df_massivos_analitico,
    segmentacoes=segmentacoes_extras,
    arquivo_log=LOG_CHANNELS
)
df_massivos_acumulado

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 315
✓ Total de colunas: 10
============================================================

============================================================
✓ 3 DataFrames unidos com sucesso
✓ Total de linhas: 228
✓ Total de colunas: 10
============================================================

============================================================
✓ 2 DataFrames unidos com sucesso
✓ Total de linhas: 543
✓ Total de colunas: 11
============================================================

,DATA,Indicador,qte,PF_PJ,PA,MesAbreviado,nr_dia_util,quartil,dt_mes,VALORPRIN_FIN,TIPO
0,2026-01-02,RCS,1494,PF,CRESOL BASER,Jan,1.0,Q1,1.0,1.263103e+07,Funil
1,2026-01-02,RCS,1,PF,CRESOL SICOPER CALLCENTER,Jan,1.0,Q1,1.0,2.340360e+03,Funil
2,2026-01-02,RCS,348,PJ,CRESOL BASER,Jan,1.0,Q1,1.0,4.126341e+06,Funil
3,2026-01-02,SMS,883,PF,CRESOL BASER,Jan,1.0,Q1,1.0,9.621171e+07,Funil
4,2026-01-05,RCS,2972,PF,CRESOL BASER,Jan,2.0,Q1,1.0,1.146828e+08,Funil
...,...,...,...,...,...,...,...,...,...,...,...
538,2026-01-27,SMS,122,Esforço,Esforço,Jan,18.0,Q1,1.0,6.606238e+06,Daily
539,2026-01-28,RCS,486,Esforço,Esforço,Jan,19.0,Q1,1.0,1.339197e+08,Daily
540,2026-01-29,SMS,1711,Esforço,Esforço,Jan,20.0,Q1,1.0,7.194221e+07,Daily
541,2026-01-30,RCS,199,Esforço,Esforço,Jan,21.0,Q1,1.0,1.754917e+07,Daily
542,2026-01-31,SMS,72,Esforço,Esforço,N/A,0.0,0,0.0,1.666100e+06,Daily

In [191]:
df_massivos_acumulado

,DATA,Indicador,qte,PF_PJ,PA,MesAbreviado,nr_dia_util,quartil,dt_mes,VALORPRIN_FIN,TIPO
0,2026-01-02,RCS,1494,PF,CRESOL BASER,Jan,1.0,Q1,1.0,1.263103e+07,Funil
1,2026-01-02,RCS,1,PF,CRESOL SICOPER CALLCENTER,Jan,1.0,Q1,1.0,2.340360e+03,Funil
2,2026-01-02,RCS,348,PJ,CRESOL BASER,Jan,1.0,Q1,1.0,4.126341e+06,Funil
3,2026-01-02,SMS,883,PF,CRESOL BASER,Jan,1.0,Q1,1.0,9.621171e+07,Funil
4,2026-01-05,RCS,2972,PF,CRESOL BASER,Jan,2.0,Q1,1.0,1.146828e+08,Funil
...,...,...,...,...,...,...,...,...,...,...,...
538,2026-01-27,SMS,122,Esforço,Esforço,Jan,18.0,Q1,1.0,6.606238e+06,Daily
539,2026-01-28,RCS,486,Esforço,Esforço,Jan,19.0,Q1,1.0,1.339197e+08,Daily
540,2026-01-29,SMS,1711,Esforço,Esforço,Jan,20.0,Q1,1.0,7.194221e+07,Daily
541,2026-01-30,RCS,199,Esforço,Esforço,Jan,21.0,Q1,1.0,1.754917e+07,Daily
542,2026-01-31,SMS,72,Esforço,Esforço,N/A,0.0,0,0.0,1.666100e+06,Daily

In [257]:
import traceback

from utils.utils import salvar_log, registrar_tempo, unir_dataframes
from Cresol.src.database import inserir_acumulado
from utils.db_connection import get_db_connections
from Cresol.src.config import LOG_PIPELINE

def _executar_etapa(nome: str, fn, *args, **kwargs):
    """
    Executa uma etapa da pipeline com log padronizado.
    Lança a exceção original em caso de falha para interromper o fluxo.
    """
    salvar_log(f"{'─' * 50}", LOG_PIPELINE)
    salvar_log(f"INÍCIO » {nome}", LOG_PIPELINE)
    try:
        resultado = fn(*args, **kwargs)
        salvar_log(f"OK    » {nome}", LOG_PIPELINE)
        return resultado
    except Exception as e:
        salvar_log(f"FALHA » {nome}: {str(e)}", LOG_PIPELINE)
        salvar_log(traceback.format_exc(), LOG_PIPELINE)
        raise

df_acumulados_consolidado = _executar_etapa(
        "Consolidação dos acumulados",
        unir_dataframes,
        df_mailing_acumulado,
        df_discagens_acumulado,
        df_ringing_acumulados,
        df_acionamentos_acumulados,
        df_massivos_acumulado,
    )

with get_db_connections() as (_, conn_bd2, __):
    _executar_etapa(
        "Insert banco de dados",
        inserir_acumulado,
        df_acionamentos_acumulados,
        conn_bd2,
    )
df_acumulados_consolidado

✓ DataFrame 4: Colunas renomeadas: VALORPRIN_FIN -> VALOR
✓ DataFrame 5: Colunas renomeadas: VALORPRIN_FIN -> VALOR

============================================================
✓ 5 DataFrames unidos com sucesso
✓ Total de linhas: 5,203
✓ Total de colunas: 11
============================================================
🔌 Conectando aos bancos de dados...
✅ Conexões estabelecidas
🔌 Conexão TRC fechada
🔌 Conexão BD2 fechada
🔌 Conexão SRC fechada

KeyError: "['VALOR'] not in index"

In [234]:
print(df_acumulados_consolidado.columns)

Index(['DATA', 'Indicador', 'qte', 'PF_PJ', 'PA', 'MesAbreviado',
       'nr_dia_util', 'quartil', 'dt_mes', 'VALOR', 'TIPO'],
      dtype='object')

In [213]:
import importlib
import utils._database.insert
importlib.reload(utils._database.insert)

# teste direto no df antes de qualquer função
registro_teste = [tuple(row) for row in df_acionamentos_acumulados.head(1).itertuples(index=False, name=None)]
for i_val, val in enumerate(registro_teste[0]):
    print(f"param-index={i_val} | valor={val} | tipo={type(val)}")

param-index=0 | valor=2026-01-05 00:00:00 | tipo=<class 'pandas._libs.tslibs.timestamps.Timestamp'>
param-index=1 | valor=Acionamentos | tipo=<class 'str'>
param-index=2 | valor=5.0 | tipo=<class 'float'>
param-index=3 | valor=PF | tipo=<class 'str'>
param-index=4 | valor=CENTRAL BRASIL EXTRA | tipo=<class 'str'>
param-index=5 | valor=Jan | tipo=<class 'str'>
param-index=6 | valor=2 | tipo=<class 'int'>
param-index=7 | valor=Q1 | tipo=<class 'str'>
param-index=8 | valor=1 | tipo=<class 'int'>
param-index=9 | valor=31096.82 | tipo=<class 'float'>
param-index=10 | valor=Funil | tipo=<class 'str'>

In [219]:
df_acumulados_consolidado = _executar_etapa(
        "Consolidação dos acumulados",
        unir_dataframes,
        df_mailing_acumulado,
        df_discagens_acumulado,
        df_ringing_acumulados,
        df_acionamentos_acumulados,
        df_massivos_acumulado,
    )
df_acumulados_consolidado

✓ DataFrame 4: Colunas renomeadas: VALORPRIN_FIN -> VALOR
✓ DataFrame 5: Colunas renomeadas: VALORPRIN_FIN -> VALOR

============================================================
✓ 5 DataFrames unidos com sucesso
✓ Total de linhas: 5,203
✓ Total de colunas: 11
============================================================

,DATA,Indicador,qte,PF_PJ,PA,MesAbreviado,nr_dia_util,quartil,dt_mes,VALOR,TIPO
0,2026-01-02,Contratos,97.0,PF,ASCOOB CRESOL,Jan,1.0,Q1,1.0,1.324306e+06,Funil
1,2026-01-02,Contratos,972.0,PF,CENTRAL BRASIL EXTRA,Jan,1.0,Q1,1.0,1.835412e+07,Funil
2,2026-01-02,Contratos,16630.0,PF,CRESOL BASER,Jan,1.0,Q1,1.0,1.431388e+09,Funil
3,2026-01-02,Contratos,499.0,PF,CRESOL SICOPER,Jan,1.0,Q1,1.0,3.614015e+07,Funil
4,2026-01-02,Contratos,6119.0,PF,CRESOL SICOPER CALLCENTER,Jan,1.0,Q1,1.0,1.086046e+08,Funil
...,...,...,...,...,...,...,...,...,...,...,...
5198,2026-01-27,SMS,122.0,Esforço,Esforço,Jan,18.0,Q1,1.0,6.606238e+06,Daily
5199,2026-01-28,RCS,486.0,Esforço,Esforço,Jan,19.0,Q1,1.0,1.339197e+08,Daily
5200,2026-01-29,SMS,1711.0,Esforço,Esforço,Jan,20.0,Q1,1.0,7.194221e+07,Daily
5201,2026-01-30,RCS,199.0,Esforço,Esforço,Jan,21.0,Q1,1.0,1.754917e+07,Daily
5202,2026-01-31,SMS,72.0,Esforço,Esforço,N/A,0.0,0,0.0,1.666100e+06,Daily

In [258]:
import importlib
import utils._database.insert
import Cresol.src.database

importlib.reload(utils._database.insert)
importlib.reload(Cresol.src.database)

from Cresol.src.database import inserir_acumulado, COLUNAS_SINTETICO

with get_db_connections() as (_, conn_bd2, __):
    inserir_acumulado(df_acumulados_consolidado, conn_bd2)

🔌 Conectando aos bancos de dados...
✅ Conexões estabelecidas
───────────────────────────────────────────────────────
[sintetico_cresol] Iniciando insert — 5,203 registros em 1 lote(s)
[sintetico_cresol] Lote 1/1 inserido — 5,203 registros
[sintetico_cresol] ✅ Commit realizado — 5,203 registros inseridos com sucesso
🔌 Conexão TRC fechada
🔌 Conexão BD2 fechada
🔌 Conexão SRC fechada

In [181]:
import os
# #df_conflitos_score
#df_acionamentos_enriquecido_limpo, df_acion_semFaixa, df_acion_semDescricao, df_acion_semOrigem 
df_mailing_acumulado.to_csv('df_mailing_acumulado.csv', sep=';', index=False, decimal=',', encoding='utf-8-sig')
os.startfile('df_mailing_acumulado.csv')  # abre com o programa padrão

In [268]:
def diagnosticar_tipos(df, nome):
    print(f"\n{'='*50}")
    print(f"DIAGNÓSTICO » {nome}")
    print(f"{'='*50}")
    registro = [tuple(row) for row in df.head(1).itertuples(index=False, name=None)]
    for i, (col, val) in enumerate(zip(df.columns, registro[0])):
        print(f"param-index={i} | col={col} | dtype={df[col].dtype} | tipo_valor={type(val).__name__} | exemplo={val}")

diagnosticar_tipos(df_mailing_analitico, 'mailing')
diagnosticar_tipos(df_discagens_analitico, 'discagens')
diagnosticar_tipos(df_acionamentos_analitico, 'acionamentos')
diagnosticar_tipos(df_massivos_analitico, 'massivos')

==================================================
DIAGNÓSTICO » mailing
==================================================
param-index=0 | col=DATA | dtype=object | tipo_valor=date | exemplo=2026-01-01
param-index=1 | col=CONTRATO | dtype=object | tipo_valor=str | exemplo=500106120230208686
param-index=2 | col=CPF | dtype=object | tipo_valor=str | exemplo=39094855968
param-index=3 | col=ID_CAR | dtype=float64 | tipo_valor=float | exemplo=89.0
param-index=4 | col=ATRASO | dtype=int64 | tipo_valor=int | exemplo=19
param-index=5 | col=COD_CLI | dtype=int64 | tipo_valor=int | exemplo=181
param-index=6 | col=VALOR | dtype=float64 | tipo_valor=float | exemplo=18664.94
param-index=7 | col=PF_PJ | dtype=object | tipo_valor=str | exemplo=PF
param-index=8 | col=PA | dtype=object | tipo_valor=str | exemplo=CRESOL BASER

==================================================
DIAGNÓSTICO » discagens
==================================================
param-index=0 | col=DATA | dtype=object | tipo_valor=date | exemplo=2026-01-05
param-index=1 | col=ID_DISCAGEM | dtype=int64 | tipo_valor=int | exemplo=15
param-index=2 | col=CONTRATO | dtype=object | tipo_valor=str | exemplo=500100820250081873
param-index=3 | col=AGENTE | dtype=object | tipo_valor=str | exemplo=
param-index=4 | col=DDD | dtype=int64 | tipo_valor=int | exemplo=45
param-index=5 | col=TELEFONE | dtype=int64 | tipo_valor=int | exemplo=999239949
param-index=6 | col=DATA_ENCERRAMENTO | dtype=datetime64[ns] | tipo_valor=Timestamp | exemplo=2026-01-05 09:47:04
param-index=7 | col=CAMPANHA | dtype=int64 | tipo_valor=int | exemplo=4304
param-index=8 | col=COD_SIP | dtype=object | tipo_valor=str | exemplo=200
param-index=9 | col=CLASS_RETORNO | dtype=object | tipo_valor=str | exemplo=cxpos
param-index=10 | col=DESC_MOTIVO_ENCERR | dtype=object | tipo_valor=str | exemplo=bloqueiodetector
param-index=11 | col=OPERACAO | dtype=object | tipo_valor=str | exemplo=ATIVO
param-index=12 | col=ESTADO | dtype=object | tipo_valor=str | exemplo=PR
param-index=13 | col=ID_CAR | dtype=float64 | tipo_valor=float | exemplo=89.0
param-index=14 | col=ATRASO | dtype=float64 | tipo_valor=float | exemplo=87.0
param-index=15 | col=COD_CLI | dtype=float64 | tipo_valor=float | exemplo=181.0
param-index=16 | col=VALOR | dtype=float64 | tipo_valor=float | exemplo=14166.630000000001
param-index=17 | col=PF_PJ | dtype=object | tipo_valor=str | exemplo=PF
param-index=18 | col=PA | dtype=object | tipo_valor=str | exemplo=CRESOL BASER
param-index=19 | col=CPF | dtype=object | tipo_valor=str | exemplo=4197996993
param-index=20 | col=nr_dia_util | dtype=int64 | tipo_valor=int | exemplo=2
param-index=21 | col=quartil | dtype=object | tipo_valor=str | exemplo=Q1
param-index=22 | col=dt_mes | dtype=int64 | tipo_valor=int | exemplo=1
param-index=23 | col=mes_abreviado | dtype=object | tipo_valor=str | exemplo=Jan

==================================================
DIAGNÓSTICO » acionamentos
==================================================
param-index=0 | col=DATA_ACIONA | dtype=object | tipo_valor=date | exemplo=2026-01-15
param-index=1 | col=HORA | dtype=object | tipo_valor=time | exemplo=00:00:00
param-index=2 | col=CONTRATO_FIN | dtype=object | tipo_valor=str | exemplo=500100320230747586
param-index=3 | col=CPF_DEV | dtype=object | tipo_valor=str | exemplo=12949342000131
param-index=4 | col=COD_ACIONA | dtype=object | tipo_valor=str | exemplo=11150
param-index=5 | col=DESC_ACIONAMENTO | dtype=object | tipo_valor=str | exemplo=ENVIO DE RCS - CRESOL
param-index=6 | col=COD_RECUP | dtype=object | tipo_valor=str | exemplo=18640
param-index=7 | col=NOME_RECUP | dtype=object | tipo_valor=str | exemplo=MARIA LUIZA MOREIRA ARAUJO
param-index=8 | col=LOGIN_RECUP | dtype=object | tipo_valor=str | exemplo=MARIAM.ARAUJO
param-index=9 | col=ULTGRUPO_RECUP | dtype=object | tipo_valor=NoneType | exemplo=None
param-index=10 | col=VALORPRIN_FIN | dtype=float64 | tipo_valor=float | exemplo=1278118.52
param-index=11 | col=STATCONT_FIN | dtype=object | tipo_valor=str | exemplo=0
param-index=12 | col=DTDEVOL_FIN | dtype=datetime64[ns] | tipo_valor=NaTType | exemplo=NaT
param-index=13 | col=DTENTRADA_FIN | dtype=datetime64[ns] | tipo_valor=NaTType | exemplo=NaT
param-index=14 | col=CLASSIFICACAO_ACIONAMENTO | dtype=object | tipo_valor=str | exemplo=1
param-index=15 | col=ACIONAMENTOS | dtype=int64 | tipo_valor=int | exemplo=1
param-index=16 | col=CPC | dtype=int64 | tipo_valor=int | exemplo=0
param-index=17 | col=CPCA | dtype=int64 | tipo_valor=int | exemplo=0
param-index=18 | col=PROMESSA | dtype=int64 | tipo_valor=int | exemplo=0
param-index=19 | col=DESCR | dtype=object | tipo_valor=str | exemplo=ENVIO DE RCS - CRESOL
param-index=20 | col=CPF | dtype=object | tipo_valor=str | exemplo=12949342000131
param-index=21 | col=ID_CAR | dtype=float64 | tipo_valor=float | exemplo=89.0
param-index=22 | col=ATRASO | dtype=float64 | tipo_valor=float | exemplo=87.0
param-index=23 | col=VALOR | dtype=float64 | tipo_valor=float | exemplo=1270429.8000000003
param-index=24 | col=PF_PJ | dtype=object | tipo_valor=str | exemplo=PJ
param-index=25 | col=PA | dtype=object | tipo_valor=str | exemplo=CRESOL BASER
param-index=26 | col=COD_CLI | dtype=object | tipo_valor=float | exemplo=181.0
param-index=27 | col=nr_dia_util | dtype=float64 | tipo_valor=float | exemplo=10.0
param-index=28 | col=quartil | dtype=object | tipo_valor=str | exemplo=Q1
param-index=29 | col=dt_mes | dtype=float64 | tipo_valor=float | exemplo=1.0
param-index=30 | col=mes_abreviado | dtype=object | tipo_valor=str | exemplo=Jan

==================================================
DIAGNÓSTICO » massivos
==================================================
param-index=0 | col=CPF | dtype=object | tipo_valor=str | exemplo=21719722000170
param-index=1 | col=DATA | dtype=object | tipo_valor=date | exemplo=2026-01-05
param-index=2 | col=CANAL | dtype=object | tipo_valor=str | exemplo=SMS
param-index=3 | col=CONTRATO | dtype=object | tipo_valor=str | exemplo=500100320250629276
param-index=4 | col=ID_CAR | dtype=float64 | tipo_valor=float | exemplo=89.0
param-index=5 | col=ATRASO | dtype=float64 | tipo_valor=float | exemplo=21.0
param-index=6 | col=COD_CLI | dtype=float64 | tipo_valor=float | exemplo=181.0
param-index=7 | col=VALOR | dtype=float64 | tipo_valor=float | exemplo=80423.09999999999
param-index=8 | col=PF_PJ | dtype=object | tipo_valor=str | exemplo=PJ
param-index=9 | col=PA | dtype=object | tipo_valor=str | exemplo=CRESOL BASER
param-index=10 | col=nr_dia_util | dtype=float64 | tipo_valor=float | exemplo=2.0
param-index=11 | col=quartil | dtype=object | tipo_valor=str | exemplo=Q1
param-index=12 | col=dt_mes | dtype=float64 | tipo_valor=float | exemplo=1.0
param-index=13 | col=mes_abreviado | dtype=object | tipo_valor=str | exemplo=Jan

In [1]:
%load_ext autoreload
%autoreload 2

# import sys 
# sys.path.append("..") 
import sys
sys.path.append(r"C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects")

In [7]:
import importlib 
#from utils import queries
#from utils.mailing import pipelines, metricas_acumuladas, data_processing
#from Renner.src.mailing import metricas_acumuladas, data_processing, pipelines
#from utils.acionamentos import metricas_acumuladas
#from utils.discagens.expert import pipelines, data_processing, metricas_acumuladas
#from utils.acionamentos import pipelines, metricas_acumuladas, data_processing
#from utils.discagens.expert.Ringing import metricas_acumuladas
#from utils.pagamentos import pipelines, metricas_acumuladas, data_processing
#from utils import utils, config, queries
from utils.digital_channels import data_processing, metricas_acumuladas
#from utils.discagens.expert.Ringing import metricas_acumuladas
from utils._database import insert, check, operations
from Cresol.src import database, config, data_loader, pipeline
#from Cresol.src.discagens import discagens_pipeline
#from Renner.src.mailing import data_processing, as
#from Renner.utils import queries

# importlib.reload(data_loader)
# importlib.reload(queries)
# importlib.reload(data_wrangling_mailingHist)
# #importlib.reload(queries)
#importlib.reload(utils)
importlib.reload(database)
importlib.reload(config)
importlib.reload(insert)
importlib.reload(check)
importlib.reload(operations)
#importlib.reload(mailing_pipeline)
importlib.reload(metricas_acumuladas)
importlib.reload(pipeline)
importlib.reload(data_processing)
importlib.reload(data_loader)
#importlib.reload(queries)

In [12]:
import importlib
import Cresol.src.pipeline
importlib.reload(Cresol.src.pipeline)

from Cresol.src.pipeline import _obter_mailing, _inserir_isolado
from Cresol.src.mailing import mailing_pipeline
from Cresol.src.discagens import discagens_pipeline
from Cresol.src.acionamentos import acionamentos_pipeline
from Cresol.src.digital_channels import massivos_pipeline
from Cresol.src.data_loader import load_data_cresol
from utils.db_connection import get_db_connections
from datetime import date
import pandas as pd

# ── Parâmetro de teste ────────────────────────────────────────────────────────
DATA_TESTE_INICIO = date(2026, 1, 1)
DATA_TESTE_FIM    = date(2026, 1, 7)

ciclo_teste = {
    'data_inicio': DATA_TESTE_INICIO,
    'data_fim':    DATA_TESTE_FIM,
    'mes':         f"{DATA_TESTE_INICIO.year}-{DATA_TESTE_INICIO.month:02d}",
}

print(f"🧪 Ciclo de teste: {ciclo_teste['mes']} ({ciclo_teste['data_inicio']} até {ciclo_teste['data_fim']})")

with get_db_connections() as (conn_trc, conn_bd2, conn_src):

    # ── Mailing ───────────────────────────────────────────────────────────────
    try:
        df_mailing_para_dependentes = _obter_mailing(ciclo_teste, conn_trc, conn_bd2, conn_src)
        print(f"✅ Mailing disponível — {len(df_mailing_para_dependentes):,} registros")
    except Exception as e:
        print(f"❌ Mailing falhou — {e}")
        raise

    # ── Discagens ─────────────────────────────────────────────────────────────
    try:
        dados_disc = load_data_cresol(
            data_inicio=str(ciclo_teste['data_inicio']),
            data_fim=str(ciclo_teste['data_fim']),
            datasets_to_load=['discagens_expert', 'dw_calendario'],
            conn_trc=conn_trc, conn_bd2=conn_bd2, conn_src=conn_src,
        )
        resultado_disc = discagens_pipeline.executar_analitico(
            df_discagens_expert=dados_disc.get('discagens_expert', pd.DataFrame()),
            df_mailing_analitico=df_mailing_para_dependentes,
            df_dw_calendario=dados_disc.get('dw_calendario', pd.DataFrame()),
        )
        print(f"✅ Discagens — {len(resultado_disc['analitico']):,} registros")
        _inserir_isolado('discagens', resultado_disc['analitico'], conn_bd2, data_fim=ciclo_teste['data_fim'])
    except Exception as e:
        print(f"❌ Discagens falhou — {e}")
        raise

    # ── Acionamentos ──────────────────────────────────────────────────────────
    try:
        dados_acion = load_data_cresol(
            data_inicio=str(ciclo_teste['data_inicio']),
            data_fim=str(ciclo_teste['data_fim']),
            datasets_to_load=['tab_acionamentos', 'tabulacao_aciona', 'dw_calendario'],
            conn_trc=conn_trc, conn_bd2=conn_bd2, conn_src=conn_src,
        )
        resultado_acion = acionamentos_pipeline.executar_analitico(
            df_tab_acionamentos=dados_acion.get('tab_acionamentos', pd.DataFrame()),
            df_tabulacao_aciona=dados_acion.get('tabulacao_aciona', pd.DataFrame()),
            df_mailing_analitico=df_mailing_para_dependentes,
            df_dw_calendario=dados_acion.get('dw_calendario', pd.DataFrame()),
        )
        print(f"✅ Acionamentos — {len(resultado_acion['analitico']):,} registros")
        _inserir_isolado('acionamentos', resultado_acion['analitico'], conn_bd2, data_fim=ciclo_teste['data_fim'])
    except Exception as e:
        print(f"❌ Acionamentos falhou — {e}")

    # ── Massivos ──────────────────────────────────────────────────────────────
    try:
        dados_mass = load_data_cresol(
            data_inicio=str(ciclo_teste['data_inicio']),
            data_fim=str(ciclo_teste['data_fim']),
            datasets_to_load=['sms', 'rcs', 'email', 'whats', 'dw_calendario'],
            conn_trc=conn_trc, conn_bd2=conn_bd2, conn_src=conn_src,
        )
        resultado_mass = massivos_pipeline.executar_analitico(
            df_sms=dados_mass.get('sms', pd.DataFrame()),
            df_rcs=dados_mass.get('rcs', pd.DataFrame()),
            df_email=dados_mass.get('email', pd.DataFrame()),
            df_whats=dados_mass.get('whats', pd.DataFrame()),
            df_mailing_analitico=df_mailing_para_dependentes,
            df_dw_calendario=dados_mass.get('dw_calendario', pd.DataFrame()),
        )
        print(f"✅ Massivos — {len(resultado_mass['analitico']):,} registros")
        _inserir_isolado('massivos', resultado_mass['analitico'], conn_bd2, data_fim=ciclo_teste['data_fim'])
    except Exception as e:
        print(f"❌ Massivos falhou — {e}")

🧪 Ciclo de teste: 2026-01 (2026-01-01 até 2026-01-07)
🔌 Conectando aos bancos de dados...
✅ Conexões estabelecidas
DEBUG load_data_cresol: conn_trc=True, conn_bd2=True, conn_src=True
DEBUG: usando conexões externas

📊 Carregando dados de 2026-01-01 até 2026-01-07...

C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\utils\data_loader.py:227: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conexao)

[1/2] ✓ Mailing Histórico: 205.345 registros (1m 51s)
[2/2] ✓ Calendário: 4 registros (0s)

✅ Carregamento concluído em 1m 51s
[analytical_mailing_cresol] 📋 Tabela vazia — inserindo todos os 205,345 registros
[analytical_mailing_cresol] 📋 205,345 registros a inserir
───────────────────────────────────────────────────────
[analytical_mailing_cresol] Iniciando insert — 205,345 registros em 21 lote(s)
[analytical_mailing_cresol] ❌ Erro no lote 1: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 7 (""): The supplied value is not a valid instance of data type float. Check the source data for invalid values. An example of an invalid value is data of numeric type with scale greater than precision. (8023) (SQLExecDirectW)')
[analytical_mailing_cresol] Rollback realizado — excluindo registros do dia 2026-03-26...
[analytical_mailing_cresol] 🗑️  Registros do dia 2026-03-26 excluídos com sucesso
✅ Mailing disponível — 205,345 registros
DEBUG load_data_cresol: conn_trc=True, conn_bd2=True, conn_src=True
DEBUG: usando conexões externas

📊 Carregando dados de 2026-01-01 até 2026-01-07...

C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\utils\data_loader.py:227: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conexao)

[1/2] ✓ Discagens Expert: 111.519 registros (48s)
[2/2] ✓ Calendário: 4 registros (0s)

✅ Carregamento concluído em 48s
✅ Discagens — 102,973 registros
[analytical_discagens_expert_cresol] 📋 Tabela vazia — inserindo todos os 102,973 registros
[analytical_discagens_expert_cresol] 📋 102,973 registros a inserir
───────────────────────────────────────────────────────
[analytical_discagens_expert_cresol] Iniciando insert — 102,973 registros em 11 lote(s)
[analytical_discagens_expert_cresol] ❌ Erro no lote 1: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 18 (""): The supplied value is not a valid instance of data type float. Check the source data for invalid values. An example of an invalid value is data of numeric type with scale greater than precision. (8023) (SQLExecDirectW)')
[analytical_discagens_expert_cresol] Rollback realizado — excluindo registros do dia 2026-03-26...
[analytical_discagens_expert_cresol] 🗑️  Registros do dia 2026-03-26 excluídos com sucesso
DEBUG load_data_cresol: conn_trc=True, conn_bd2=True, conn_src=True
DEBUG: usando conexões externas

📊 Carregando dados de 2026-01-01 até 2026-01-07...

C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\utils\data_loader.py:227: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conexao)

[1/3] ✓ Tabulação de Acionamentos: 497 registros (5s)
[2/3] ✓ Tabulação Acionamentos: 9.843 registros (0s)
[3/3] ✓ Calendário: 4 registros (0s)

✅ Carregamento concluído em 5s
✅ Acionamentos — 421 registros
[analytical_acionamentos_cresol] 📋 Tabela vazia — inserindo todos os 421 registros
[analytical_acionamentos_cresol] 📋 421 registros a inserir
───────────────────────────────────────────────────────
[analytical_acionamentos_cresol] Iniciando insert — 421 registros em 1 lote(s)
[analytical_acionamentos_cresol] ❌ Erro no lote 1: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 25 (""): The supplied value is not a valid instance of data type float. Check the source data for invalid values. An example of an invalid value is data of numeric type with scale greater than precision. (8023) (SQLExecDirectW)')
[analytical_acionamentos_cresol] Rollback realizado — excluindo registros do dia 2026-03-26...
[analytical_acionamentos_cresol] 🗑️  Registros do dia 2026-03-26 excluídos com sucesso
DEBUG load_data_cresol: conn_trc=True, conn_bd2=True, conn_src=True
DEBUG: usando conexões externas

📊 Carregando dados de 2026-01-01 até 2026-01-07...

[1/5] ✓ Calendário: 4 registros (0s)

C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\utils\data_loader.py:227: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conexao)

[2/5] ✓ SMS: 8.913 registros (0s)
[3/5] ✓ RCS: 10.753 registros (0s)
[4/5] ✓ Email: 0 registros (2s)

C:\Users\claudiano.alves\Documents\Claudiano\repository\Data-Analysis-Portfolio\Projects\utils\data_loader.py:227: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  df = pd.read_sql(query, conexao)

[5/5] ✓ WhatsApp: 0 registros (0s)

✅ Carregamento concluído em 3s
✅ Massivos — 14,955 registros
[analytical_massivos_cresol] 📋 Tabela vazia — inserindo todos os 14,955 registros
[analytical_massivos_cresol] 📋 14,955 registros a inserir
───────────────────────────────────────────────────────
[analytical_massivos_cresol] Iniciando insert — 14,955 registros em 2 lote(s)
[analytical_massivos_cresol] ❌ Erro no lote 1: ('42000', '[42000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 8 (""): The supplied value is not a valid instance of data type float. Check the source data for invalid values. An example of an invalid value is data of numeric type with scale greater than precision. (8023) (SQLExecDirectW)')
[analytical_massivos_cresol] Rollback realizado — excluindo registros do dia 2026-03-26...
[analytical_massivos_cresol] 🗑️  Registros do dia 2026-03-26 excluídos com sucesso
🔌 Conexão TRC fechada
🔌 Conexão BD2 fechada
🔌 Conexão SRC fechada

In [16]:
import pandas as pd
from datetime import date
from utils._database import insert
from utils.db_connection import get_db_connections

df_teste = pd.DataFrame({
    'DATA': [date(2026, 3, 25)],  # ← DEPOIS da última data da tabela
    'CONTRATO': ['TEST001'],
    'CPF': ['00000000000'],
    'ID_CAR': ['CAR001'],
    'ATRASO': [10],
    'COD_CLI': ['181'],
    'VALOR': [100.0],
    'PF_PJ': ['PF'],
    'PA': ['PA TESTE'],
})

with get_db_connections() as (_, conn_bd2, __):
    print("🧪 Testando insert isolado...")
    
    resultado = insert.inserir_dataframe_incremental(
        df=df_teste,
        tabela='sintetico_cresol',
        col_data='DATA',
        conn=conn_bd2,
        arquivo_log=None,
    )
    
    print(f"✅ Resultado: {resultado}")

🔌 Conectando aos bancos de dados...
✅ Conexões estabelecidas
🧪 Testando insert isolado...
[sintetico_cresol] DEBUG: Verificando datas faltantes...
[sintetico_cresol] DEBUG: col_data=DATA, df.shape=(1, 9)
[sintetico_cresol] DEBUG: colunas df=['DATA', 'CONTRATO', 'CPF', 'ID_CAR', 'ATRASO', 'COD_CLI', 'VALOR', 'PF_PJ', 'PA']
[sintetico_cresol] DEBUG: datas_pendentes=[datetime.date(2026, 2, 1), datetime.date(2026, 2, 2), datetime.date(2026, 2, 3), datetime.date(2026, 2, 4), datetime.date(2026, 2, 5), datetime.date(2026, 2, 6), datetime.date(2026, 2, 7), datetime.date(2026, 2, 8), datetime.date(2026, 2, 9), datetime.date(2026, 2, 10), datetime.date(2026, 2, 11), datetime.date(2026, 2, 12), datetime.date(2026, 2, 13), datetime.date(2026, 2, 14), datetime.date(2026, 2, 15), datetime.date(2026, 2, 16), datetime.date(2026, 2, 17), datetime.date(2026, 2, 18), datetime.date(2026, 2, 19), datetime.date(2026, 2, 20), datetime.date(2026, 2, 21), datetime.date(2026, 2, 22), datetime.date(2026, 2, 23), datetime.date(2026, 2, 24), datetime.date(2026, 2, 25), datetime.date(2026, 2, 26), datetime.date(2026, 2, 27), datetime.date(2026, 2, 28), datetime.date(2026, 3, 1), datetime.date(2026, 3, 2), datetime.date(2026, 3, 3), datetime.date(2026, 3, 4), datetime.date(2026, 3, 5), datetime.date(2026, 3, 6), datetime.date(2026, 3, 7), datetime.date(2026, 3, 8), datetime.date(2026, 3, 9), datetime.date(2026, 3, 10), datetime.date(2026, 3, 11), datetime.date(2026, 3, 12), datetime.date(2026, 3, 13), datetime.date(2026, 3, 14), datetime.date(2026, 3, 15), datetime.date(2026, 3, 16), datetime.date(2026, 3, 17), datetime.date(2026, 3, 18), datetime.date(2026, 3, 19), datetime.date(2026, 3, 20), datetime.date(2026, 3, 21), datetime.date(2026, 3, 22), datetime.date(2026, 3, 23), datetime.date(2026, 3, 24)]
[sintetico_cresol] 📅 Datas faltantes: 52 dia(s)
[sintetico_cresol] ⚠️  Nenhum registro no df para as datas faltantes
✅ Resultado: False
🔌 Conexão TRC fechada
🔌 Conexão BD2 fechada
🔌 Conexão SRC fechada

In [5]:
import numpy as np
from Cresol.src.config import TABELAS

config = TABELAS['discagens']
df = resultado_disc['analitico']

# Seleciona e renomeia colunas como operations.py faz
df_prep = df[list(config['colunas'].keys())].rename(columns=config['colunas'])

print("=== Tipos das colunas ===")
print(df_prep.dtypes)
print()

print("=== Colunas numéricas com NaN ou inf ===")
for col in df_prep.select_dtypes(include=['float', 'int']).columns:
    n_nan = df_prep[col].isna().sum()
    n_inf = np.isinf(df_prep[col].replace({None: np.nan})).sum() if df_prep[col].dtype.kind == 'f' else 0
    if n_nan > 0 or n_inf > 0:
        print(f"  {col}: {n_nan} NaN, {n_inf} inf")

print()
print("=== Amostra das colunas float ===")
print(df_prep.select_dtypes(include='float').describe())

=== Tipos das colunas ===
data                          object
id_discagem                    int64
contrato                      object
agente                        object
ddd                            int64
telefone                       int64
data_encerramento     datetime64[ns]
campanha                       int64
cod_sip                       object
class_retorno                 object
desc_motivo_encerr            object
cod_motivo_encerr              int64
operacao                      object
estado                        object
id_car                       float64
atraso                       float64
cod_cli                      float64
valor                        float64
pf_pj                         object
pa                            object
cpf                           object
nr_dia_util                    int64
quartil                       object
dt_mes                         int64
mes_abreviado                 object
dtype: object

=== Colunas numéricas com NaN ou inf ===
  id_car: 6553 NaN, 0 inf

=== Amostra das colunas float ===
             id_car         atraso        cod_cli         valor
count  96420.000000  102973.000000  102973.000000  1.029730e+05
mean      89.352012     680.152283     192.859740  7.736097e+04
std        0.753819    1062.656791      22.761978  2.952394e+05
min       89.000000    -412.000000     181.000000  0.000000e+00
25%       89.000000      26.000000     181.000000  3.048190e+03
50%       89.000000     118.000000     181.000000  1.196329e+04
75%       89.000000     793.000000     181.000000  4.113556e+04
max       91.000000    7390.000000     254.000000  9.020434e+06

In [11]:
from Cresol.src.config import TABELAS

with get_db_connections() as (_, conn_bd2, __):
    for nome in ['mailing', 'discagens', 'acionamentos', 'massivos']:
        config = TABELAS[nome]
        cursor = conn_bd2.cursor()
        cursor.execute(f"SELECT TOP 0 * FROM {config['tabela']}")
        colunas_banco = [col[0] for col in cursor.description]
        colunas_insert = list(config['colunas'].values())
        
        faltando = [c for c in colunas_insert if c not in colunas_banco]
        
        print(f"[{nome}] tabela: {config['tabela']}")
        print(f"  banco:  {colunas_banco}")
        print(f"  insert: {colunas_insert}")
        print(f"  ❌ faltando no banco: {faltando}")
        print()

🔌 Conectando aos bancos de dados...
✅ Conexões estabelecidas
[mailing] tabela: analytical_mailing_cresol
  banco:  ['id', 'dt_carga', 'data', 'contrato', 'cpf', 'id_car', 'atraso', 'cod_cli', 'valor', 'pf_pj', 'pa']
  insert: ['data', 'contrato', 'cpf', 'id_car', 'atraso', 'cod_cli', 'valor', 'pf_pj', 'pa']
  ❌ faltando no banco: []

[discagens] tabela: analytical_discagens_expert_cresol
  banco:  ['ID', 'dt_carga', 'data', 'id_discagem', 'contrato', 'agente', 'ddd', 'telefone', 'data_encerramento', 'campanha', 'cod_sip', 'class_retorno', 'desc_motivo_encerr', 'cod_motivo_encerr', 'operacao', 'estado', 'id_car', 'atraso', 'cod_cli', 'valor', 'pf_pj', 'pa', 'cpf', 'nr_dia_util', 'quartil', 'dt_mes', 'mes_abreviado']
  insert: ['data', 'id_discagem', 'contrato', 'agente', 'ddd', 'telefone', 'data_encerramento', 'campanha', 'cod_sip', 'class_retorno', 'desc_motivo_encerr', 'cod_motivo_encerr', 'operacao', 'estado', 'id_car', 'atraso', 'cod_cli', 'valor', 'pf_pj', 'pa', 'cpf', 'nr_dia_util', 'quartil', 'dt_mes', 'mes_abreviado']
  ❌ faltando no banco: []

[acionamentos] tabela: analytical_acionamentos_cresol
  banco:  ['ID', 'dt_carga', 'data_aciona', 'hora', 'contrato_fin', 'cpf_dev', 'cod_aciona', 'desc_acionamento', 'cod_recup', 'nome_recup', 'login_recup', 'ultgrupo_recup', 'valorprin_fin', 'statcont_fin', 'dtdevol_fin', 'dtentrada_fin', 'classificacao_acionamento', 'acionamentos', 'cpc', 'cpca', 'promessa', 'descr', 'cpf', 'id_car', 'atraso', 'valor', 'pf_pj', 'pa', 'cod_cli', 'nr_dia_util', 'quartil', 'dt_mes', 'mes_abreviado']
  insert: ['data_aciona', 'hora', 'contrato_fin', 'cpf_dev', 'cod_aciona', 'desc_acionamento', 'cod_recup', 'nome_recup', 'login_recup', 'ultgrupo_recup', 'valorprin_fin', 'statcont_fin', 'dtdevol_fin', 'dtentrada_fin', 'classificacao_acionamento', 'acionamentos', 'cpc', 'cpca', 'promessa', 'descr', 'cpf', 'id_car', 'atraso', 'valor', 'pf_pj', 'pa', 'cod_cli', 'nr_dia_util', 'quartil', 'dt_mes', 'mes_abreviado']
  ❌ faltando no banco: []

[massivos] tabela: analytical_massivos_cresol
  banco:  ['ID', 'dt_carga', 'cpf', 'data', 'canal', 'contrato', 'id_car', 'atraso', 'cod_cli', 'valor', 'pf_pj', 'pa', 'nr_dia_util', 'quartil', 'dt_mes', 'mes_abreviado']
  insert: ['cpf', 'data', 'canal', 'contrato', 'id_car', 'atraso', 'cod_cli', 'valor', 'pf_pj', 'pa', 'nr_dia_util', 'quartil', 'dt_mes', 'mes_abreviado']
  ❌ faltando no banco: []

🔌 Conexão TRC fechada
🔌 Conexão BD2 fechada
🔌 Conexão SRC fechada